"""Run the actual mode controller against Android service doubles; no device claims."""
from pathlib import Path
import subprocess
R=Path(__file__).resolve().parents[1];S=R/'experimental/refactor_hook/java/top/rongshangs/lumacurve/refactor'
O=R/'build/brightness-control-tests';O.mkdir(parents=True,exist_ok=True)
J=R/'build/refactor-diagnostics/json-20240303.jar'
def write(name,text):
 p=O/(name+'.java');p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8');return p
sources=[]
stubs={
'android/os/SystemClock':'''package android.os;public class SystemClock{public static long now=0;public static long uptimeMillis(){return now;}public static long elapsedRealtime(){return now;}}''',
'android/os/Handler':'''package android.os;import java.util.*;public class Handler{public final Map<Runnable,Long> jobs=new IdentityHashMap<>();public boolean post(Runnable r){return postDelayed(r,0);}public boolean postDelayed(Runnable r,long ms){jobs.put(r,SystemClock.now+ms);return true;}public void removeCallbacks(Runnable r){jobs.remove(r);}public void due(){for(int i=0;i<20;i++){Runnable next=null;for(Map.Entry<Runnable,Long> e:jobs.entrySet())if(e.getValue()<=SystemClock.now){next=e.getKey();break;}if(next==null)return;jobs.remove(next);next.run();}throw new AssertionError("timer spin");}}''',
'android/os/PowerManager':'''package android.os;public class PowerManager{public boolean interactive=true;public boolean isInteractive(){return interactive;}}''',
'android/database/ContentObserver':'''package android.database;import android.os.Handler;public class ContentObserver{public ContentObserver(Handler h){}public void onChange(boolean self){}}''',
'android/content/ContentResolver':'''package android.content;import android.database.ContentObserver;import java.util.*;public class ContentResolver{final Map<Object,List<ContentObserver>> callbacks=new HashMap<>();public void registerContentObserver(Object uri,boolean descendants,ContentObserver o){callbacks.computeIfAbsent(uri,k->new ArrayList<>()).add(o);}public void unregisterContentObserver(ContentObserver o){for(List<ContentObserver> list:callbacks.values())list.remove(o);}public void change(Object uri){for(ContentObserver o:new ArrayList<>(callbacks.getOrDefault(uri,Collections.emptyList())))o.onChange(false);}}''',
'android/content/Context':'''package android.content;public class Context{public static final String DISPLAY_SERVICE="display",SENSOR_SERVICE="sensor",KEYGUARD_SERVICE="keyguard";public final ContentResolver resolver=new ContentResolver();public Object display=new android.hardware.display.DisplayManager(),sensor=new android.hardware.SensorManager(),keyguard=new android.app.KeyguardManager();public ContentResolver getContentResolver(){return resolver;}public Object getSystemService(String key){return key.equals(DISPLAY_SERVICE)?display:key.equals(KEYGUARD_SERVICE)?keyguard:sensor;}}''',
'android/app/KeyguardManager':'''package android.app;public class KeyguardManager{public boolean locked;public boolean isKeyguardLocked(){return locked;}}''',
'android/view/Display':'''package android.view;public class Display{public static final int DEFAULT_DISPLAY=0;}''',
'android/hardware/Sensor':'''package android.hardware;public class Sensor{public static final int TYPE_LIGHT=5,REPORTING_MODE_ON_CHANGE=1;public int type,reporting=1;public Sensor(int t){type=t;}public int getType(){return type;}public int getReportingMode(){return reporting;}public String getName(){return "sensor-"+type;}}''',
'android/hardware/SensorEvent':'''package android.hardware;public class SensorEvent{public Sensor sensor;public float[] values;public SensorEvent(Sensor s,float v){sensor=s;values=new float[]{v};}}''',
'android/hardware/SensorEventListener':'''package android.hardware;public interface SensorEventListener{void onSensorChanged(SensorEvent e);void onAccuracyChanged(Sensor s,int a);}''',
'android/hardware/SensorManager':'''package android.hardware;import android.os.Handler;public class SensorManager{public int registers,unregisters;public boolean ok=true;public boolean registerListener(SensorEventListener l,Sensor s,int rate,Handler h){registers++;return ok;}public void unregisterListener(SensorEventListener l){unregisters++;}}''',
'android/provider/Settings':'''package android.provider;import android.content.ContentResolver;import java.util.*;public class Settings{public static class System{public static final String SCREEN_BRIGHTNESS_MODE="mode",SCREEN_BRIGHTNESS="brightness";public static final Map<String,String> values=new HashMap<>();public static int getInt(ContentResolver r,String k,int d){try{return Integer.parseInt(values.get(k));}catch(Exception e){return d;}}public static String getString(ContentResolver r,String k){return values.get(k);}public static boolean putInt(ContentResolver r,String k,int v){values.put(k,""+v);r.change(getUriFor(k));return true;}public static Object getUriFor(String k){return "system/"+k;}}
public static class Global{public static final Map<String,String> values=new HashMap<>();public static String getString(ContentResolver r,String k){return values.get(k);}public static boolean putString(ContentResolver r,String k,String v){if(v==null)values.remove(k);else values.put(k,v);r.change(getUriFor(k));return true;}public static Object getUriFor(String k){return "global/"+k;}}}''',
'android/hardware/display/BrightnessInfo':'''package android.hardware.display;public class BrightnessInfo{public float brightnessMinimum=.001f,brightnessMaximum=1,brightness=.25f;}''',
'android/hardware/display/DisplayManagerGlobal':'''package android.hardware.display;public class DisplayManagerGlobal{public static DisplayManagerGlobal instance=new DisplayManagerGlobal();public BrightnessInfo info=new BrightnessInfo();public static DisplayManagerGlobal getInstance(){return instance;}public BrightnessInfo getBrightnessInfo(int id){if(id!=0)throw new AssertionError("wrong screen");return info;}}''',
'android/hardware/display/DisplayManager':'''package android.hardware.display;public class DisplayManager{public float value=.25f;public int writes;public boolean fail;public DisplayListener listener;public interface DisplayListener{void onDisplayAdded(int id);void onDisplayRemoved(int id);void onDisplayChanged(int id);}public void registerDisplayListener(DisplayListener l,android.os.Handler h){listener=l;}public void unregisterDisplayListener(DisplayListener l){listener=null;}public float getBrightness(int id){if(id!=0)throw new AssertionError("wrong screen");return value;}public void setBrightness(int id,float v){if(fail)throw new IllegalStateException("write rejected");if(id!=0)throw new AssertionError("wrong screen");writes++;value=v;DisplayManagerGlobal.instance.info.brightness=v;}}''',
}
for name,text in stubs.items():sources.append(write(name,text))
base='top/rongshangs/lumacurve/refactor/'
sources.append(write(base+'RawPanelLease', '''package top.rongshangs.lumacurve.refactor;class RawPanelLease{static String token="none";static long until;static int active,target;static boolean ok=true;static boolean healthy(String t){return ok;}static void clear(){token="none";until=0;active=0;target=-1;}static void write(String t,int p,long e,int a,int v){token=t;until=e;active=a;target=v;}}'''))
sources.append(write(base+'RawPanelOutputHooks', '''package top.rongshangs.lumacurve.refactor;class RawPanelOutputHooks{static boolean ok=true;static boolean supports(Class<?> c){return ok;}}'''))
sources.append(write(base+'NativePanelClient', '''package top.rongshangs.lumacurve.refactor;class NativePanelClient{static void require(String s){}}'''))
sources.append(write('android/os/Process', '''package android.os;public class Process{public static int myPid(){return 123;}}'''))
sources.append(write(base+'HookEntry', '''package top.rongshangs.lumacurve.refactor;public class HookEntry{static final ForegroundUser currentUser=new ForegroundUser();static{currentUser.switched(0);}static Object get(Object o,String key)throws Exception{java.lang.reflect.Field f=o.getClass().getDeclaredField(key);f.setAccessible(true);return f.get(o);}}'''))
sources.append(write(base+'HookRuntime', '''package top.rongshangs.lumacurve.refactor;import android.content.*;import android.os.*;import java.util.*;public class HookRuntime{static final String BUILD="test";final Context context=new Context();final Handler handler=new Handler();final PowerManager power=new PowerManager();final Owner owner=new Owner();final String fingerprint="device";boolean closed,on=true,user=true,hdr;String phase="active";int publishes,fastPublishes;List<String> logs=new ArrayList<>();boolean screenOn(){return on;}boolean appliesToUser(){return user;}Boolean hdrActive(){return hdr;}void log(String t){logs.add(t);}void requestRecalculation(){}void queuePublish(){publishes++;}void queueControlPublish(){fastPublishes++;}static String processStart(){return "123";}static Boolean optionalBoolean(Object o,String key){try{return (Boolean)HookEntry.get(o,key);}catch(Exception e){return null;}}
public static class Owner{public int mDisplayId=0;public Impl mAutomaticBrightnessControllerImpl=new Impl();}public static class Impl{public boolean mProximityPositive=false;public ABC mAutomaticBrightnessController=new ABC();public Dual mDualSensorPolicy=new Dual();}public static class ABC{public boolean mAmbientLuxValid=true,mLightSensorEnabled=true;public float mAmbientLux=1;public android.hardware.Sensor mLightSensor=new android.hardware.Sensor(5);}public static class Dual{public float mFovAmplifyFactor=1,mAssistFovAmplifyFactor=1;public android.hardware.Sensor mAssistLightSensor=new android.hardware.Sensor(33171055);}}'''))
sources.append(write(base+'BrightnessControlHostTest', '''package top.rongshangs.lumacurve.refactor;
import org.json.*;import android.os.*;import android.hardware.*;import android.hardware.display.*;import android.provider.Settings;
public class BrightnessControlHostTest{
static int cases;static void check(boolean b){if(!b)throw new AssertionError("case "+cases);cases++;}
static BrightnessControl controller()throws Exception{Settings.Global.values.clear();Settings.System.values.clear();RawPanelLease.ok=true;RawPanelOutputHooks.ok=true;SystemClock.now=0;DisplayManagerGlobal.instance=new DisplayManagerGlobal();HookRuntime s=new HookRuntime();Settings.System.values.put("mode","1");BrightnessControl c=new BrightnessControl(s);c.start();BrightnessControlOptions o=new BrightnessControlOptions();o.darkLock=true;o.minutes=1;c.configure(o);return c;}
static void sample(BrightnessControl c,float front,float back){c.onSensorChanged(new SensorEvent(c.main,front));c.onSensorChanged(new SensorEvent(c.assist,back));}
static void time(BrightnessControl c,long n){SystemClock.now=n;c.s.handler.due();}
static int writes(BrightnessControl c){return ((DisplayManager)c.s.context.display).writes;}
static JSONObject command(BrightnessControl c,String action,String session,double value)throws Exception{String id="req"+cases+SystemClock.now+action;JSONObject r=new JSONObject().put("id",id).put("build","test").put("process_start","123").put("elapsed",SystemClock.now).put("gesture_elapsed",SystemClock.now).put("action",action).put("session",session).put("value",value);Settings.Global.putString(c.s.context.getContentResolver(),BrightnessControl.REQUEST,r.toString());return new JSONObject(Settings.Global.getString(c.s.context.getContentResolver(),BrightnessControl.ACK));}
public static void main(String[] ignored)throws Exception{
BrightnessControlOptions defaults=BrightnessControlOptions.parse(new JSONObject());check(!defaults.darkLock&&defaults.manualPanel);
for(String k:new String[]{"dark_lock_minutes","dark_lock_enter_lux","dark_lock_exit_lux","dark_lock_exit_seconds"})try{BrightnessControlOptions.parse(new JSONObject().put(k,"5"));throw new AssertionError();}catch(IllegalArgumentException e){cases++;}
try{BrightnessControlOptions.parse(new JSONObject().put("dark_lock_enter_lux",20).put("dark_lock_exit_lux",20));throw new AssertionError();}catch(IllegalArgumentException e){cases++;}
try{BrightnessControlOptions.parse(new JSONObject().put("dark_lock_minutes",1.5));throw new AssertionError();}catch(IllegalArgumentException e){cases++;}
BrightnessControl c=controller();check(c.listening&&c.assist.getType()==33171055);sample(c,1,1);check(c.policy.darkSince==0);time(c,59999);check(c.auto()&&writes(c)==0);time(c,60000);check(!c.auto()&&c.owner.equals("dark")&&writes(c)==1);time(c,120000);check(writes(c)==1);
sample(c,1,60);check(!c.auto());time(c,124999);check(!c.auto());time(c,125000);check(c.auto()&&c.owner.equals("none")&&writes(c)==1);
c=controller();sample(c,1,1);time(c,40000);sample(c,1,40);time(c,60000);check(c.auto()&&writes(c)==0);sample(c,1,1);time(c,119999);check(c.auto());time(c,120000);check(!c.auto());
c=controller();sample(c,1,1);Settings.System.putInt(c.s.context.getContentResolver(),"mode",0);time(c,90000);check(!c.auto()&&writes(c)==0&&!c.listening);c.screenOff();check(!c.auto());
c=controller();sample(c,1,1);time(c,60000);c.screenOff();check(c.auto()&&!c.listening&&c.owner.equals("none"));check(c.s.handler.jobs.isEmpty());
c=controller();sample(c,1,1);time(c,60000);Settings.System.putInt(c.s.context.getContentResolver(),"mode",1);check(c.owner.equals("none")&&!c.listening);int before=writes(c);time(c,90000);check(c.auto()&&writes(c)==before);
c=controller();sample(c,1,1);time(c,60000);time(c,63000);Settings.System.putInt(c.s.context.getContentResolver(),"brightness",99);check(!c.auto()&&c.owner.equals("none"));c.stop();check(!c.auto());
c=controller();sample(c,Float.NaN,1);time(c,180000);check(c.auto()&&writes(c)==0);
c=controller();sample(c,1,1);time(c,60000);sample(c,Float.NaN,1);check(c.auto()&&c.owner.equals("none"));
c=controller();sample(c,1,1);((DisplayManager)c.s.context.display).fail=true;time(c,60000);check(c.auto()&&c.owner.equals("none")&&c.failed);
c=controller();sample(c,1,1);time(c,60000);c.s.on=false;c.tick();check(c.auto()&&!c.listening);
c=controller();sample(c,1,1);time(c,60000);c.s.user=false;c.tick();check(c.auto()&&c.owner.equals("none"));
c=controller();check(command(c,"begin","abc",.8).getBoolean("ok"));check(!c.auto()&&writes(c)==1&&c.owner.equals("panel")&&!c.listening);check(command(c,"set","abc",.9).getBoolean("ok"));check(writes(c)==2);check(!command(c,"set","other",.5).getBoolean("ok"));check(writes(c)==2);
Settings.System.putInt(c.s.context.getContentResolver(),"mode",1);check(c.owner.equals("none"));check(!command(c,"set","abc",.5).getBoolean("ok"));check(c.auto()&&writes(c)==2);
check(command(c,"begin","second",.6).getBoolean("ok"));check(!c.auto());check(command(c,"restore","second",0).getBoolean("ok"));check(c.auto()&&c.owner.equals("none"));
c=controller();DisplayManagerGlobal.instance.info.brightnessMaximum=.4f;check(command(c,"begin","clamped",.9).getBoolean("ok"));check(((DisplayManager)c.s.context.display).value==.4f);check(!command(c,"set","clamped",1.1).getBoolean("ok"));check(writes(c)==1);
c=controller();c.options.manualPanel=false;check(!command(c,"begin","disabled",.3).getBoolean("ok"));check(c.auto()&&writes(c)==0);
c=controller();check(command(c,"begin","manual",.6).getBoolean("ok"));c.stop();check(!c.auto()&&c.owner.equals("none"));check(!command(c,"set","manual",.7).getBoolean("ok"));check(writes(c)==1);
c=controller();sample(c,1,1);time(c,60000);c.options.darkLock=false;c.tick();check(c.auto());
c=controller();sample(c,1,1);time(c,60000);String mark=Settings.Global.getString(c.s.context.getContentResolver(),BrightnessControl.OWNER);check(mark!=null);HookRuntime replacement=new HookRuntime();BrightnessControl restarted=new BrightnessControl(replacement);restarted.start();check(restarted.auto()&&Settings.Global.getString(replacement.context.getContentResolver(),BrightnessControl.OWNER)==null);
Settings.System.values.put("mode","0");Settings.Global.values.put(BrightnessControl.OWNER,new JSONObject().put("owner","panel").put("fingerprint","device").put("user",0).toString());BrightnessControl restartPanel=new BrightnessControl(new HookRuntime());restartPanel.start();check(!restartPanel.auto());
c=controller();c.main.reporting=0;sample(c,1,1);time(c,11000);check(c.policy.darkSince<0&&c.auto());check(writes(c)==0);
c=controller();c.s.owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mAmbientLuxValid=false;sample(c,1,1);time(c,120000);check(c.auto()&&writes(c)==0);
c=controller();c.s.owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mAmbientLux=60;sample(c,1,1);time(c,120000);check(c.auto()&&writes(c)==0);
c=controller();sample(c,1,1);time(c,60000);sample(c,1,60);time(c,62000);sample(c,1,1);time(c,65000);check(!c.auto());sample(c,1,60);time(c,70000);check(c.auto());
c=controller();c.s.owner.mAutomaticBrightnessControllerImpl.mDualSensorPolicy.mFovAmplifyFactor=10;c.unlisten();c.tick();sample(c,1,1);time(c,120000);check(c.auto()&&writes(c)==0&&c.mainLux==10);
c=controller();((DisplayManager)c.s.context.display).fail=true;check(!command(c,"begin","failure",.5).getBoolean("ok"));check(c.auto()&&c.owner.equals("none")&&writes(c)==0);
c=controller();check(command(c,"begin","end",.5).getBoolean("ok"));check(command(c,"end","end",0).getBoolean("ok"));check(c.owner.equals("none")&&!c.auto());check(!command(c,"set","end",.8).getBoolean("ok"));check(writes(c)==1);
c=controller();c.s.owner.mDisplayId=1;check(!c.available());check(!command(c,"begin","backscreen",.4).getBoolean("ok"));check(c.auto()&&writes(c)==0);
c=controller();sample(c,1,1);time(c,60000);c.stop();check(c.auto()&&c.s.handler.jobs.isEmpty());
c=controller();c.s.owner.mAutomaticBrightnessControllerImpl.mDualSensorPolicy.mAssistLightSensor.type=99999;check(!c.bindSensors());
c=controller();c.s.owner.mAutomaticBrightnessControllerImpl.mProximityPositive=true;sample(c,1,1);time(c,120000);check(c.auto()&&writes(c)==0);
c=controller();SystemClock.now=100;Settings.System.putInt(c.s.context.getContentResolver(),"mode",1);JSONObject stale=new JSONObject().put("id","stale").put("build","test").put("process_start","123").put("elapsed",100).put("gesture_elapsed",0).put("action","begin").put("session","stale").put("value",.9);Settings.Global.putString(c.s.context.getContentResolver(),BrightnessControl.REQUEST,stale.toString());check(!new JSONObject(Settings.Global.getString(c.s.context.getContentResolver(),BrightnessControl.ACK)).getBoolean("ok"));check(c.auto()&&writes(c)==0);
c=controller();SystemClock.now=5000;stale.put("id","delay").put("elapsed",5000);Settings.Global.putString(c.s.context.getContentResolver(),BrightnessControl.REQUEST,stale.toString());check(!new JSONObject(Settings.Global.getString(c.s.context.getContentResolver(),BrightnessControl.ACK)).getBoolean("ok"));check(c.auto()&&writes(c)==0);
c=controller();sample(c,1,1);time(c,60000);((DisplayManager)c.s.context.display).value=.5f;time(c,62000);check(!c.auto()&&c.owner.equals("none")&&!c.listening);
c=controller();sample(c,1,1);time(c,60000);c.s.hdr=true;c.tick();check(c.auto()&&c.owner.equals("none"));
c=controller();((SensorManager)c.s.context.sensor).ok=false;c.unlisten();c.tick();check(c.failed&&c.auto()&&c.s.phase.equals("active"));((SensorManager)c.s.context.sensor).ok=true;time(c,30000);check(!c.failed&&c.listening);sample(c,1,1);time(c,90000);check(!c.auto()&&c.owner.equals("dark"));
c=controller();sample(c,1,1);time(c,60000);JSONObject old=new JSONObject(Settings.Global.getString(c.s.context.getContentResolver(),BrightnessControl.OWNER));old.put("fingerprint","older firmware");Settings.Global.values.put(BrightnessControl.OWNER,old.toString());BrightnessControl ota=new BrightnessControl(new HookRuntime());ota.start();check(ota.auto());
c=controller();c.s.owner.mAutomaticBrightnessControllerImpl.mDualSensorPolicy.mAssistLightSensor=null;c.unlisten();c.tick();c.onSensorChanged(new SensorEvent(c.main,1));time(c,60000);check(!c.auto());c.onSensorChanged(new SensorEvent(c.main,60));time(c,65000);check(c.auto());
c=controller();c.options.darkLock=false;c.tick();check(!c.listening&&c.auto()&&c.s.handler.jobs.isEmpty());
c=controller();Settings.System.values.put("mode","0");try{c.claim("dark","race",.3f);throw new AssertionError();}catch(IllegalStateException expected){cases++;}check(!c.auto()&&writes(c)==0&&c.owner.equals("none"));
c=controller();check(command(c,"begin","dedupe",.3).getBoolean("ok"));int n=writes(c);c.command();check(writes(c)==n);
c=controller();sample(c,1,1);time(c,60000);Sensor previous=c.main;c.s.owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mLightSensor=new Sensor(5);c.tick();check(c.auto()&&c.owner.equals("none")&&c.main!=previous&&c.listening);check(c.policy.darkSince<0&&writes(c)==1);c.onSensorChanged(new SensorEvent(previous,1));check(Float.isNaN(c.mainLux));sample(c,1,1);time(c,119999);check(c.auto());time(c,120000);check(!c.auto()&&writes(c)==2);
c=controller();sample(c,1,1);time(c,60000);c.s.owner.mAutomaticBrightnessControllerImpl.mDualSensorPolicy.mFovAmplifyFactor=2;c.status();check(c.auto()&&c.owner.equals("none")&&!c.listening&&c.mainScale==2);c.tick();sample(c,1,1);time(c,120000);check(!c.auto());
// Native readiness must be confirmed before blocking any official brightness frame.
c=controller();check(command(c,"raw_begin","raw",1000).getBoolean("ok"));check(!c.auto()&&c.owner.equals("raw_panel")&&writes(c)==0&&RawPanelLease.token.equals("raw"));check(!c.rawOutputBlocked(.3f));check(command(c,"raw_ready","raw",1000).getBoolean("ok"));check(c.rawOutputBlocked(.3f)&&c.rawConfirmed&&RawPanelLease.target==1000&&c.s.fastPublishes>=2);check(!c.rawOutputBlocked(0)&&!c.rawOutputBlocked(-1)&&!c.rawOutputBlocked(Float.NaN));time(c,2000);check(RawPanelLease.until==10000);Settings.System.putInt(c.s.context.getContentResolver(),"mode",1);check(c.owner.equals("none")&&RawPanelLease.token.equals("none")&&!c.rawOutputBlocked(.3f));check(!command(c,"raw_validate","raw",1000).getBoolean("ok"));
// Lock releases write permission while remembering the target. Screen-on alone is not unlock.
c=controller();check(command(c,"raw_begin","screen",9000).getBoolean("ok"));check(command(c,"raw_ready","screen",9000).getBoolean("ok"));c.s.on=false;c.screenOff();check(!c.auto()&&c.owner.equals("raw_panel")&&c.rawPaused&&RawPanelLease.active==0&&RawPanelLease.target==9000&&c.s.fastPublishes>=3);check(!c.rawOutputBlocked(.3f));time(c,10000);check(RawPanelLease.active==0&&RawPanelLease.until==18000);c.s.on=true;((android.app.KeyguardManager)c.s.context.keyguard).locked=true;c.screenOn();check(c.rawPaused&&RawPanelLease.active==0&&!c.rawOutputBlocked(.3f));((android.app.KeyguardManager)c.s.context.keyguard).locked=false;c.screenOn();check(!c.rawPaused&&RawPanelLease.active==1&&RawPanelLease.target==9000&&c.rawOutputBlocked(.3f));check(!c.auto()&&writes(c)==0);c.screenOff();Settings.System.putInt(c.s.context.getContentResolver(),"mode",1);c.screenOn();check(c.owner.equals("none")&&c.rawTarget==-1&&RawPanelLease.until==0);
c=controller();check(command(c,"raw_begin","old",1000).getBoolean("ok"));check(command(c,"raw_begin","new",1000).getBoolean("ok"));check(c.rawWasAuto);check(!command(c,"raw_validate","old",1000).getBoolean("ok"));check(command(c,"raw_validate","new",2000).getBoolean("ok"));check(c.rawTarget==2000&&RawPanelLease.target==2000);c.stop();check(RawPanelLease.token.equals("none")&&c.rawTarget==-1);
c=controller();check(command(c,"raw_begin","failure",1000).getBoolean("ok"));RawPanelLease.ok=false;time(c,2000);check(c.auto()&&c.owner.equals("none")&&RawPanelLease.until==0);
c=controller();Settings.System.values.put("mode","0");check(command(c,"raw_begin","manualfailure",1000).getBoolean("ok"));RawPanelLease.ok=false;time(c,2000);check(!c.auto()&&c.owner.equals("none"));
c=controller();c.options.manualPanel=false;check(!command(c,"raw_begin","disabledraw",1000).getBoolean("ok"));check(c.auto()&&RawPanelLease.token.equals("none"));
c=controller();RawPanelOutputHooks.ok=false;check(!command(c,"raw_begin","unsupportedoutput",1000).getBoolean("ok"));check(c.auto()&&RawPanelLease.until==0);
// DOZE/OFF display events pause before renewal; only the unlocked main screen resumes.
c=controller();check(command(c,"raw_begin","doze",1000).getBoolean("ok"));c.s.on=false;((DisplayManager)c.s.context.display).listener.onDisplayChanged(0);check(c.owner.equals("raw_panel")&&RawPanelLease.active==0&&!c.auto());c.s.on=true;((DisplayManager)c.s.context.display).listener.onDisplayChanged(0);check(c.owner.equals("raw_panel")&&RawPanelLease.active==1&&writes(c)==0);check(command(c,"raw_validate","doze",1000).getBoolean("ok"));
c=controller();c.s.power.interactive=false;check(!command(c,"raw_begin","sleeping",1000).getBoolean("ok"));check(c.auto()&&RawPanelLease.until==0);
c=controller();((android.app.KeyguardManager)c.s.context.keyguard).locked=true;check(!command(c,"raw_begin","locked",1000).getBoolean("ok"));check(c.auto()&&RawPanelLease.until==0);
c=controller();check(command(c,"raw_begin","lostdisplay",1000).getBoolean("ok"));((DisplayManager)c.s.context.display).listener.onDisplayRemoved(0);check(c.owner.equals("none")&&RawPanelLease.until==0);c.close();check(((DisplayManager)c.s.context.display).listener==null);
// Raw-node mode does not depend on framework float range or HBM brightness metadata.
c=controller();DisplayManagerGlobal.instance.info.brightnessMaximum=1.2f;check(!c.available());check(command(c,"raw_begin","hbmrange",1000).getBoolean("ok"));check(!c.auto()&&c.owner.equals("raw_panel")&&writes(c)==0);c.screenOff();check(RawPanelLease.active==0);
c=controller();DisplayManagerGlobal.instance.info=null;check(command(c,"raw_begin","norangedata",1000).getBoolean("ok"));check(!c.auto()&&writes(c)==0);c.screenOff();
System.out.println("Brightness mode control: "+cases+" cases PASS; actual controller with service doubles, Android not tested");
}}
'''))
classes=O/'classes';classes.mkdir(exist_ok=True)
names=['BrightnessControl','BrightnessControlOptions','DarkLockPolicy','FrameworkBrightness','ForegroundUser']
subprocess.run(['javac','-encoding','UTF-8','--release','8','-cp',str(J),'-d',str(classes),*[str(p) for p in sources],*[str(S/(n+'.java')) for n in names]],check=True)
subprocess.run(['java','-cp',str(classes)+';'+str(J),'top.rongshangs.lumacurve.refactor.BrightnessControlHostTest'],check=True)
