"""Exercise production outdoor policy, data ownership and Xposed callbacks with deterministic clocks.
This is a host model, not an Android/device brightness measurement.
"""
from pathlib import Path
import subprocess

ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'experimental/refactor_hook/java/top/rongshangs/lumacurve/refactor'
OUT=ROOT/'build/refactor-outdoor-tests'
OUT.mkdir(exist_ok=True)
JSON=ROOT/'build/refactor-diagnostics/json-20240303.jar'
sources={
'android/os/SystemClock.java':'''package android.os; public class SystemClock {public static long now=1000;public static long uptimeMillis(){return now;}public static long elapsedRealtime(){return now;}}''',
'android/os/Handler.java':'''package android.os;import java.util.*;public class Handler {public Map<Runnable,Long> pending=new HashMap<>();public void removeCallbacks(Runnable r){pending.remove(r);}public boolean postDelayed(Runnable r,long delay){pending.put(r,SystemClock.now+delay);return true;}public void advance(long now){SystemClock.now=now;int count=0;while(true){Runnable due=null;for(Map.Entry<Runnable,Long> e:pending.entrySet())if(e.getValue()<=now){due=e.getKey();break;}if(due==null)return;if(++count>100)throw new AssertionError("timer loop");pending.remove(due);due.run();}}}''',
'de/robv/android/xposed/XC_MethodHook.java':'''package de.robv.android.xposed;import java.util.*;public class XC_MethodHook {protected void beforeHookedMethod(MethodHookParam p)throws Throwable{}protected void afterHookedMethod(MethodHookParam p)throws Throwable{}public class Unhook {Runnable remove;Unhook(Runnable r){remove=r;}public void unhook(){remove.run();}}public static class MethodHookParam{public Object thisObject;public Object[] args;Object result;Throwable error;boolean skip;Map<String,Object> extra=new HashMap<>();public boolean hasThrowable(){return error!=null;}public Object getResult(){return result;}public void setResult(Object r){result=r;skip=true;error=null;}public void setObjectExtra(String k,Object v){extra.put(k,v);}public Object getObjectExtra(String k){return extra.get(k);}}}''',
'de/robv/android/xposed/XposedBridge.java':'''package de.robv.android.xposed;import java.lang.reflect.*;import java.util.*;import java.util.concurrent.Callable;public class XposedBridge{static Map<Method,List<XC_MethodHook>> hooks=new HashMap<>();public static XC_MethodHook.Unhook hookMethod(Method m,XC_MethodHook h){hooks.computeIfAbsent(m,k->new ArrayList<>()).add(h);return h.new Unhook(()->hooks.get(m).remove(h));}public static void log(String s){}public static Object invoke(Object o,String n,Class<?>[] types,Object[] args,Callable<Object> body){try{Method m=o.getClass().getDeclaredMethod(n,types);XC_MethodHook.MethodHookParam p=new XC_MethodHook.MethodHookParam();p.thisObject=o;p.args=args;List<XC_MethodHook> list=hooks.getOrDefault(m,Collections.emptyList());for(XC_MethodHook h:list)h.beforeHookedMethod(p);if(!p.skip)try{p.result=body.call();}catch(Throwable error){p.error=error;}for(int i=list.size()-1;i>=0;i--)list.get(i).afterHookedMethod(p);if(p.error!=null)throw p.error;return p.result;}catch(Throwable ex){throw new RuntimeException(ex);}}}''',
'top/rongshangs/lumacurve/refactor/HookEntry.java':'''package top.rongshangs.lumacurve.refactor;import java.util.*;import java.lang.reflect.*;class HookEntry{static Map<Object,HookRuntime> states=new IdentityHashMap<>();static Field field(Class<?> c,String n)throws Exception{Field f=c.getDeclaredField(n);f.setAccessible(true);return f;}static Object get(Object o,String n)throws Exception{return field(o.getClass(),n).get(o);}static HookRuntime ownerState(Object o){return states.get(o);}}''',
'top/rongshangs/lumacurve/refactor/PipelineHooks.java':'''package top.rongshangs.lumacurve.refactor;class PipelineHooks{static HookRuntime state(Object impl,int role){for(HookRuntime s:HookEntry.states.values())if(((com.android.server.display.DisplayPowerControllerImpl)s.owner).mAutomaticBrightnessControllerImpl==impl&&s.onDisplayThread())return s;return null;}}''',
'top/rongshangs/lumacurve/refactor/HookRuntime.java':'''package top.rongshangs.lumacurve.refactor;import java.util.*;class HookRuntime{Object owner;String outputStrategy(Object d){return strategy;}String phase="active";boolean closed,thread=true,user=true,screen=true,scene=true;String strategy="AutomaticBrightnessStrategy";Boolean hdr=false;int thermalSeverity=0;float batteryTemperature=30,thermalCeiling=43,thermalCooling=1;int publishes,recalculations;android.os.Handler handler=new android.os.Handler();List<String> logs=new ArrayList<>();Power power=new Power();static class Power{boolean low;boolean isPowerSaveMode(){return low;}}Kernel kernel=new Kernel();static class Kernel{boolean auto=true;Object get(String key){return auto;}}final OutdoorController outdoor=new OutdoorController(this);boolean appliesToUser(){return user;}boolean onDisplayThread(){return thread&&!closed;}boolean screenOn(){return screen;}Boolean hdrActive(){return hdr;}boolean normalTuningAllowed(Object a,Object b){return scene&&((com.android.server.display.AutomaticBrightnessController)a).mAmbientLuxValid;}void log(String text){logs.add(text);}void queuePublish(){publishes++;}void requestRecalculation(){recalculations++;}static float optionalNumber(Object o,String f){try{return ((Number)HookEntry.get(o,f)).floatValue();}catch(Exception e){return Float.NaN;}}static Boolean optionalBoolean(Object o,String f){try{return (Boolean)HookEntry.get(o,f);}catch(Exception e){return null;}}}''',
'com/android/server/display/config/HighBrightnessModeData.java':'''package com.android.server.display.config;public class HighBrightnessModeData{public float minimumLux,transitionPoint,minimumHdrPercentOfScreen;public long timeWindowMillis,timeMaxMillis,timeMinMillis;public boolean allowInLowPowerMode,isHighBrightnessModeEnabled;public Object sdrToHdrRatioSpline,refreshRateLimit;public HighBrightnessModeData(float l,float t,long w,long max,long min,boolean low,float hdr,Object spline,Object refresh,boolean enable){minimumLux=l;transitionPoint=t;timeWindowMillis=w;timeMaxMillis=max;timeMinMillis=min;allowInLowPowerMode=low;minimumHdrPercentOfScreen=hdr;sdrToHdrRatioSpline=spline;refreshRateLimit=refresh;isHighBrightnessModeEnabled=enable;}}''',
'com/android/server/display/AutomaticBrightnessController.java':'''package com.android.server.display;public class AutomaticBrightnessController{public float mAmbientLux=30000;public boolean mAmbientLuxValid=true;}''',
'com/android/server/display/BrightnessRangeControllerImpl.java':'''package com.android.server.display;import de.robv.android.xposed.XposedBridge;public class BrightnessRangeControllerImpl{public boolean mSupportDynamicBrightnessRange=true,mAutoBrightnessEnabled=true;public float mMaxBrightness=.75f;public float getCurrentBrightnessMax(HighBrightnessModeController h){return (Float)XposedBridge.invoke(this,"getCurrentBrightnessMax",new Class<?>[]{HighBrightnessModeController.class},new Object[]{h},()->mSupportDynamicBrightnessRange&&mAutoBrightnessEnabled?mMaxBrightness:h.getCurrentBrightnessMax());}}''',
'com/android/server/display/BrightnessRangeController.java':'''package com.android.server.display;public class BrightnessRangeController{public BrightnessRangeControllerImpl mBrightnessRangeControllerImpl=new BrightnessRangeControllerImpl();}''',
'com/android/server/display/DisplayPowerController.java':'''package com.android.server.display;public class DisplayPowerController{public BrightnessRangeController mBrightnessRangeController=new BrightnessRangeController();}''',
'com/android/server/display/HbmEvent.java':'''package com.android.server.display;public class HbmEvent{long begin,end;public HbmEvent(long b,long e){begin=b;end=e;}public long getStartTimeMillis(){return begin;}public long getEndTimeMillis(){return end;}}''',
'com/android/server/display/HighBrightnessModeMetadata.java':'''package com.android.server.display;import java.util.*;public class HighBrightnessModeMetadata{public long start=-1;public ArrayDeque<HbmEvent> events=new ArrayDeque<>();public long getRunningStartTimeMillis(){return start;}public ArrayDeque<HbmEvent> getHbmEventQueue(){return events;}}''',
'com/android/server/display/HighBrightnessModeController.java':'''package com.android.server.display;import com.android.server.display.config.*;import de.robv.android.xposed.XposedBridge;public class HighBrightnessModeController{
 public float mBrightnessMax=1,mBrightnessMin=0,mAmbientLux=30000,mBrightness=.5f;public boolean mIsAutoBrightnessEnabled=true,mIsAutoBrightnessOffByState=false,mIsTimeAvailable=true,mIsInAllowedAmbientRange=true,mIsBlockedByLowPowerMode=false,mIsHdrLayerPresent=false,mHbmControllerIsEnabled=true,mDolbyEnable=false;public HighBrightnessModeData mHbmData=new HighBrightnessModeData(20000,.6f,600000,180000,30000,false,.5f,new Object(),new Object(),true);public HighBrightnessModeMetadata mHighBrightnessModeMetadata=new HighBrightnessModeMetadata();public float peak=.85f;public int recalc;public boolean throwing;
 public float getCurrentBrightnessMax(){return (Float)XposedBridge.invoke(this,"getCurrentBrightnessMax",new Class<?>[]{},new Object[]{},()->(!mHbmControllerIsEnabled||isHbmCurrentlyAllowed())?Math.min(mBrightnessMax,peak):mHbmData.transitionPoint);}
 public float getNormalBrightnessMax(){return mHbmData.transitionPoint;}public boolean isHbmCurrentlyAllowed(){return !mHbmControllerIsEnabled?mBrightness>mHbmData.transitionPoint:mIsAutoBrightnessEnabled&&mIsTimeAvailable&&mIsInAllowedAmbientRange&&!mIsBlockedByLowPowerMode;}
 public void onAmbientLuxChange(float l){XposedBridge.invoke(this,"onAmbientLuxChange",new Class<?>[]{float.class},new Object[]{l},()->{mAmbientLux=l;mIsInAllowedAmbientRange=l>=mHbmData.minimumLux;recalculateTimeAllowance();return null;});}
 private void recalculateTimeAllowance(){if(throwing)throw new IllegalStateException("recalc");recalc++;}
 public void setAutoBrightnessEnabled(int state){XposedBridge.invoke(this,"setAutoBrightnessEnabled",new Class<?>[]{int.class},new Object[]{state},()->{mIsAutoBrightnessOffByState=state==3;if(mHbmControllerIsEnabled)mIsAutoBrightnessEnabled=state==1||state==3;return null;});}
 public void resetHbmData(){XposedBridge.invoke(this,"resetHbmData",new Class<?>[]{},new Object[]{},()->null);}public void updateHbmMode(){XposedBridge.invoke(this,"updateHbmMode",new Class<?>[]{},new Object[]{},()->null);}
}''',
'com/android/server/display/AutomaticBrightnessControllerImpl.java':'''package com.android.server.display;import de.robv.android.xposed.XposedBridge;public class AutomaticBrightnessControllerImpl {public AutomaticBrightnessController mAutomaticBrightnessController=new AutomaticBrightnessController();public boolean mIsOverrideDragPolicy=false;public float getOverrideLimitBrightness(float b,boolean manual,float lux){return (Float)XposedBridge.invoke(this,"getOverrideLimitBrightness",new Class<?>[]{float.class,boolean.class,float.class},new Object[]{b,manual,lux},()->b);}}''',
'com/android/server/display/brightness/BrightnessReason.java':'''package com.android.server.display.brightness;public class BrightnessReason {int modifiers;public void addModifier(int m){modifiers|=m;}public int getModifier(){return modifiers;}public void setModifier(int m){modifiers=m;}}''',
'com/android/server/display/DisplayPowerControllerImpl.java':'''package com.android.server.display;import de.robv.android.xposed.XposedBridge;import com.android.server.display.brightness.*;public class DisplayPowerControllerImpl{
 public DisplayPowerController mDisplayPowerController=new DisplayPowerController();public HighBrightnessModeController mHbmController=new HighBrightnessModeController();public AutomaticBrightnessControllerImpl mAutomaticBrightnessControllerImpl=new AutomaticBrightnessControllerImpl();public float thermal=.7f,battery=1,power=1;public int animationCalls;public float opr=1;public boolean mAutoBrightnessEnable=true,hdrScene,privacy,throwPrivacy,throwSdr;
 public float getMaxHbmBrightnessForPeak(){return (Float)XposedBridge.invoke(this,"getMaxHbmBrightnessForPeak",new Class<?>[]{},new Object[]{},()->.85f);}
 private boolean shouldUsePrivacyOprBrightness(){if(throwPrivacy)throw new IllegalStateException("privacy unavailable");return privacy;}
 private boolean isHdrScene(){return hdrScene;}
 public float adjustBrightnessByOpr(float b,BrightnessReason reason){return (Float)XposedBridge.invoke(this,"adjustBrightnessByOpr",new Class<?>[]{float.class,BrightnessReason.class},new Object[]{b,reason},()->{if(b>opr)reason.addModifier(8192);return Math.min(b,opr);});}
 private float adjustBrightnessByThermal(float b,boolean hdr,BrightnessReason reason){return (Float)XposedBridge.invoke(this,"adjustBrightnessByThermal",new Class<?>[]{float.class,boolean.class,BrightnessReason.class},new Object[]{b,hdr,reason},()->Math.min(b,thermal));}
 private float adjustBrightnessByBattery(float b,BrightnessReason reason){return (Float)XposedBridge.invoke(this,"adjustBrightnessByBattery",new Class<?>[]{float.class,BrightnessReason.class},new Object[]{b,reason},()->Math.min(b,battery));}
 public float adjustSdrBrightness(float b,boolean auto,BrightnessReason reason,boolean fast,boolean dim){return (Float)XposedBridge.invoke(this,"adjustSdrBrightness",new Class<?>[]{float.class,boolean.class,BrightnessReason.class,boolean.class,boolean.class},new Object[]{b,auto,reason,fast,dim},()->{float out=adjustBrightnessByOpr(dim?Math.min(b,.4f):b,reason);if(throwSdr)throw new IllegalStateException("SDR failed");out=Math.min(out,getMaxHbmBrightnessForPeak());out=Math.min(out,power);out=adjustBrightnessByThermal(out,false,reason);out=adjustBrightnessByBattery(out,reason);animationCalls++;return out;});}
}''',
'top/rongshangs/lumacurve/refactor/OutdoorTest.java':r'''package top.rongshangs.lumacurve.refactor;
import org.json.*;import com.android.server.display.*;import com.android.server.display.config.*;import com.android.server.display.brightness.*;import android.os.*;
public class OutdoorTest{static int count;static void check(boolean b){if(!b)throw new AssertionError("case "+count);count++;}static void eq(float a,float b){check(Math.abs(a-b)<.0001);}static void bad(JSONObject j){try{OutdoorOptions.parse(j);throw new AssertionError();}catch(IllegalArgumentException expected){count++;}}
 static OutdoorOptions enabled()throws Exception{return OutdoorOptions.parse(new JSONObject().put("outdoor_enabled",true));}
 static void activate(HookRuntime s)throws Exception{s.outdoor.configure(enabled());long at=SystemClock.now;s.handler.advance(at+3000);check(s.outdoor.policy.active);}
 public static void main(String[] args)throws Exception{
  OutdoorOptions off=OutdoorOptions.parse(new JSONObject());check(!off.flags[0]);JSONObject wire=new JSONObject();off.put(wire);check(OutdoorOptions.parse(wire).same(off));
  for(int i=0;i<OutdoorOptions.KEYS.length;i++){bad(new JSONObject().put(OutdoorOptions.KEYS[i],OutdoorOptions.MIN[i]-1));bad(new JSONObject().put(OutdoorOptions.KEYS[i],OutdoorOptions.MAX[i]+1));bad(new JSONObject().put(OutdoorOptions.KEYS[i],"1"));}
  for(String f:OutdoorOptions.FLAGS)bad(new JSONObject().put(f,1));bad(new JSONObject().put("outdoor_hbm_tuning",true));bad(new JSONObject().put("outdoor_enabled",true).put("outdoor_full_lux",10000));bad(new JSONObject().put("outdoor_enter_ms",500.5));
  try{enabled().verify(new JSONObject());throw new AssertionError();}catch(IllegalArgumentException ok){count++;}
  OutdoorOptions o=enabled();OutdoorPolicy p=new OutdoorPolicy();check(!p.step(o,30000,1000,null));check(p.next==4000);check(!p.step(o,9000,2000,null));check(p.enterAt==-1);check(!p.step(o,30000,3000,null));check(p.step(o,30000,6000,null));check(p.started==6000);
  check(p.step(o,6000,7000,null));check(p.reason.equals("exit_confirm"));check(p.step(o,8000,11000,null));check(p.exitAt==-1);check(p.step(o,6000,12000,null));check(!p.step(o,6000,17000,null));check(p.reason.equals("low_lux"));
  p.step(o,30000,18000,null);p.step(o,30000,21000,null);check(!p.step(o,30000,201000,null));check(p.next==261000);check(!p.step(o,30000,230000,null));check(!p.step(o,30000,261000,null));check(p.step(o,30000,264000,null));
  p.manual(30000,265000);check(!p.step(o,31000,400000,null));check(!p.step(o,1000,401000,null));check(!p.step(o,30000,402000,null));check(p.step(o,30000,405000,null));check(!p.step(o,30000,406000,"screen_off"));check(p.manualAt==-1);check(p.cooldownUntil>406000);check(!p.step(o,30000,407000,null));
  eq(OutdoorPolicy.target(o,30000,.3f,.6f,1),.94f);eq(OutdoorPolicy.target(o,30000,.97f,.6f,1),.97f);eq(OutdoorPolicy.target(o,30000,.3f,.6f,.6f),.6f);eq(OutdoorPolicy.target(o,Float.NaN,.3f,.6f,1),.3f);eq(OutdoorPolicy.target(o,30000,.3f,.6f,Float.NaN),.3f);eq(OutdoorPolicy.target(o,30000,.3f,.6f,.5f),.3f);
  check(OutdoorPolicy.budget(600000,180000,30000,2)==360000);check(OutdoorPolicy.budget(200000,180000,30000,2)==200000);try{OutdoorPolicy.budget(600000,0,0,2);throw new AssertionError();}catch(IllegalArgumentException ok){count++;}
  DisplayPowerControllerImpl owner=new DisplayPowerControllerImpl();HookRuntime s=new HookRuntime();s.owner=owner;HookEntry.states.put(owner,s);OutdoorTuning.install(owner.getClass());check(s.outdoor.supported());check(s.outdoor.rangeSupported());HbmAccess h=s.outdoor.binding();check(h.tunable());
  HighBrightnessModeData baseline=owner.mHbmController.mHbmData;OutdoorOptions config=enabled();config.flags[1]=true;config.values[8]=.5;config.values[9]=2;s.outdoor.configure(config);check(owner.mHbmController.mHbmData==baseline);s.handler.advance(SystemClock.now+3000);HighBrightnessModeData clone=owner.mHbmController.mHbmData;check(clone!=baseline);eq(baseline.minimumLux,20000);eq(clone.minimumLux,10000);check(clone.timeMaxMillis==360000&&baseline.timeMaxMillis==180000);check(clone.sdrToHdrRatioSpline==baseline.sdrToHdrRatioSpline&&clone.refreshRateLimit==baseline.refreshRateLimit);
  s.outdoor.tick();check(owner.mHbmController.mHbmData==clone);s.handler.advance(SystemClock.now+3000);check(s.outdoor.policy.active);
  eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.8125f);check(s.outdoor.boosts>0);eq(owner.adjustSdrBrightness(.8125f,true,new BrightnessReason(),false,false),.7f);check(owner.animationCalls==1);check(s.outdoor.status().getJSONArray("limit_trace").length()>0);
  config.flags[2]=true;s.outdoor.configure(config); // same object is unsupported usage in UI; emulate a parsed distinct submission below.
  config=OutdoorOptions.parse(new JSONObject().put("outdoor_enabled",true).put("outdoor_range_unlock",true));s.outdoor.configure(config);s.handler.advance(SystemClock.now+3000);eq(owner.mHbmController.getCurrentBrightnessMax(),1);eq(owner.getMaxHbmBrightnessForPeak(),1);eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.94f);eq(owner.adjustSdrBrightness(.94f,true,new BrightnessReason(),false,false),.7f);
  owner.mHbmController.mIsTimeAvailable=false;eq(owner.mHbmController.getCurrentBrightnessMax(),.6f);eq(owner.getMaxHbmBrightnessForPeak(),.85f);owner.mHbmController.mIsTimeAvailable=true;
  BrightnessRangeControllerImpl dynamic=owner.mDisplayPowerController.mBrightnessRangeController.mBrightnessRangeControllerImpl;eq(dynamic.getCurrentBrightnessMax(owner.mHbmController),1);check(s.outdoor.dynamicRaises>0);owner.mHbmController.mIsTimeAvailable=false;eq(dynamic.getCurrentBrightnessMax(owner.mHbmController),.75f);owner.mHbmController.mIsTimeAvailable=true;dynamic.mAutoBrightnessEnabled=false;eq(dynamic.getCurrentBrightnessMax(owner.mHbmController),1);dynamic.mAutoBrightnessEnabled=true;
  s.hdr=true;eq(owner.mHbmController.getCurrentBrightnessMax(),.85f);eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.3f);check(!s.outdoor.policy.active);s.hdr=false;
  s.outdoor.stop();check(owner.mHbmController.mHbmData==baseline);check(s.handler.pending.isEmpty());eq(owner.mHbmController.getCurrentBrightnessMax(),.85f);
  eq(dynamic.getCurrentBrightnessMax(owner.mHbmController),.75f);eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.3f);
  activate(s);owner.mHbmController.setAutoBrightnessEnabled(3);check(!s.outdoor.policy.active&&s.outdoor.policy.reason.equals("screen_off"));eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.3f);owner.mHbmController.setAutoBrightnessEnabled(1);s.outdoor.stop();
  activate(s);s.batteryTemperature=43;s.outdoor.tick();check(s.outdoor.policy.reason.equals("temperature"));s.batteryTemperature=42.5f;s.outdoor.tick();check(s.outdoor.policy.reason.equals("temperature"));s.batteryTemperature=42;s.outdoor.tick();check(s.outdoor.policy.reason.equals("cooldown"));s.batteryTemperature=30;s.outdoor.stop();
  for(String block:new String[]{"user","screen","hdr","power","temperature","scene","manual","invalid","thread","output"}){s.outdoor.stop();s.user=true;s.screen=true;s.hdr=false;s.power.low=false;s.batteryTemperature=30;s.scene=true;s.thread=true;s.strategy="AutomaticBrightnessStrategy";owner.mAutomaticBrightnessControllerImpl.mIsOverrideDragPolicy=false;owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mAmbientLuxValid=true;activate(s);
    if(block.equals("user"))s.user=false;if(block.equals("screen"))s.screen=false;if(block.equals("hdr"))s.hdr=null;if(block.equals("power"))s.power.low=true;if(block.equals("temperature"))s.batteryTemperature=Float.NaN;if(block.equals("scene"))s.scene=false;if(block.equals("manual"))owner.mAutomaticBrightnessControllerImpl.mIsOverrideDragPolicy=true;if(block.equals("invalid"))owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mAmbientLuxValid=false;if(block.equals("thread"))s.thread=false;if(block.equals("output"))s.strategy="TemporaryBrightnessStrategy";
    float got=owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000);eq(got,.3f);}
  s.thread=true;s.strategy="AutomaticBrightnessStrategy";s.scene=true;s.user=true;s.screen=true;s.hdr=false;s.power.low=false;s.batteryTemperature=30;owner.mAutomaticBrightnessControllerImpl.mIsOverrideDragPolicy=false;owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mAmbientLuxValid=true;s.outdoor.stop();activate(s);
  owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,true,30000);eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.3f);s.handler.advance(SystemClock.now+600000);eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.3f);
  s.screen=false;s.outdoor.tick();s.screen=true;s.outdoor.tick();s.handler.advance(SystemClock.now+3000);check(s.outdoor.policy.active);long deadline=s.outdoor.policy.started+180000;s.handler.advance(deadline);check(!s.outdoor.policy.active&&s.outdoor.policy.reason.equals("cooldown"));
  s.outdoor.stop();owner.mHbmController.mHbmControllerIsEnabled=false;owner.mHbmController.mIsAutoBrightnessEnabled=false;check(!h.tunable());activate(s);check(s.outdoor.status().has("controller_managed"));check(!s.outdoor.status().has("hbm_remaining_estimate_ms"));owner.mHbmController.mHbmControllerIsEnabled=true;owner.mHbmController.mIsAutoBrightnessEnabled=true;
  // A full-strength auto target uses the mapping range, but downstream safety caps still run.
  s.outdoor.stop();config=enabled();config.flags[2]=true;config.values[5]=1;int recalcBefore=s.recalculations;s.outdoor.configure(config);s.handler.advance(SystemClock.now+3000);check(s.recalculations>recalcBefore);
  eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),1);eq(owner.mHbmController.getCurrentBrightnessMax(),1);eq(dynamic.getCurrentBrightnessMax(owner.mHbmController),1);eq(owner.getMaxHbmBrightnessForPeak(),1);
  eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),.7f);owner.mHbmController.mIsTimeAvailable=false;eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.6f);owner.mHbmController.mIsTimeAvailable=true;
  recalcBefore=s.recalculations;s.handler.advance(s.outdoor.policy.started+180000);check(!s.outdoor.policy.active&&s.recalculations>recalcBefore);eq(owner.mHbmController.getCurrentBrightnessMax(),.85f);eq(owner.mAutomaticBrightnessControllerImpl.getOverrideLimitBrightness(.3f,false,30000),.3f);
  s.outdoor.stop();config=enabled();config.flags[1]=true;s.outdoor.configure(config);HighBrightnessModeData external=new HighBrightnessModeData(25000,.5f,600000,120000,30000,false,.5f,null,null,true);owner.mHbmController.mHbmData=external;s.outdoor.stop();check(owner.mHbmController.mHbmData==external);
  h=s.outdoor.binding();owner.mHbmController.mHighBrightnessModeMetadata.events.add(new HbmEvent(1000,2000));long now=SystemClock.now;check(h.remaining(now)==120000);check(owner.mHbmController.mHighBrightnessModeMetadata.events.size()==1);owner.mHbmController.mHighBrightnessModeMetadata.start=now-10000;check(h.remaining(now)==110000);owner.mHbmController.mHighBrightnessModeMetadata.start=now+100;check(h.remaining(now)==-1);
  s.outdoor.stop();config=enabled();config.flags[1]=true;owner.mHbmController.throwing=true;s.outdoor.configure(config);s.handler.advance(SystemClock.now+3000);check(s.outdoor.policy.reason.equals("error"));check(owner.mHbmController.mHbmData==external);check(s.handler.pending.isEmpty());s.outdoor.tick();check(s.outdoor.policy.reason.equals("error"));owner.mHbmController.throwing=false;s.outdoor.configure(enabled());s.handler.advance(SystemClock.now+3000);check(s.outdoor.policy.active);s.outdoor.stop();

  // Reproduce the supplied firmware trace: a full target is reduced to .57015526 by OPR.
  s.outdoor.stop();owner.opr=.57015526f;owner.thermal=owner.battery=owner.power=1;
  config=OutdoorOptions.parse(new JSONObject().put("outdoor_enabled",true).put("outdoor_range_unlock",true).put("outdoor_strength",1));
  check(!config.flags[3]);s.outdoor.configure(config);s.handler.advance(SystemClock.now+3000);
  BrightnessReason reason=new BrightnessReason();eq(owner.adjustSdrBrightness(1,true,reason,false,false),owner.opr);check(reason.getModifier()==8192);
  check(s.outdoor.oprSupported());check(s.outdoor.status().optBoolean("opr_supported"));
  bad(new JSONObject().put("outdoor_enabled",true).put("outdoor_opr_relax",true));
  bad(new JSONObject().put("outdoor_opr_relax",true));
  config=OutdoorOptions.parse(new JSONObject().put("outdoor_enabled",true).put("outdoor_range_unlock",true).put("outdoor_opr_relax",true).put("outdoor_strength",1));
  JSONObject caps=new JSONObject().put("outdoor_supported",true).put("outdoor_range_supported",true);
  try{config.verify(caps);throw new AssertionError();}catch(IllegalArgumentException expected){count++;}config.verify(caps.put("outdoor_opr_supported",true));
  s.outdoor.configure(config);s.handler.advance(SystemClock.now+3000);long raises=s.outdoor.oprRaises;
  reason=new BrightnessReason();reason.addModifier(2);eq(owner.adjustSdrBrightness(1,true,reason,false,false),1);check(reason.getModifier()==2);check(s.outdoor.oprRaises==raises+1);check(OutdoorOpr.current.get()==null);
  reason=new BrightnessReason();reason.addModifier(8192|2);eq(owner.adjustSdrBrightness(1,true,reason,false,false),1);check(reason.getModifier()==(8192|2));
  eq(owner.adjustBrightnessByOpr(1,new BrightnessReason()),owner.opr);eq(owner.adjustSdrBrightness(1,false,new BrightnessReason(),false,false),owner.opr);
  eq(owner.adjustSdrBrightness(.3f,true,new BrightnessReason(),false,false),.3f);eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,true),.4f);
  owner.thermal=.7f;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),.7f);owner.thermal=1;
  owner.battery=.65f;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),.65f);owner.battery=1;
  owner.power=.6f;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),.6f);owner.power=1;
  owner.privacy=true;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);owner.privacy=false;
  owner.hdrScene=true;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);owner.hdrScene=false;
  owner.mAutoBrightnessEnable=false;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);owner.mAutoBrightnessEnable=true;
  owner.throwPrivacy=true;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);owner.throwPrivacy=false;
  owner.throwSdr=true;try{owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false);throw new AssertionError();}catch(RuntimeException expected){count++;}check(OutdoorOpr.current.get()==null);owner.throwSdr=false;
  owner.opr=Float.NaN;check(Float.isNaN(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false)));owner.opr=.57015526f;
  eq(s.outdoor.opr(Float.NaN,.5f),.5f);eq(s.outdoor.opr(1.5f,.5f),.5f);eq(s.outdoor.opr(.4f,.5f),.5f);
  owner.mHbmController.mIsTimeAvailable=false;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);owner.mHbmController.mIsTimeAvailable=true;
  owner.mHbmController.mIsInAllowedAmbientRange=false;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);owner.mHbmController.mIsInAllowedAmbientRange=true;
  owner.mHbmController.mBrightnessMax=.8f;eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),.8f);owner.mHbmController.mBrightnessMax=1;
  DisplayPowerControllerImpl other=new DisplayPowerControllerImpl();other.opr=.5f;eq(other.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),.5f);
  OutdoorOpr.Frame outer=new OutdoorOpr.Frame(other,true);OutdoorOpr.current.set(outer);eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),1);check(OutdoorOpr.current.get()==outer);OutdoorOpr.current.remove();
  for(String gate:new String[]{"screen","user","thread","hdr","power","temperature","manual","output","lux"}){
   if(gate.equals("screen"))s.screen=false;if(gate.equals("user"))s.user=false;if(gate.equals("thread"))s.thread=false;if(gate.equals("hdr"))s.hdr=true;if(gate.equals("power"))s.power.low=true;if(gate.equals("temperature"))s.batteryTemperature=Float.NaN;if(gate.equals("manual"))s.kernel.auto=false;if(gate.equals("output"))s.strategy="TemporaryBrightnessStrategy";if(gate.equals("lux"))owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mAmbientLux=500;
   eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);check(OutdoorOpr.current.get()==null);
   s.screen=s.user=s.thread=true;s.hdr=false;s.power.low=false;s.batteryTemperature=30;s.kernel.auto=true;s.strategy="AutomaticBrightnessStrategy";owner.mAutomaticBrightnessControllerImpl.mAutomaticBrightnessController.mAmbientLux=30000;s.outdoor.stop();s.outdoor.configure(config);s.handler.advance(SystemClock.now+3000);
  }
  s.handler.advance(s.outdoor.policy.started+180000);eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);check(!s.outdoor.policy.active);
  s.outdoor.stop();eq(owner.adjustSdrBrightness(1,true,new BrightnessReason(),false,false),owner.opr);check(OutdoorOpr.current.get()==null);
  System.out.println("Outdoor production hooks: "+count+" cases PASS; deterministic OEM model, device not verified");
 }
}'''
}
for path,text in sources.items():
    file=OUT/path;file.parent.mkdir(parents=True,exist_ok=True);file.write_text(text,encoding='utf-8')
classes=OUT/'classes';classes.mkdir(exist_ok=True)
production=[SRC/(name+'.java') for name in ['OutdoorOptions','OutdoorPolicy','HbmAccess','OutdoorController','OutdoorTuning','OutdoorOpr','ThermalPolicy','AdvancedPolicy']]
subprocess.run(['javac','-encoding','UTF-8','--release','8','-cp',str(JSON),'-d',str(classes),*map(str,production),*[str(OUT/p) for p in sources]],check=True)
subprocess.run(['java','-cp',str(classes)+';'+str(JSON),'top.rongshangs.lumacurve.refactor.OutdoorTest'],check=True)
