"""Exercise production inline scene forms with widget doubles, not Android rendering."""
from pathlib import Path
import os,subprocess
R=Path(__file__).resolve().parents[1];S=R/'experimental/refactor_hook/java/top/rongshangs/lumacurve/refactor'
O=R/'build/refactor-scene-settings-tests';O.mkdir(parents=True,exist_ok=True);J=R/'build/refactor-diagnostics/json-20240303.jar'
stubs={
'android/R.java':'package android;public class R{public static class layout{public static int simple_spinner_dropdown_item;}}',
'android/os/SystemClock.java':'package android.os;public class SystemClock{public static long elapsedRealtime(){return 1000;}}',
'android/text/Editable.java':'package android.text;public interface Editable extends CharSequence{}',
'android/text/TextWatcher.java':'package android.text;public interface TextWatcher{void beforeTextChanged(CharSequence s,int start,int count,int after);void onTextChanged(CharSequence s,int start,int before,int count);void afterTextChanged(Editable s);}',
'android/text/InputType.java':'package android.text;public class InputType{public static int TYPE_CLASS_NUMBER=2,TYPE_NUMBER_FLAG_DECIMAL=8192;}',
'android/view/View.java':'''package android.view;public class View{public static final int VISIBLE=0,GONE=8;static int next;int id,visibility;boolean enabled=true;public static int generateViewId(){return ++next;}public void setId(int n){id=n;}public int getId(){return id;}public void setVisibility(int n){visibility=n;}public int getVisibility(){return visibility;}public void setEnabled(boolean b){enabled=b;}public boolean isEnabled(){return enabled;}public void setPadding(int a,int b,int c,int d){}public void setMinHeight(int n){}}''',
'android/widget/LinearLayout.java':'''package android.widget;import android.view.*;import java.util.*;public class LinearLayout extends View{public static final int VERTICAL=1;public final List<View> children=new ArrayList<>();public LinearLayout(Object c){}public void addView(View v){children.add(v);}public void addView(View v,LayoutParams p){children.add(v);}public void setOrientation(int o){}public static class LayoutParams{public LayoutParams(int w,int h){}}}''',
'android/widget/TextView.java':'''package android.widget;import android.view.*;public class TextView extends View{public CharSequence value="";public TextView(Object c){}public void setText(CharSequence s){value=s;}public CharSequence getText(){return value;}public void setTextSize(float n){}}''',
'android/widget/EditText.java':'''package android.widget;import android.text.*;import java.util.*;public class EditText extends TextView{final List<TextWatcher> watchers=new ArrayList<>();public EditText(Object c){super(c);}public void setInputType(int n){}public void addTextChangedListener(TextWatcher w){watchers.add(w);}public void setText(CharSequence s){super.setText(s);for(TextWatcher w:watchers)w.onTextChanged(s,0,0,s.length());}}''',
'android/widget/Switch.java':'''package android.widget;public class Switch extends TextView{boolean checked;Listener listener;public interface Listener{void onCheckedChanged(Switch v,boolean on);}public Switch(Object c){super(c);}public boolean isChecked(){return checked;}public void setChecked(boolean on){if(checked==on)return;checked=on;if(listener!=null)listener.onCheckedChanged(this,on);}public void setOnCheckedChangeListener(Listener l){listener=l;}}''',
'android/widget/RadioButton.java':'''package android.widget;public class RadioButton extends Switch{public RadioButton(Object c){super(c);}}''',
'android/widget/RadioGroup.java':'''package android.widget;import android.view.*;public class RadioGroup extends LinearLayout{Listener listener;public interface Listener{void onCheckedChanged(RadioGroup v,int id);}public RadioGroup(Object c){super(c);}public void check(int id){boolean changed=false;for(View v:children){RadioButton b=(RadioButton)v;boolean next=b.getId()==id;changed|=b.isChecked()!=next;b.setChecked(next);}if(changed&&listener!=null)listener.onCheckedChanged(this,id);}public void setOnCheckedChangeListener(Listener l){listener=l;}}''',
'android/widget/AdapterView.java':'''package android.widget;import android.view.*;public class AdapterView<T> extends View{public interface OnItemSelectedListener{void onItemSelected(AdapterView<?> p,View v,int at,long id);void onNothingSelected(AdapterView<?> p);}}''',
'android/widget/Spinner.java':'''package android.widget;public class Spinner extends AdapterView<Object>{int at;OnItemSelectedListener listener;public Spinner(Object c){}public void setAdapter(Object a){}public int getSelectedItemPosition(){return at;}public void setSelection(int n){boolean changed=n!=at;at=n;if(changed)dispatch();}public void dispatch(){if(listener!=null)listener.onItemSelected(this,null,at,at);}public void setOnItemSelectedListener(OnItemSelectedListener l){listener=l;}}''',
'android/widget/ArrayAdapter.java':'''package android.widget;public class ArrayAdapter<T>{public ArrayAdapter(Object c,int resource,T[] items){}}'''
}
files=[]
for name,code in stubs.items():
 p=O/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(code,encoding='utf-8');files.append(p)
test=O/'SceneSettingsTest.java'
test.write_text(r'''package top.rongshangs.lumacurve.refactor;
import android.widget.*;import android.view.*;import java.util.*;import org.json.*;
class StatusAdvice{static class Action{String text,target;int group;Action(String t,int g,String key){text=t;group=g;target=key;}}}
class SceneCatalog{static final String[] BRIEF=SceneDescriptions.ENTER,EFFECTS=SceneDescriptions.EXIT;static class Row{String values="system values";}
 static List<Row> read(JSONObject j,long now){List<Row> rows=new ArrayList<>();for(int i=0;i<9;i++)rows.add(new Row());return rows;}static String briefState(Row r,JSONObject j,long now){return "未生效";}}
class MainActivity{
 int INK,BLUE,MUTED,navigations;boolean dirty;JSONObject runtime=new JSONObject();SceneOptions sceneOptions=new SceneOptions();StatusAdvice.Action last;final Map<String,Runnable> detailOpeners=new HashMap<>();
 LinearLayout column(){return new LinearLayout(this);}LinearLayout card(LinearLayout parent){LinearLayout c=column();parent.addView(c);return c;}int dp(int n){return n;}TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);return t;}TextView action(String s,Runnable r){return text(s,14,BLUE);}EditText input(String s){return new EditText(this);}String tr(String s){return s;}String format(double n){return Double.toString(n);}void scenesDialog(){}void drawDraftState(){}void openAdvice(StatusAdvice.Action a){navigations++;last=a;detailOpeners.get(a.target).run();}LinearLayout settingsDetails(LinearLayout p,String key){LinearLayout c=column();c.setVisibility(View.GONE);p.addView(c);detailOpeners.put(key,()->c.setVisibility(View.VISIBLE));return c;}
}
public class SceneSettingsTest{
 static int cases;static void check(boolean b){if(!b)throw new AssertionError("case "+cases);cases++;}
 static void invalid(SceneSettings s)throws Exception{try{s.commit();throw new AssertionError("invalid draft applied");}catch(IllegalArgumentException expected){cases++;}}
 public static void main(String[] args)throws Exception{
  MainActivity a=new MainActivity();SceneSettings s=new SceneSettings(a,a.column());s.addScene(a.column(),7);s.refresh();
  for(int i=0;i<9;i++){SceneSettings.Editor e=s.editors[i];check(e!=null&&e.selected()==0);check(e.conditions.getVisibility()==View.GONE);check(!e.modes[1].isEnabled()&&!e.modes[2].isEnabled());e.source.dispatch();e.cover.dispatch();check(!a.dirty&&!e.touched);a.runtime.put("scene_"+SceneOptions.IDS[i]+"_supported",true);}s.refresh();
  for(SceneSettings.Editor e:s.editors)check(e.modes[1].isEnabled()&&e.modes[2].isEnabled());
  SceneSettings.Editor e=s.editors[0];e.mode.check(e.modes[2].getId());check(a.dirty&&e.touched);check(e.conditions.getVisibility()==View.VISIBLE&&e.exitCustom.getVisibility()==View.VISIBLE);s.refresh();check(e.state.getText().toString().contains("自定义条件")&&e.state.getText().toString().contains("当前："));invalid(s);s.revealError();check(a.last.group==5&&a.last.target.equals("scene_night_driving"));
  e.lux.setChecked(true);e.enter.setText("5");e.exit.setText("0.5");s.commit();SceneOptions.Condition c=a.sceneOptions.entries[0].condition;check(c.confirmEnter==5000&&c.confirmExit==500);check(e.error.getText().length()==0);
  e.enter.setText("1.001");s.commit();check(a.sceneOptions.entries[0].condition.confirmEnter==1001);e.enter.setText("1.0011");invalid(s);e.enter.setText("5");s.commit();
  e.min.setText("100");check(e.error.getText().length()>0);String invalidValue=e.min.getText().toString();s.refresh();check(e.min.getText().toString().equals(invalidValue));invalid(s);check(a.sceneOptions.entries[0].condition.min==0);
  e.max.setText("200");s.commit();check(a.sceneOptions.entries[0].condition.min==100&&a.sceneOptions.entries[0].condition.max==200);
  for(String bad:new String[]{"","abc","-1","60.001","NaN"}){e.enter.setText(bad);invalid(s);}e.enter.setText("0");s.commit();check(a.sceneOptions.entries[0].condition.confirmEnter==0);
  e.clock.setChecked(true);e.start.setText("2300");e.end.setText("0700");s.commit();check(a.sceneOptions.entries[0].condition.start==1380);e.start.setText("2500");invalid(s);e.clock.setChecked(false);s.commit();check(!a.sceneOptions.entries[0].condition.time);
  e.enter.setText("");e.mode.check(e.modes[1].getId());s.commit();check(a.sceneOptions.entries[0].mode.equals("block"));check(e.conditions.getVisibility()==View.GONE&&e.exitCustom.getVisibility()==View.GONE);e.mode.check(e.modes[2].getId());invalid(s);e.enter.setText("1");s.commit();
  JSONObject imported=new JSONObject().put("scene_options",new JSONObject().put("policies",new JSONObject().put("night_driving",new JSONObject().put("mode","condition").put("condition",new JSONObject().put("time",true).put("confirm",7000)))));a.sceneOptions=SceneOptions.parse(imported);a.dirty=false;s.refresh();check(!e.touched&&!a.dirty);check(e.enter.getText().toString().equals("7.0")&&e.exit.getText().toString().equals("7.0"));check(e.clock.isChecked()&&!e.lux.isChecked());e.source.dispatch();e.cover.dispatch();check(!a.dirty);
  SceneSettings.Editor sun=s.editors[7];sun.mode.check(sun.modes[2].getId());invalid(s);s.revealError();check(a.last.group==2&&a.last.target.equals("scene_manual_sunlight"));sun.mode.check(sun.modes[0].getId());s.commit();
  check(s.effects(2)==s.editors[2].effectParameters);for(int i=0;i<9;i++)check(!SceneDescriptions.ENTER[i].isEmpty()&&!SceneDescriptions.EXIT[i].isEmpty());
  for(String text:new String[]{"系统识别到驾驶，且处于日落后至日出前。驾驶标签只是系统识别结果。","系统收到步行事件；后续步行事件会延长有效时间。","手指进入本机光感保护区域；区域会随旋转、折叠姿态变化。","普通距离采样已开启，且读数小于本机遮挡阈值。","出现变暗候选，且系统启用了流式距离确认。","出现变暗候选，照度位于本机 AON 检查范围，系统开始反射确认。","系统通知夜间唤醒策略生效；具体识别时间由系统决定。","使用手动亮度，已开启系统阳光屏，亮屏且未挂起；强光持续达到系统门槛。","应用进入系统游戏名单，并启用游戏触摸保护分支。","驾驶识别结束或进入白天，恢复常规自动亮度。","最后一次步行事件超过系统有效时间，恢复普通降亮确认。","手指移开并经过释放等待后，恢复接收环境照度。","距离读数恢复无遮挡后，恢复接收环境照度。","系统确认无遮挡后继续降亮；采样关闭时沿用系统处理。","确认结束或达到最长等待后，由系统决定是否继续降亮。旧反射标记不代表仍在等待。","系统通知夜间唤醒结束，恢复常规亮度目标。","照度持续低于退出门槛，或转为自动亮度、息屏、暂停阳光屏时退出。","退出游戏，或超过入场、最近触摸的保护时间后恢复降亮。","场景判定与控制","场景是系统针对驾驶、遮挡、步行等情况临时采用的亮度策略。","展开对应场景，依次查看进入条件、生效效果和退出条件。修改后统一保存并应用。","查看当前场景","夜间亮度目标","遮挡与降亮保护","运动与游戏","其他输出策略","手动阳光屏位于户外高亮。HDR、背屏和驱动保护由系统管理。","不参与亮度控制","自定义条件","跟随系统","不限遮挡","普通距离：遮挡","普通距离：无遮挡","流式距离：遮挡","流式距离：无遮挡","触摸保护中","触摸保护已解除","请输入有效的场景条件","参与方式","跟随系统 · 保留原有判断","自定义 · 系统条件＋附加条件","进入条件","系统条件成立后，还需同时满足下面选中的条件。至少选择一项。","限定时间段","开始时间（HHmm，如 2200）","结束时间（支持跨午夜）","限定环境照度","照度来源","融合照度","主光感","辅助光感","最低照度（lux）","最高照度（lux）","遮挡条件","进入确认（秒，0–60）","条件持续满足后才允许参与；这段等待不会强制进入系统场景。","生效效果","效果参数沿用系统；参与方式和附加条件可在本页调整。","退出条件","附加条件退出确认（秒，0–60）","任一附加条件持续不满足后停止参与。系统自身结束场景时立即退出，不受此等待延长。","条件数据未取得时跟随系统；不会把缺失读数当作遮挡。","当前已选择不参与，此效果不会执行。","时间请输入 HHmm","确认时间请输入 0–60 秒（最多三位小数）","照度请输入有效数值","待应用","接口未就绪","系统当前参数：","未取得"})check(UiText.translate(text,true).codePoints().noneMatch(n->n>=0x4e00&&n<=0x9fff));
  System.out.println("Inline scene settings: "+cases+" cases PASS; production form with widget doubles, Android rendering not tested");
 }
}''',encoding='utf-8')
classes=O/'classes';classes.mkdir(exist_ok=True)
subprocess.run(['javac','--release','8','-encoding','UTF-8','-cp',str(J),'-d',str(classes),*[str(p) for p in files],*[str(S/(n+'.java')) for n in ['SceneOptions','SceneDescriptions','SceneSettings','UiText']],str(test)],check=True)
subprocess.run(['java','-cp',str(classes)+os.pathsep+str(J),'top.rongshangs.lumacurve.refactor.SceneSettingsTest'],check=True)
