package top.rongshangs.lumacurve.refactor;

import android.view.*;
import android.widget.*;
import android.text.*;
import java.util.*;
import org.json.*;

/** Inline scene drafts, validated before submitting a configuration. */
final class SceneSettings {
    final MainActivity a;final Editor[] editors=new Editor[SceneOptions.IDS.length];
    SceneSettings(MainActivity a,LinearLayout parent){this.a=a;
        LinearLayout intro=a.card(parent);intro.addView(a.text("场景判定与控制",18,a.INK));intro.addView(a.text("场景是系统针对驾驶、遮挡、步行等情况临时采用的亮度策略。",13,a.MUTED));intro.addView(a.text("展开对应场景，依次查看进入条件、生效效果和退出条件。修改后统一保存并应用。",12,a.MUTED));intro.addView(a.action("查看当前场景",a::scenesDialog));
        section(parent,"夜间亮度目标",new int[]{0,6});section(parent,"遮挡与降亮保护",new int[]{2,3,4,5});section(parent,"运动与游戏",new int[]{1,8});
        LinearLayout note=a.card(parent);note.addView(a.text("其他输出策略",17,a.INK));note.addView(a.text("手动阳光屏位于户外高亮。HDR、背屏和驱动保护由系统管理。",12,a.MUTED));
    }
    void section(LinearLayout parent,String title,int[] ids){TextView label=a.text(title,14,a.MUTED);label.setPadding(a.dp(12),a.dp(10),0,a.dp(6));parent.addView(label);for(int id:ids)addScene(parent,id);}
    LinearLayout addScene(LinearLayout parent,int id){Editor e=new Editor(parent,id);editors[id]=e;return e.effectParameters;}
    LinearLayout effects(int id){return editors[id].effectParameters;}
    View find(String key){int id=key.startsWith("scene_")?SceneOptions.index(key.substring(6)):-1;return id<0||editors[id]==null?null:editors[id].anchor;}
    static String modeText(String mode){return mode.equals("block")?"不参与亮度控制":mode.equals("condition")?"自定义条件":"跟随系统";}
    static String time(int value){return String.format(Locale.ROOT,"%02d:%02d",value/60,value%60);}
    static String[] coverLabels(){return new String[]{"不限遮挡","普通距离：遮挡","普通距离：无遮挡","流式距离：遮挡","流式距离：无遮挡","触摸保护中","触摸保护已解除"};}
    void refresh(){List<SceneCatalog.Row> rows=SceneCatalog.read(a.runtime,android.os.SystemClock.elapsedRealtime());for(Editor e:editors)if(e!=null)e.refresh(rows.get(e.id));}
    void commit()throws Exception{SceneOptions.Entry[] next=a.sceneOptions.entries.clone();for(Editor e:editors)if(e!=null&&e.touched)try{next[e.id]=e.read();}catch(Exception invalid){e.error.setText(a.tr(message(invalid)));throw new IllegalArgumentException(SceneOptions.NAMES[e.id]+"："+message(invalid));}for(Editor e:editors)if(e!=null&&e.touched){a.sceneOptions.entries[e.id]=next[e.id];e.bound=next[e.id];}}
    void revealError(){for(Editor e:editors)if(e!=null&&e.touched)try{e.read();}catch(Exception invalid){a.openAdvice(new StatusAdvice.Action(SceneOptions.NAMES[e.id],e.id==7?2:5,"scene_"+SceneOptions.IDS[e.id]));return;}}
    static String message(Exception e){return e.getMessage()==null?"请输入有效的场景条件":e.getMessage();}
    void watch(EditText field,Runnable change){field.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){change.run();}public void afterTextChanged(Editable s){}});}
    Spinner choices(LinearLayout parent,String label,String[] labels,int selected){parent.addView(a.text(label,13,a.INK));Spinner s=new Spinner(a);String[] translated=new String[labels.length];for(int i=0;i<labels.length;i++)translated[i]=a.tr(labels[i]);s.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,translated));s.setSelection(selected);parent.addView(s,new LinearLayout.LayoutParams(-1,a.dp(52)));return s;}
    EditText number(LinearLayout parent,String label,String value,boolean decimal){parent.addView(a.text(label,13,a.INK));EditText input=a.input(label);input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|(decimal?android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL:0));input.setText(value);input.setMinHeight(a.dp(48));parent.addView(input,new LinearLayout.LayoutParams(-1,-2));return input;}
    Switch flag(LinearLayout parent,String label,boolean checked){Switch v=new Switch(a);v.setText(a.tr(label));v.setTextSize(14);v.setChecked(checked);v.setMinHeight(a.dp(52));parent.addView(v,new LinearLayout.LayoutParams(-1,-2));return v;}
    void heading(LinearLayout parent,String title){TextView t=a.text(title,15,a.INK);t.setPadding(0,a.dp(16),0,a.dp(6));parent.addView(t);}
    final class Editor {
        final int id;final View anchor;final LinearLayout conditions,effectParameters,times,levels,exitCustom;final TextView state,error,values,effectNotice;final RadioGroup mode;final RadioButton[] modes=new RadioButton[3];final Switch clock,lux;final Spinner source,cover;final EditText min,max,start,end,enter,exit;SceneOptions.Entry bound;boolean loading=true,touched;
        Editor(LinearLayout parent,int id){this.id=id;bound=a.sceneOptions.entries[id];LinearLayout card=a.card(parent);anchor=card;card.addView(a.text(SceneOptions.NAMES[id],17,a.INK));card.addView(a.text(SceneCatalog.BRIEF[id],12,a.MUTED));state=a.text("",12,a.MUTED);card.addView(state);LinearLayout body=a.settingsDetails(card,"scene_"+SceneOptions.IDS[id]);
            heading(body,"参与方式");mode=new RadioGroup(a);mode.setOrientation(LinearLayout.VERTICAL);body.addView(mode);String[] labels={"跟随系统 · 保留原有判断","不参与亮度控制","自定义 · 系统条件＋附加条件"};for(int i=0;i<3;i++){RadioButton button=new RadioButton(a);button.setId(View.generateViewId());button.setText(a.tr(labels[i]));button.setTextSize(13);button.setMinHeight(a.dp(48));modes[i]=button;mode.addView(button,new RadioGroup.LayoutParams(-1,-2));}
            heading(body,"进入条件");body.addView(a.text(SceneDescriptions.ENTER[id],13,a.MUTED));conditions=a.column();body.addView(conditions);conditions.addView(a.text("系统条件成立后，还需同时满足下面选中的条件。至少选择一项。",12,a.MUTED));
            clock=flag(conditions,"限定时间段",false);times=a.column();conditions.addView(times);start=number(times,"开始时间（HHmm，如 2200）","2200",false);end=number(times,"结束时间（支持跨午夜）","0700",false);
            lux=flag(conditions,"限定环境照度",false);levels=a.column();conditions.addView(levels);source=choices(levels,"照度来源",new String[]{"融合照度","主光感","辅助光感"},0);min=number(levels,"最低照度（lux）","0",true);max=number(levels,"最高照度（lux）","50",true);cover=choices(conditions,"遮挡条件",coverLabels(),0);enter=number(conditions,"进入确认（秒，0–60）","2",true);conditions.addView(a.text("条件持续满足后才允许参与；这段等待不会强制进入系统场景。",12,a.MUTED));
            heading(body,"生效效果");effectNotice=a.text("",12,a.MUTED);body.addView(effectNotice);body.addView(a.text(SceneCatalog.EFFECTS[id],13,a.MUTED));values=a.text("",12,a.MUTED);body.addView(values);effectParameters=a.column();body.addView(effectParameters);if(id!=2&&id!=7)effectParameters.addView(a.text("效果参数沿用系统；参与方式和附加条件可在本页调整。",12,a.MUTED));
            heading(body,"退出条件");body.addView(a.text(SceneDescriptions.EXIT[id],13,a.MUTED));exitCustom=a.column();body.addView(exitCustom);exit=number(exitCustom,"附加条件退出确认（秒，0–60）","2",true);exitCustom.addView(a.text("任一附加条件持续不满足后停止参与。系统自身结束场景时立即退出，不受此等待延长。",12,a.MUTED));exitCustom.addView(a.text("条件数据未取得时跟随系统；不会把缺失读数当作遮挡。",12,a.MUTED));error=a.text("",12,0xffad5426);body.addView(error);
            write(bound);mode.setOnCheckedChangeListener((g,checked)->changed());clock.setOnCheckedChangeListener((v,on)->changed());lux.setOnCheckedChangeListener((v,on)->changed());for(EditText field:new EditText[]{start,end,min,max,enter,exit})watch(field,this::changed);AdapterView.OnItemSelectedListener selected=new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int at,long item){changed();}public void onNothingSelected(AdapterView<?> p){}};source.setOnItemSelectedListener(selected);cover.setOnItemSelectedListener(selected);
        }
        int selected(){for(int i=0;i<modes.length;i++)if(modes[i].isChecked())return i;return 0;}
        void visibility(){boolean custom=selected()==2;conditions.setVisibility(custom?View.VISIBLE:View.GONE);exitCustom.setVisibility(custom?View.VISIBLE:View.GONE);effectNotice.setText(selected()==1?a.tr("当前已选择不参与，此效果不会执行。"):"");effectNotice.setVisibility(selected()==1?View.VISIBLE:View.GONE);times.setVisibility(clock.isChecked()?View.VISIBLE:View.GONE);levels.setVisibility(lux.isChecked()?View.VISIBLE:View.GONE);}
        void changed(){if(loading)return;visibility();try{SceneOptions.Entry next=read();error.setText("");if(next.json().toString().equals(bound.json().toString()))return;bound=next;a.sceneOptions.entries[id]=next;}catch(Exception invalid){error.setText(a.tr(message(invalid)));}touched=true;a.dirty=true;a.drawDraftState();}
        void write(SceneOptions.Entry e){loading=true;bound=e;SceneOptions.Condition c=e.condition;mode.check(modes[Arrays.asList("system","block","condition").indexOf(e.mode)].getId());clock.setChecked(c.time);lux.setChecked(c.lux);source.setSelection(Arrays.asList(SceneOptions.SOURCES).indexOf(c.source));cover.setSelection(Arrays.asList(SceneOptions.COVERS).indexOf(c.cover));start.setText(time(c.start).replace(":",""));end.setText(time(c.end).replace(":",""));min.setText(Double.toString(c.min));max.setText(Double.toString(c.max));enter.setText(Double.toString(c.confirmEnter/1000.0));exit.setText(Double.toString(c.confirmExit/1000.0));error.setText("");touched=false;visibility();loading=false;}
        int minute(EditText text){String raw=text.getText().toString().trim();if(!raw.matches("[0-9]{3,4}"))throw new IllegalArgumentException("时间请输入 HHmm");int n=Integer.parseInt(raw);if(n/100>23||n%100>59)throw new IllegalArgumentException("时间请输入 HHmm");return n/100*60+n%100;}
        double seconds(EditText field){try{int ms=new java.math.BigDecimal(field.getText().toString().trim()).movePointRight(3).intValueExact();if(ms<0||ms>60000)throw new ArithmeticException();return ms;}catch(NumberFormatException|ArithmeticException invalid){throw new IllegalArgumentException("确认时间请输入 0–60 秒（最多三位小数）");}}
        SceneOptions.Entry read()throws JSONException{String choice=new String[]{"system","block","condition"}[selected()];JSONObject c=bound.condition.json();if(choice.equals("condition")){c.put("time",clock.isChecked()).put("lux",lux.isChecked()).put("source",SceneOptions.SOURCES[source.getSelectedItemPosition()]).put("cover",SceneOptions.COVERS[cover.getSelectedItemPosition()]).put("confirm_enter",seconds(enter)).put("confirm_exit",seconds(exit));if(clock.isChecked())c.put("start",minute(start)).put("end",minute(end));if(lux.isChecked())try{c.put("min",Double.parseDouble(min.getText().toString())).put("max",Double.parseDouble(max.getText().toString()));}catch(NumberFormatException invalid){throw new IllegalArgumentException("照度请输入有效数值");}}return new SceneOptions.Entry(new JSONObject().put("mode",choice).put("condition",c));}
        void refresh(SceneCatalog.Row row){if(bound!=a.sceneOptions.entries[id])write(a.sceneOptions.entries[id]);boolean supported=a.runtime!=null&&a.runtime.optBoolean("scene_"+SceneOptions.IDS[id]+"_supported");for(int i=1;i<3;i++)modes[i].setEnabled(supported);state.setText(a.tr("设置：")+a.tr(modeText(new String[]{"system","block","condition"}[selected()]))+(touched?" · "+a.tr("待应用"):"")+"\n"+a.tr("当前：")+a.tr(SceneCatalog.briefState(row,a.runtime,android.os.SystemClock.elapsedRealtime()))+(supported?"":" · "+a.tr("接口未就绪")));values.setText(a.tr("系统当前参数：")+a.tr(row.values.isEmpty()?"未取得":row.values));}
    }
}
