package top.rongshangs.lumacurve.refactor;
import java.util.*;

/** System-language UI translation; technical state JSON stays untouched. */
public final class UiText {
    private static final LinkedHashMap<String,String> WORDS=new LinkedHashMap<>();
    static {
        WORDS.put("名单来自官网，联网时自动更新","From the website; refreshed when online");
        WORDS.put("暂时无法读取名单","Unable to load the list");
        WORDS.put("已同步官网感谢名单","Thank-you list synced with the website");
        WORDS.put("暂未连接官网，显示已保存的名单","Website unavailable; showing the saved list");
        WORDS.put("记得备注[昵称：想说的话]噢","Please add a note: [nickname: your message]");
        WORDS.put("将会尽快更新到感谢名单。","You will be added to the thank-you list as soon as possible.");
        WORDS.put("完全开源免费。欢迎捐赠 2.3 元支持开发。备注「昵称：想说的一句话」，总计不超过 30 个字符，将会尽快更新到感谢名单。","Free and open source. A ¥2.3 donation supports development. Add “nickname: your message” (30 characters total); you will be added to the thank-you list as soon as possible.");
        WORDS.put("自动滚动","Auto-scroll");
        WORDS.put("默认关闭。在设定照度以内增加主、辅助光感的变化确认时间。手动调节、熄屏、HDR、闲置与驾驶模式继续沿用系统。","Off by default. Extends main and assist light-change confirmation within the chosen light range. Manual changes, screen off, HDR, idle and driving modes keep system behavior.");
        WORDS.put("适用照度 5～100 lux；变亮、变暗最短确认各为 1～4 秒。保留系统更长等待；辅助光感采样窗口仅 5 秒，因此确认时间最高 4 秒。","Light range: 5–100 lux. Minimum brightening and dimming confirmation: 1–4 s each. Longer system waits remain. The assist buffer holds 5 s, so the selectable confirmation is capped at 4 s.");
        WORDS.put("暗光适用照度：","Low-light range: ");
        WORDS.put("暗光最短变亮确认：","Low-light brightening minimum: ");
        WORDS.put("暗光最短变暗确认：","Low-light dimming minimum: ");
        WORDS.put("暗光参数超出可调范围","Low-light parameters are out of range");
        WORDS.put("1/8 收集曲线、运行状态与本次系统进程日志…","1/8 Collecting curves, runtime state and Hook logs…");
        WORDS.put("2/8 收集显示、光感、唤醒和温控状态…","2/8 Collecting display, sensors, power and thermal state…");
        WORDS.put("3/8 收集显示接口、资源覆盖与近期系统记录…","3/8 Collecting display interfaces, overlays and recent system logs…");
        WORDS.put("4/8 收集固件标识、亮度资源和背光只读信息…","4/8 Collecting firmware identity, brightness resources and read-only backlight data…");
        WORDS.put("5/8 收集显示配置文件…","5/8 Collecting display configuration files…");
        WORDS.put("6/8 提取系统与小米显示框架，计算校验值…","6/8 Extracting system and Xiaomi display frameworks and checksums…");
        WORDS.put("7/8 收集旧模块诊断并再次采集显示快照…","7/8 Collecting legacy diagnostics and a second display snapshot…");
        WORDS.put("8/8 完成压缩并校验分析包…","8/8 Finishing and verifying the diagnostic archive…");
        WORDS.put("照度跳变：","Light jump: ");
        WORDS.put("系统高亮控制器的当前状态；仍由系统判断何时触发。","Current sunlight high-brightness state. Triggering remains under system control.");
        WORDS.put("阳光增强","Sunlight boost");
        WORDS.put("采样窗口不足时沿用原有等待，避免一直等不到确认。","Keep the original delay if the evidence window is too short, so confirmation cannot be stalled.");
        WORDS.put("系统会根据双侧读数与场景切换参考，不意味着两个独立亮度引擎在抢控制权。","The system switches sensor references according to readings and scenes. This does not imply two competing brightness engines.");
        WORDS.put("当前光感参考","Active sensor reference");
        WORDS.put("其他系统策略","Other system policy");
        WORDS.put("光感参考切换：","Sensor reference changed: ");
        WORDS.put("旧引擎仍在退出，尚未启用新曲线","The old engine is still exiting; the new curve is not enabled yet");
        WORDS.put("已启用","On");
        WORDS.put("实际延长确认：主光感 ","Confirmations extended: main ");
        WORDS.put(" · 辅助光感 "," · assist ");
        WORDS.put(" 秒前 · #"," s ago · #");
        WORDS.put("未启用","Off");
        WORDS.put("曲线路径切换：","Curve path changed: ");
        WORDS.put("输出路径切换：","Output strategy changed: ");
        WORDS.put("默认关闭。已确认或候选照度不超过 50 lux 时，主、辅助光感至少持续变亮 3 秒、变暗 4 秒才确认；更长的原有等待保留。手动调节、熄屏、HDR、闲置与驾驶模式不受此项影响。","Off by default. When confirmed or candidate light is up to 50 lux, both sensor paths require at least 3 s of brightening or 4 s of dimming evidence. Longer existing waits remain. Manual changes, screen off, HDR, idle and driving modes are unaffected.");
        WORDS.put("当前路径未取得可绘制曲线","No drawable curve observed for this path");
        WORDS.put("自动、临时、应用指定与系统回退是不同输出策略；回退不代表用户关闭了自动亮度。","Automatic, temporary, app override and fallback are different output strategies. Fallback does not mean you turned off automatic brightness.");
        WORDS.put("显示最近一次实际执行的映射路径，不把支持某接口当作正在使用它。","Shows the mapping path actually observed in the latest calculation, rather than assuming a supported interface is in use.");
        WORDS.put("比较同一次计算中，场景处理前后的亮度目标。","Compares targets before and after scene processing in the same calculation.");
        WORDS.put("显示系统手动保持策略是否改写目标；手动曲线节点仍可另行影响曲线。","Shows whether the system manual hold altered the target. Remembered curve points can affect the curve separately.");
        WORDS.put("系统记忆模型的状态；模型存在不等于当前曲线一定使用了它。","System memory model status. Its presence does not prove the active curve uses it.");
        WORDS.put("显示策略开关，不代表本次一定改变了亮度。","Shows the policy flag, not a claim that it changed this calculation.");
        WORDS.put("视频等 HDR 内容可改变输出亮度，与照度曲线变化分开记录。","HDR content can change output brightness. These output calls are recorded separately from curve calculations.");
        WORDS.put("仅增加照度变化的确认时间，保留原有传感器数值与系统过渡动画。","Extends light-change confirmation only; keeps original sensor readings and system transitions.");
        WORDS.put("未取得表示该阶段尚未被观察到。曲线计算与后续输出分开记录，导出分析包可查看切换详情。","Unavailable means the stage has not been observed. Calculations and later output calls are separate; export a diagnostic package for transition details.");
        WORDS.put("亮度分支：等待读取 · 点击查看","Brightness paths: waiting · Tap to view");
        WORDS.put("点击查看亮度分支","Tap to view brightness paths");
        WORDS.put("正式版","Official release");
        WORDS.put("暗光稳定接口尚未完整兼容","Low-light stability interfaces are not fully compatible");
        WORDS.put("稳定性测试版","Stability test");
        WORDS.put("亮度分支","Brightness paths");
        WORDS.put("最近曲线计算：","Last curve calculation: ");
        WORDS.put("曲线路径","Curve path");
        WORDS.put("输出路径","Output path");
        WORDS.put("标准映射曲线","Standard mapping curve");
        WORDS.put("Refactor 曲线","Refactor curve");
        WORDS.put("场景修正","Scene adjustment");
        WORDS.put("手动保持修正","Manual hold adjustment");
        WORDS.put("短期记忆模型","Short-term memory model");
        WORDS.put("夜间唤醒策略","Night wake policy");
        WORDS.put("暗光稳定","Low-light stability");
        WORDS.put("已改写目标","Target changed");
        WORDS.put("未改写目标","Target unchanged");
        WORDS.put("系统回退","System fallback");
        WORDS.put("临时亮度","Temporary brightness");
        WORDS.put("应用指定亮度","App brightness override");
        WORDS.put("曲线：","Curve: ");
        WORDS.put("输出：","Output: ");
        WORDS.put("适配 HyperOS 4 的自动亮度工具。\n\n以系统双侧感光与场景判定为基础，提供可编辑曲线、预设与手动偏好记忆。保留系统平滑过渡，也可按需调整温控和变化确认时间。","Automatic brightness for HyperOS 4.\n\nBuilt on system sensor fusion and scene detection, with editable curves, presets and manual brightness memory. Keeps smooth system transitions, with optional thermal and light-change controls.");
        WORDS.put("Root 已授权。请在 LSPosed 启用 HyperLux，勾选系统框架，然后重启手机。\n从旧测试版迁移时，请先关闭旧版的 LSPosed 开关。","Root is granted. Enable HyperLux in LSPosed, select System Framework, then restart.\nDisable the old test module’s LSPosed switch before migrating.");
        WORDS.put("请在 Root 管理器中允许 HyperLux 获得 Root 权限，再点击重新检测。\nRoot 可用后才会继续检查 LSPosed。","Allow Root access for HyperLux in your Root manager, then check again.\nLSPosed can be checked once Root is available.");
        WORDS.put("完全开源免费。欢迎捐赠 2.3 元支持开发。备注「昵称：想说的一句话」，总计不超过 30 个字符，下次更新加入感谢名单。","Free and open source. A ¥2.3 donation supports development. Add “name: a message” (30 characters total) to join the next update’s credits.");
        WORDS.put("适配 HyperOS 4 的自动亮度工具。可编辑与记忆的亮度曲线，配合系统场景感知和平滑调节。","Automatic brightness for HyperOS 4. Editable curves and manual brightness memory, with system scene sensing and smooth transitions.");
        WORDS.put("✓ Root 授权已通过\n○ 系统框架连接未建立\n请核对 LSPosed 作用域和是否重启","✓ Root granted\n○ System Hook not connected\nCheck the LSPosed scope and restart the phone");
        WORDS.put("通过 LSPosed 接入系统曲线，沿用系统光感与亮度输出。Root 用于设置与诊断。","LSPosed connects to the system curve while keeping its sensors and brightness output. Root is used for settings and diagnostics.");
        WORDS.put("变亮 0.5～10 秒，变暗 1～15 秒。小幅变亮、闲置与驾驶模式继续沿用系统策略。","Brighten: 0.5–10 s; dim: 1–15 s. Small increases, idle and driving modes retain system policy.");
        WORDS.put("默认关闭。开启后可减少显示层的温控限亮；严重过热或达到电池温度阈值时恢复系统策略。","Off by default. Reduces display-layer thermal dimming. System protection resumes during severe heat or at the battery threshold.");
        WORDS.put("变亮 0.5～10 秒，变暗 1～15 秒。闲置与驾驶模式继续沿用系统策略。","Brighten: 0.5–10 s; dim: 1–15 s. Idle and driving modes retain system policy.");
        WORDS.put("节点受系统上下限和相邻节点约束，亮度随照度不递减；最高照度端保持系统上限。","Points stay within system limits and cannot fall below their neighbors. The last point stays at the system maximum.");
        WORDS.put("关闭后不再记入新调整，已有记忆保留。记忆可能被系统重置，不保证跨重启保留。","Turning this off keeps existing memory. The system may reset it, and a reboot may clear it.");
        WORDS.put("Root 已获授权，但系统仍在运行旧版 Hook。请重启手机以加载新版本。","Root is granted, but the old Hook is still loaded. Restart the phone to load the new version.");
        WORDS.put("默认沿用系统。光线持续越过变化阈值后再调节，等待越长越不易受短暂遮挡影响。","Uses system delays by default. Longer confirmation reduces reactions to brief obstructions.");
        WORDS.put("手动亮度立即生效，也会影响附近照度的曲线。强度越低，每次记住的调整越少。","Manual changes take effect immediately and shape the curve nearby. Lower strength remembers less each time.");
        WORDS.put("尚未连接 Hook：请在 LSPosed 启用本模块，勾选系统框架并重启","Hook disconnected. Enable the module in LSPosed, select System Framework, and restart.");
        WORDS.put("请在 Root 管理器中卸载这些旧模块并重启，避免多套引擎同时调节亮度。","Uninstall these old modules in your Root manager, then restart to avoid overlapping brightness control.");
        WORDS.put("可设 38～45℃。达到阈值交回系统，冷却到设定幅度后再允许减少降亮。","Range: 38–45℃. System control resumes at the threshold; relaxation returns after cooling by the margin.");
        WORDS.put("可设 38～45℃，冷却 1℃后重新允许。硬件及其他系统限制仍生效。","Range: 38–45°C; resumes after cooling by 1°C. Hardware and other system limits still apply.");
        WORDS.put("导出到手机存储根目录，包含运行记录、设备状态、显示链路与温控信息。","Exports logs, device status, display and thermal information to the storage root.");
        WORDS.put("在相近照度范围内延续同一次记忆；暗处至少保留 5 lux 的容差。","Nearby light levels share one adjustment, with at least 5 lux tolerance in dim light.");
        WORDS.put("0.5～15 秒。仅影响系统判定的微小变亮；关闭后沿用系统时间。","0.5–15 s. Applies only to small increases identified by the system; uses system timing when disabled.");
        WORDS.put("100% 为系统基础值。范围由系统亮度上下限及相邻节点决定。","100% is the system baseline. System brightness limits and neighboring points define this range.");
        WORDS.put("关闭请求已保存，但系统尚未确认恢复；请重启，暂不恢复旧引擎","Disable request saved, but restoration is not confirmed. Restart before resuming the old engine.");
        WORDS.put("关闭请求已保存；请重启后再点停用，确认恢复并解除旧模块暂停","Disable request saved. Restart and select Disable again to confirm restoration and resume the old module.");
        WORDS.put("保留基础曲线和最近滑块位置，仅清除当前曲线的手动锚点。","Keep your base curve and last slider position. Clear only the remembered curve points.");
        WORDS.put("节点必须随照度不递减，请降低前一个节点或提高后一个节点","Brightness cannot decrease as light rises. Lower the previous point or raise the next one.");
        WORDS.put("已清除当前手动曲线锚点；系统保存的最近滑块位置保持原样","Manual points cleared; the saved slider position is unchanged");
        WORDS.put("当前已恢复系统曲线。请核对兼容状态，再重新保存并应用。","System curves have been restored. Check compatibility, then save and apply again.");
        WORDS.put("高照度端暂保持官方上限，请保持第四个参数为 100%","The last point must stay at the system maximum (100%)");
        WORDS.put("当前系统进程 · 最近 160 条 · 最新在下方","Current system session · Last 160 entries · Newest at the bottom");
        WORDS.put("已接入小米曲线。系统手动保持仍可能影响当前输出。","Curve applied. A system manual override may still affect brightness.");
        WORDS.put("曲线高度是逻辑亮度比例；屏幕亮度由系统标定换算。","Curve height is a logical ratio; the system converts it to screen brightness.");
        WORDS.put("当前为手动亮度，曲线将在开启自动亮度后参与调节。","Manual brightness is on. The curve takes effect when auto brightness is enabled.");
        WORDS.put("灰：系统基础 · 蓝：自定义 · 绿：手动记忆","Gray: system · Blue: custom · Green: learned");
        WORDS.put("QQ 交流群 314981836 · 点击复制","QQ group 314981836 · Copy");
        WORDS.put("主光感和辅助光感，经融合与场景判断产生有效照度","Main and assist sensors feed fusion and scene detection to produce effective light");
        WORDS.put("已恢复官方基础曲线，并恢复由本应用暂停的旧模块","System curve restored; the old module paused by this app has been resumed");
        WORDS.put("间隔以内的连续拖动视为一次调整，避免重复累积。","Consecutive moves within this interval count as one adjustment.");
        WORDS.put("自定义曲线已接入，官方光感和过渡动画继续运行","Custom curve connected; system sensors and transitions retained");
        WORDS.put("预设已按本机可调范围调整，保存并应用后生效","Preset adjusted to this device’s limits. Save & apply to activate it.");
        WORDS.put("请先在官方曲线 test01 中恢复原配置","Restore the original configuration in curve test01 first");
        WORDS.put("照度定位曲线，换算亮度后交由系统平滑调节。","Light selects a point on the curve. The system converts it to brightness and smooths the transition.");
        WORDS.put("已清除本次系统曲线的手动锚点，保留基础曲线","Manual points cleared; base curve retained");
        WORDS.put("此固件温控亮度接口尚未兼容，不能启用该选项","Thermal control is unsupported on this firmware; this option cannot be enabled.");
        WORDS.put("纵轴为曲线相对强度，不是屏幕亮度百分比。","Curve height is relative strength, not screen brightness percentage.");
        WORDS.put("进入设置自动读取；修改后点击保存并应用。","Settings refresh when opened. Save & apply your changes.");
        WORDS.put("此固件曲线接口尚未兼容，保留官方行为：","Curve interface unsupported; system behavior retained: ");
        WORDS.put("收集曲线、运行状态与本次系统进程日志…","Collecting curves, status and session logs…");
        WORDS.put("微小变亮确认时间应在 0.5～15 秒","Small-increase delay must be 0.5–15 s");
        WORDS.put("系统尚未确认曲线接入，已撤回本次提交","The system did not confirm the curve. Changes have been rolled back.");
        WORDS.put("拖动节点调整亮度，点击节点输入数值。","Drag a point to adjust brightness. Tap it to enter a value.");
        WORDS.put("1.0.0 · APP 测试版 03","1.0.0 · App test 03");
        WORDS.put("该预设来自其他固件，请先核对曲线节点","This preset is from another firmware. Check the curve points first.");
        WORDS.put("未取得 Root 响应，请确认授权。","No Root response. Check the permission grant.");
        WORDS.put("已应用，官方动画与传感器继续控制主屏","Applied; system sensors and animation control the main display");
        WORDS.put("系统尚未确认锚点清除，请重新读取状态","Point reset is not confirmed yet. Refresh the status.");
        WORDS.put("只影响状态显示，不改变亮度调节频率。","Only changes display refresh; brightness control is unaffected.");
        WORDS.put("LumaCurve 官方曲线测试模块","LumaCurve system-curve test module");
        WORDS.put("314981836，暗号：1691","314981836, passcode: 1691");
        WORDS.put("拖动节点调整曲线，点击节点输入数值","Drag a curve point or tap it to enter a value");
        WORDS.put("手动亮度已调整，本次不写入曲线锚点","Manual brightness changed; not remembered in the curve");
        WORDS.put("当前系统进程 · 最近 160 条","Current system process · Last 160 entries");
        WORDS.put("提交小米基础曲线并等待系统确认…","Submitting the curve and waiting for confirmation…");
        WORDS.put("曲线已选中，点击保存并应用后生效","Curve selected. Save & apply to activate it.");
        WORDS.put("拖动或点击节点 · 高照度端固定","Drag or tap a point · Last point is fixed");
        WORDS.put("包含设备与显示信息，请按需分享。","Contains device and display information. Share only as needed.");
        WORDS.put("节点强度范围是 10%～200%","Point strength must be 10%–200%");
        WORDS.put("系统曲线已连接；主屏接口核对通过","System curve connected; main display verified");
        WORDS.put("已连接小米曲线，当前沿用官方基准","Xiaomi curve connected; using system baseline");
        WORDS.put("锚点记忆强度应在 0%～100%","Memory strength must be 0%–100%");
        WORDS.put("✓ Root 与系统框架已连接\n","✓ Root and system framework connected\n");
        WORDS.put("旧引擎仍在退出，尚未启用新曲线","The old engine is still stopping. The new curve has not been enabled.");
        WORDS.put("温控恢复阈值应在 38～45℃","Battery threshold must be 38–45℃");
        WORDS.put("此固件的温控亮度接口尚未兼容","The thermal brightness interface is unsupported on this firmware");
        WORDS.put("未找到浏览器，可复制网址打开","No browser found. The address has been copied.");
        WORDS.put("曲线已应用，重新建立基础锚点","Curve applied; base points rebuilt");
        WORDS.put("设置已更新，保留当前手动锚点","Settings updated; remembered points kept");
        WORDS.put("温控亮度保持可用（仅显示层）","Reduced thermal dimming available (display layer)");
        WORDS.put("已跳过显示层温控降亮；电池 ","Display thermal dimming skipped; battery ");
        WORDS.put("此系统的确认时间接口暂未兼容","Custom light-change delays are unavailable on this firmware");
        WORDS.put("LumaCurve 旧版模块","Legacy LumaCurve module");
        WORDS.put("○ 接入异常，请查看详细读数","○ Hook error; see detailed readings");
        WORDS.put("此系统的微小变亮接口暂未兼容","Small-increase timing is unavailable on this firmware");
        WORDS.put("等待温度读数，系统温控生效","Waiting for temperature; system thermal control active");
        WORDS.put("最高照度节点固定为系统上限","The last point is fixed at the system maximum");
        WORDS.put("接入异常，已尝试恢复官方：","Hook error; system restoration attempted: ");
        WORDS.put("系统已更新，请重新应用曲线","The system was updated. Reapply the curve.");
        WORDS.put("温控冷却幅度应在 1～3℃","Cooling margin must be 1–3℃");
        WORDS.put("分析包保存到手机存储根目录","Analysis archive saves to the storage root");
        WORDS.put("当前用户与曲线配置不一致","The current user does not match the curve configuration");
        WORDS.put("HyperLux 交流群","HyperLux group");
        WORDS.put("预设名称，最多 24 字","Preset name (up to 24 characters)");
        WORDS.put("正在应用曲线和温控选项…","Applying the curve and options…");
        WORDS.put("LSPosed 尚未接入","LSPosed not connected");
        WORDS.put("○ 温控显示接口暂未兼容","○ Display thermal interface unsupported");
        WORDS.put("已恢复官方曲线与温控策略","System curve and thermal control restored");
        WORDS.put("用户已切换，恢复官方策略","User changed; system control restored");
        WORDS.put("恢复上一轮标准曲线测试…","Restoring the previous curve test…");
        WORDS.put("收集系统温控与固件信息…","Collecting thermal and firmware information…");
        WORDS.put("○ 当前使用系统基础曲线","○ Using the system base curve");
        WORDS.put("尚未连接兼容的系统曲线","No compatible system curve connected");
        WORDS.put("逻辑亮度边界类型已变化","The logical brightness boundary type has changed");
        WORDS.put("载入后点击保存并应用。","After loading, select Save & apply.");
        WORDS.put(" lux · 节点强度"," lux · Point strength");
        WORDS.put("温度较高，系统温控生效","Temperature limit reached; system control active");
        WORDS.put("相邻节点限制了可调范围","Neighboring points limit this range");
        WORDS.put("已交回官方温控亮度策略","System thermal control restored");
        WORDS.put("本应用暂只支持主用户","Only the main user is supported");
        WORDS.put("需要 Root 权限","Root permission required");
        WORDS.put("连接系统后再保存预设","Connect to the system before saving a preset");
        WORDS.put("需要 Root 授权","Root permission required");
        WORDS.put("✓ 主屏曲线接口兼容","✓ Main-display curve supported");
        WORDS.put("✓ 自定义曲线已应用","✓ Custom curve active");
        WORDS.put("○ 当前使用官方基准","○ System baseline active");
        WORDS.put("✓ 温控显示接口兼容","✓ Display thermal interface supported");
        WORDS.put("已连接 · 官方曲线","Connected · System curve");
        WORDS.put("查看仓库了解更新内容","See the repository for release details");
        WORDS.put("确认时间超出可调范围","Light-change delay is outside the allowed range");
        WORDS.put("记忆分组参数超出范围","Memory grouping settings are outside the allowed range");
        WORDS.put("○ 温控接口暂未兼容","○ Thermal interface unavailable");
        WORDS.put("正在清除手动记忆…","Clearing brightness memory…");
        WORDS.put("融合滤波与场景判定","Fusion, filtering & scene detection");
        WORDS.put("连接后显示节点范围","Connect to see point limits");
        WORDS.put("手动偏好：等待读取","Memory: waiting for data");
        WORDS.put("正在等待系统状态…","Waiting for system status…");
        WORDS.put("入群暗号：1691","Passcode: 1691");
        WORDS.put("预设已保存到本机：","Preset saved: ");
        WORDS.put("请输入范围内的数值","Enter a value within the range");
        WORDS.put("正在恢复官方策略…","Restoring system control…");
        WORDS.put("减少温控降亮已启用","Reduced thermal dimming enabled");
        WORDS.put("✓ 系统框架已连接","✓ System Hook connected");
        WORDS.put("官方手动锚点更新：","Manual point updated: ");
        WORDS.put("暂停旧版亮度引擎…","Pausing the old brightness engine…");
        WORDS.put("收集系统显示链路…","Collecting display information…");
        WORDS.put("另一项操作还在执行","Another operation is still running");
        WORDS.put("自定义变化确认时间","Custom light-change delays");
        WORDS.put("当前没有新应用版本","No new app release available");
        WORDS.put("请卸载旧版亮度模块","Remove old brightness modules");
        WORDS.put("自定义微小变亮确认","Custom small-increase delay");
        WORDS.put("关闭请求保存失败","Could not save the disable request");
        WORDS.put("状态目录创建失败","Could not create the status directory");
        WORDS.put("记住我的手动调整","Remember manual adjustments");
        WORDS.put("等待读取手动锚点","Waiting for remembered points");
        WORDS.put("清除当前手动记忆","Clear current memory");
        WORDS.put("已复制群号与暗号","Group number and passcode copied");
        WORDS.put("还没有自定义预设","No custom presets yet");
        WORDS.put("尚未连接系统曲线","System curve not connected");
        WORDS.put("正在导出分析包…","Exporting analysis…");
        WORDS.put("系统接口尚未兼容","System interface unsupported");
        WORDS.put("系统处于手动亮度","Manual brightness is on");
        WORDS.put("使用系统基础曲线","Using the system curve");
        WORDS.put("该固件接口未兼容","Unsupported on this firmware");
        WORDS.put("当前没有手动锚点","No manual point yet");
        WORDS.put("状态格式不兼容：","Unsupported status format: ");
        WORDS.put(" · 变亮 > "," · Brighten above ");
        WORDS.put("需要四个曲线参数","Four curve parameters required");
        WORDS.put("记忆照度范围：±","Memory light range: ±");
        WORDS.put("自动检查应用更新","Automatic app update checks");
        WORDS.put("暂时无法检查更新","Unable to check for updates");
        WORDS.put("系统确认时间无效","Invalid system light-change delay");
        WORDS.put("手动锚点输入无效","Invalid manual brightness point");
        WORDS.put("✓ 温控接口兼容","✓ Thermal interface compatible");
        WORDS.put("旧预设文件过大","The old preset file is too large");
        WORDS.put("配置格式不兼容","Unsupported configuration format");
        WORDS.put("照度与亮度曲线","Light & brightness curve");
        WORDS.put("清除手动记忆？","Clear brightness memory?");
        WORDS.put("电池温度阈值：","Battery threshold: ");
        WORDS.put("温控：等待读取","Thermal: waiting for data");
        WORDS.put(" · 尚未保存"," · Unsaved");
        WORDS.put(" · 系统速度"," · System speed");
        WORDS.put(" · 缓慢记忆"," · Gentler memory");
        WORDS.put("请填写预设名称","Enter a preset name");
        WORDS.put("请输入有效数字","Enter a valid number");
        WORDS.put("自动亮度已接入","Auto brightness connected");
        WORDS.put("已交回系统控制","System control restored");
        WORDS.put("；系统热状态 ","; Thermal status: ");
        WORDS.put("系统锚点位于 ","Remembered point at ");
        WORDS.put("手动记忆节点：","Remembered points: ");
        WORDS.put("连接后读取曲线","Connect to read the curve");
        WORDS.put("% · 可调 ","% · Range ");
        WORDS.put("曲线坐标不兼容","Unsupported curve coordinates");
        WORDS.put("该节点不可编辑","This point cannot be edited");
        WORDS.put("连续调节间隔：","Gesture grouping interval: ");
        WORDS.put("状态刷新间隔：","Status refresh interval: ");
        WORDS.put("正在检查更新…","Checking for updates…");
        WORDS.put("暗号：1691","Join code: 1691");
        WORDS.put("微小变亮确认：","Small-increase delay: ");
        WORDS.put("命令输出过长","Command output is too long");
        WORDS.put("配置提交失败","Could not submit the configuration");
        WORDS.put("状态写入失败","Could not publish status");
        WORDS.put("配置标识无效","Invalid configuration identifier");
        WORDS.put("等待系统连接","Waiting for the system");
        WORDS.put("当前亮度曲线","Current brightness curve");
        WORDS.put("当前屏幕亮度","Current screen brightness");
        WORDS.put("曲线计算亮度","Calculated brightness");
        WORDS.put("手动偏好记忆","Brightness memory");
        WORDS.put("减少温控降亮","Reduce thermal dimming");
        WORDS.put("最近运行记录","Recent activity");
        WORDS.put("保存曲线预设","Save curve preset");
        WORDS.put("我的曲线预设","My curve presets");
        WORDS.put("编辑曲线节点","Edit curve point");
        WORDS.put("分析包已导出","Analysis exported");
        WORDS.put("系统温控生效","System thermal control");
        WORDS.put("尚无运行记录","No activity yet");
        WORDS.put("等待变化阈值","Waiting for change thresholds");
        WORDS.put("曲线节点无效","Invalid curve point");
        WORDS.put("曲线参数无效","Invalid curve parameters");
        WORDS.put("，记忆强度 ",", memory strength ");
        WORDS.put("完成分析包…","Finishing the analysis archive…");
        WORDS.put("发现新版本 ","New version: ");
        WORDS.put("有新版本可用","Update available");
        WORDS.put("QQ 交流群","QQ community");
        WORDS.put(" · 已停用"," · Disabled");
        WORDS.put(" · 待更新"," · Update pending");
        WORDS.put(" · 已安装"," · Installed");
        WORDS.put("操作失败：","Operation failed: ");
        WORDS.put("操作超时：","Operation timed out: ");
        WORDS.put("保存并应用","Save & apply");
        WORDS.put("停用并恢复","Disable & restore");
        WORDS.put("保存为预设","Save preset");
        WORDS.put("记忆强度 ","Memory strength ");
        WORDS.put("运行与兼容","Connection & compatibility");
        WORDS.put("导出分析包","Export analysis");
        WORDS.put("已删除预设","Preset deleted");
        WORDS.put("可调范围：","Available range: ");
        WORDS.put("输入百分比","Enter a percentage");
        WORDS.put("手动偏好：","Memory: ");
        WORDS.put("变暗 < ","Dim below ");
        WORDS.put("冷却幅度：","Cooling margin: ");
        WORDS.put("变亮确认：","Brightening delay: ");
        WORDS.put("变暗确认：","Dimming delay: ");
        WORDS.put("系统已更新","System updated");
        WORDS.put("变亮 > ","Brighten above ");
        WORDS.put("已复制群号","Group ID copied");
        WORDS.put("接口检查","Interface check");
        WORDS.put("参数过长","Parameters are too long");
        WORDS.put("未知操作","Unknown operation");
        WORDS.put("请求过长","Request is too long");
        WORDS.put("配置过长","Configuration is too long");
        WORDS.put("辅助光感","Assist light sensor");
        WORDS.put("详细读数","Detailed readings");
        WORDS.put("引擎控制","Engine");
        WORDS.put("系统默认","System");
        WORDS.put("我的预设","My presets");
        WORDS.put("（建议）"," (recommended)");
        WORDS.put("尚无记录","No entries yet");
        WORDS.put("开源协议","License");
        WORDS.put("作者博客","Blog");
        WORDS.put("酷安主页","Coolapk");
        WORDS.put("感谢名单","Thanks");
        WORDS.put("重新检测","Check again");
        WORDS.put("已导出：","Exported: ");
        WORDS.put("操作完成","Done");
        WORDS.put("连接中断","Disconnected");
        WORDS.put("等待连接","Waiting for connection");
        WORDS.put("接入异常","Hook error");
        WORDS.put("官方基准","System baseline");
        WORDS.put("等待计算","Waiting for calculation");
        WORDS.put("等待输出","Waiting for output");
        WORDS.put("暂无读数","No reading");
        WORDS.put("未启用：","Not enabled: ");
        WORDS.put("场景响应","Scene response");
        WORDS.put("检查更新","Check updates");
        WORDS.put("下载更新","Download update");
        WORDS.put("变暗 —","Dim —");
        WORDS.put("变亮 —","Brighten —");
        WORDS.put("复制群号","Copy group ID");
        WORDS.put("连接中","Connecting");
        WORDS.put("主光感","Main light sensor");
        WORDS.put("支付宝","Alipay");
        WORDS.put("知道了","Got it");
        WORDS.put("未连接","Not connected");
        WORDS.put("不兼容","Unsupported");
        WORDS.put("运行中","Active");
        WORDS.put("温控：","Thermal: ");
        WORDS.put("电池 ","Battery ");
        WORDS.put("无读数","No reading");
        WORDS.put("系统：","System: ");
        WORDS.put("构建：","Build: ");
        WORDS.put("版本 ","Version ");
        WORDS.put("正式版","Stable release");
        WORDS.put("温控","Thermal");
        WORDS.put("柔和","Soft");
        WORDS.put("稍亮","Brighter");
        WORDS.put("刷新","Refresh");
        WORDS.put("官网","Website");
        WORDS.put("微信","WeChat");
        WORDS.put("打赏","Support");
        WORDS.put("状态","Status");
        WORDS.put("设置","Settings");
        WORDS.put("日志","Logs");
        WORDS.put("关于","About");
        WORDS.put("取消","Cancel");
        WORDS.put("清除","Clear");
        WORDS.put("稍后","Later");
        WORDS.put("保存","Save");
        WORDS.put("删除","Delete");
        WORDS.put("载入","Load");
        WORDS.put("关闭","Close");
        WORDS.put("网址","Web address");
        WORDS.put("确定","Confirm");
        WORDS.put(" 个"," points");
        WORDS.put("正常","Normal");
        WORDS.put("轻微","Light");
        WORDS.put("中等","Moderate");
        WORDS.put("严重","Severe");
        WORDS.put("危急","Critical");
        WORDS.put("紧急","Emergency");
        WORDS.put("关机","Shutdown");
        WORDS.put("未知","Unknown");
        WORDS.put(" 秒"," s");
        WORDS.put("界面","Interface");
        WORDS.put("未取得","Unavailable");
        WORDS.put("自动亮度","Automatic brightness");
        WORDS.put("息屏显示","Always-on display");
        WORDS.put("熄屏","Screen off");
        WORDS.put("HDR 场景进入，输出可能增强","HDR scene entered; output may be boosted");
        WORDS.put("HDR 场景退出，输出恢复常规策略","HDR scene ended; output returned to normal policy");
        WORDS.put("开始改写目标","Target adjustment started");
        WORDS.put("停止改写目标","Target adjustment stopped");
    }
    public static String translate(String text,boolean english){
        if(text==null||!english)return text;
        String exact=WORDS.get(text);if(exact!=null)return exact;
        for(Map.Entry<String,String> item:WORDS.entrySet())text=text.replace(item.getKey(),item.getValue());
        return text;
    }
}
