package top.rongshangs.lumacurve.refactor;
import java.util.*;

/** System-language UI translation; technical state JSON stays untouched. */
public final class UiText {
    private static final LinkedHashMap<String,String> WORDS=new LinkedHashMap<>();
    private static final List<Map.Entry<String,String>> PHRASES;
    static {
        WORDS.put("不记忆将会导致在开启自动亮度时，您将无法手动调整屏幕亮度","With memory disabled, you cannot manually adjust screen brightness while automatic brightness is on.");
        WORDS.put("灰线：系统默认 · 蓝线：基础曲线\n拖动蓝色节点，或点击输入数值；保存并应用后生效。","Gray: system default · Blue: baseline\nDrag a blue point or tap to enter a value. Save and apply to activate.");
        WORDS.put("实际生效曲线会受到手动记忆影响，可在「手动记忆」页查看。","Manual memory affects the effective curve. View it on the Manual memory page.");
        WORDS.put("蓝线：已应用基础曲线 · 浅绿线：记忆后的实际曲线\n浅绿色实点：当前记忆 · 空心点：已保存，恢复后才生效","Blue: applied baseline · Light green: effective curve with memory\nSolid light green: live memory · Hollow: saved, effective once restored");
        WORDS.put("曲线表示亮度目标，最终屏幕亮度仍受温控和场景影响。","The curve represents a brightness target; thermal and scene controls still affect screen brightness.");
        WORDS.put("蓝色基础曲线与浅绿色实际曲线","Blue baseline and light green effective curve");

        WORDS.put("基础曲线","Baseline curve");
        WORDS.put("曲线数据未就绪","Curve data unavailable");

        WORDS.put("强光优先：提高目标并开放高亮范围；支持时放宽画面灰阶限亮，保留系统过渡和温控保护。保存后生效。","Outdoor maximum raises the target and opens the high brightness range. Where supported, it relaxes grayscale limits while keeping system transitions and thermal protection. Save to apply.");
        WORDS.put("强光下放宽画面限亮","Relax content brightness limits in strong light");
        WORDS.put("实验选项：仅持续强光、自动亮度下放宽灰阶限亮，最高不超过本机映射范围。温控、低电量、HBM 预算仍有效；HDR 与特殊场景沿用系统。可能增加发热与耗电，默认关闭。","Experimental: relaxes grayscale caps only in sustained strong light with automatic brightness, within the device mapping range. Thermal, low battery and HBM budgets remain; HDR and special scenes use system limits. May increase heat and power use. Off by default.");
        WORDS.put("此固件的画面限亮接口尚未兼容","Content brightness limit controls are not supported on this firmware");
        WORDS.put("请先开放高亮范围，再放宽画面限亮","Open the high brightness range before relaxing content limits");
        WORDS.put("本机使用 HBM 控制器","This device uses an HBM controller");
        WORDS.put("画面限亮放宽次数","Content limit relaxations");

        WORDS.put("此设备的手动记忆恢复接口尚未兼容","Manual memory restoration is not supported on this device");
        WORDS.put("记忆保留期限应为 1～90 天","Memory retention must be 1–90 days");
        WORDS.put("持久化节点上限应为自动或 1～7 个","Saved anchor limit must be Automatic or 1–7");
        WORDS.put("记忆持久化开关无效","Invalid persistent memory switch");
        WORDS.put("记忆保留期限必须为整数天","Memory retention must be whole days");
        WORDS.put("持久化节点上限无效","Invalid saved anchor limit");
        WORDS.put("已清除当前与已保存的手动记忆，保留基础曲线","Cleared live and saved manual memory, keeping the baseline");
        WORDS.put("已清除当前与已保存的手动记忆；系统保存的最近滑块位置保持原样","Live and saved manual anchors cleared; the system slider preference is retained");
        WORDS.put("持久化节点上限已按本机能力调整","Saved anchor limit adjusted to this device");
        WORDS.put("等待确认手动记忆恢复条件","Waiting for manual memory restoration conditions");
        WORDS.put("跨重启保留手动记忆","Keep manual memory across restarts");
        WORDS.put("自动按本机接口保存实际手动节点，也可限制保留数量。这里只控制保存与恢复，系统运行中的节点仍由系统管理。","Automatically saves actual manual anchors supported by this device. You can limit saved anchors; live anchors remain managed by the system.");
        WORDS.put("跨重启、锁屏后通过系统接口恢复。修改基础曲线、切换用户或系统更新后，旧记忆不会混用；关闭后保留已保存数据，但停止保存和恢复。","Restores through system APIs after restart or screen off. Old memory is not reused after a baseline edit, user switch or firmware update. Turning this off keeps stored data but stops saving and restoring.");
        WORDS.put("清除当前曲线与已保存的手动节点，保留基础曲线。此操作不会在下次重启时重复执行。","Clears live and stored manual anchors, keeping the baseline. This action will not run again on the next restart.");
        WORDS.put("清除手动记忆","Clear manual memory");
        WORDS.put("记忆保留期限：","Keep memory for: ");
        WORDS.put("持久化节点上限：","Saved anchor limit: ");
        WORDS.put("自动 · 本机最多 ","Automatic · device supports up to ");
        WORDS.put(" 个 · 本机最多 "," anchors · device supports up to ");
        WORDS.put("当前手动节点：","Live manual anchors: ");
        WORDS.put(" 个 · 已保存 "," anchors · saved ");
        WORDS.put("尚无已保存的手动记忆","No manual memory saved");
        WORDS.put("手动记忆待保存","Saving manual memory…");
        WORDS.put("手动记忆已保存","Manual memory saved");
        WORDS.put("手动记忆已恢复","Manual memory restored");
        WORDS.put("手动记忆已清除","Manual memory cleared");
        WORDS.put("记忆持久化已关闭","Persistent memory is off");
        WORDS.put("无匹配且未过期的手动记忆","No matching, unexpired manual memory");
        WORDS.put("手动记忆保存失败","Could not save manual memory");
        WORDS.put("手动记忆恢复未完成","Could not restore manual memory");
        WORDS.put("未保存的设置无法恢复，请重新检查","Could not restore unsaved settings. Please review them.");
        WORDS.put(" 天"," days");
        WORDS.put("曲线适配测试版","Curve compatibility test");
        WORDS.put("默认基准取自本设备的系统曲线。编辑保留原曲线形状与完整节点；亮度须随照度不递减，高照度末端保持原始值。","The baseline comes from this device. Edits preserve its shape and nodes; brightness must not decrease with light, and the final point stays unchanged.");
        WORDS.put("最高照度节点保持设备原始值","The final point keeps this device\'s original value");
        WORDS.put("传统系统曲线 · 设备本地基准","Physical mapping · this device's baseline");
        WORDS.put("Refactor 曲线 · 设备本地基准","Refactor · this device's baseline");
        WORDS.put("接入后端","Curve backend");
        WORDS.put("传统系统曲线","Physical mapping curve");
        WORDS.put("设备曲线尚未连接","Device curve not connected");
        WORDS.put("设备曲线尚未就绪","Device curve not ready");
        WORDS.put("LSPosed 已加载","LSPosed loaded");
        WORDS.put("等待读取设备本地曲线；如持续未连接，请导出分析包。","Waiting for this device's baseline. If it remains unavailable, export an analysis package.");
        WORDS.put("根据系统正在使用的控制器读取设备本地曲线，保留传感器处理和亮度动画。","Reads the device baseline from the active system controller, preserving sensor processing and brightness animation.");
        WORDS.put("触摸遮挡保护","Touch-cover protection");
        WORDS.put("触摸释放等待","Wait after touch release");
        WORDS.put(" · 触摸保护 "," · touch protection ");
        WORDS.put("系统检测到手指仍在遮挡区域时始终保留保护。这里只调整手指移开后的等待，可设 0～5 秒；0 秒仅取消移开后的附加等待，不关闭遮挡检测。","Protection remains while the system detects a finger in the cover area. Sets the wait after release to 0–5 s; 0 removes only the extra wait, not cover detection.");
        WORDS.put("新增等待受采样窗口限制；主光感最近实际确认时间显示在下方，系统更长等待仍保留。","Added waits are limited by retained sensor history. Recent main confirmation is shown below; longer OEM waits remain.");
        WORDS.put("变亮 0.5～10 秒，变暗 1～15 秒；实际等待受本机采样窗口限制。熄屏、HDR、闲置与驾驶沿用系统策略。","Brightening 0.5–10 s and dimming 1–15 s, limited by this device's history window. Screen off, HDR, idle and driving keep system behavior.");
        WORDS.put("最近主光感基础确认：亮 ","Recent main base confirmation: brighter ");
        WORDS.put(" · 暗 "," · darker ");
        WORDS.put("触摸释放等待须为整数秒","Touch release wait must be whole seconds");
        WORDS.put("HBM 控制器","HBM controller");WORDS.put("HBM 时间条件","HBM time condition");WORDS.put("HBM 照度条件","HBM light condition");WORDS.put("HBM 省电限制","HBM power saving block");WORDS.put("HDR 图层","HDR layer");WORDS.put("杜比显示","Dolby display");WORDS.put("距离遮挡","Proximity obstruction");
        WORDS.put("高级参数超出范围","Advanced parameter out of range");WORDS.put("高级开关必须是布尔值","Advanced toggles must be boolean");WORDS.put("高级参数必须是数值","Advanced parameters must be numeric");WORDS.put("此系统暂不支持：","Unsupported by this system: ");
        WORDS.put("变化阈值与辅助确认","Thresholds and assist confirmation");
        WORDS.put("变化阈值","Change thresholds");
        WORDS.put("辅助光感确认","Assist confirmation");
        WORDS.put("过渡动画","Transitions");
        WORDS.put("手动模式阳光屏","Manual sunlight mode");
        WORDS.put("自定义","Customize");
        WORDS.put("此系统接口暂未兼容","Interface unavailable on this system");
        WORDS.put("展开参数","Show parameters");
        WORDS.put("收起参数","Hide parameters");
        WORDS.put("变亮阈值倍率","Brightening threshold multiplier");
        WORDS.put("变暗阈值倍率","Dimming threshold multiplier");
        WORDS.put("微小变亮阈值倍率","Small-brightening threshold multiplier");
        WORDS.put("最小变亮照度差","Minimum brightening difference");
        WORDS.put("最小变暗照度差","Minimum dimming difference");
        WORDS.put("自定义阈值照度上限","Threshold tuning light limit");
        WORDS.put("辅助变亮确认","Assist brightening confirmation");
        WORDS.put("辅助变暗确认","Assist dimming confirmation");
        WORDS.put("辅助微小变亮确认","Assist small-brightening confirmation");
        WORDS.put("变亮时长倍率","Brightening duration multiplier");
        WORDS.put("变暗时长倍率","Dimming duration multiplier");
        WORDS.put("阳光屏进入确认","Sunlight entry confirmation");
        WORDS.put("阳光屏退出确认","Sunlight exit confirmation");
        WORDS.put("默认沿用系统。倍率越大，需要更明显的照度变化才调节；最低照度差可过滤暗处的小波动。只在选定照度以内生效，高亮度、HDR 与驾驶场景保留系统阈值。","Uses system defaults until enabled. Larger multipliers require a stronger light change. Minimum differences filter small fluctuations. Applies within the chosen light range; high brightness, HDR and driving keep system behavior.");
        WORDS.put("辅助光感独立确认，避免背面遮挡影响持续过久。三种等待各为 0.5～4 秒，受系统 5 秒历史窗口约束；暗光稳定开启时取更长等待。","The assist sensor confirms changes independently. Each wait is 0.5–4 s within the system's 5 s history window. Low-light stability keeps the longer wait.");
        WORDS.put("保留系统感知亮度过渡，只调整时长。倍率越大越慢；变亮、变暗分别设置。仅自动亮度正常场景生效，已有过渡不重启。","Keeps the system perceptual transition and adjusts duration. Larger multipliers are slower. Brightening and dimming are separate. Applies to normal automatic brightness; existing transitions are not restarted.");
        WORDS.put("这里只调整系统手动模式阳光屏的进入、退出确认，不是自动亮度 HBM 的冷却时间。仍需要系统开启阳光屏并满足照度与亮度条件，不强制开启增强。","Adjusts entry and exit confirmation for Xiaomi's manual sunlight mode, not automatic HBM cooldown. The system sunlight setting and brightness/light conditions still apply; boosting is never forced.");
        WORDS.put("等待读取高级参数兼容状态","Waiting for advanced capabilities");
        WORDS.put("实际改写次数：阈值 ","Changes applied: thresholds ");
        WORDS.put(" · 辅助确认 "," · assist ");
        WORDS.put(" · 动画 "," · transition ");
        WORDS.put(" · 阳光屏 "," · sunlight ");
        WORDS.put("确认时间受采样窗口限制：","Confirmation limited by history window: ");
        WORDS.put(" 次"," times");
        WORDS.put("系统场景与增强条件","System scenes and boost conditions");
        WORDS.put("高级选项默认关闭；次数为本次系统进程累计，不代表当前每一帧都在调整。","Advanced options are off by default. Counts cover this system process and do not imply changes on every frame.");
        WORDS.put("只读显示。未出现的字段表示未取得，并非关闭；系统仍负责口袋、反射、驾驶、HDR 和高亮度保护。","Read-only observations. Missing fields mean unavailable. The system still handles pocket, reflection, driving, HDR and high-brightness protection.");
        WORDS.put("系统状态未及时刷新","System status has not refreshed yet");
        WORDS.put("参数研究测试版","Parameter research test build");
        WORDS.put("手动阳光屏","Manual sunlight mode");
        WORDS.put("阳光屏传感器","Sunlight sensor");
        WORDS.put("夜间唤醒","Night wake");
        WORDS.put("夜间驾驶","Night driving");
        WORDS.put("反射判定","Reflective scene");
        WORDS.put("运动延迟","Motion delay");
        WORDS.put("辅助重置等待","Assist reset pending");
        WORDS.put("已触发","Active");
        WORDS.put("未触发","Inactive");
        WORDS.put("主光感历史窗口","Main sensor history");
        WORDS.put("运动附加等待","Extra motion wait");
        WORDS.put("HBM 最低照度","HBM light threshold");
        WORDS.put("HBM 时间窗口","HBM time window");
        WORDS.put("HBM 时间预算","HBM time budget");
        WORDS.put("名单来自官网，联网时自动更新","From the website; refreshed when online");
        WORDS.put("暂时无法读取名单","Unable to load the list");
        WORDS.put("已同步官网感谢名单","Thank-you list synced with the website");
        WORDS.put("暂未连接官网，显示已保存的名单","Website unavailable; showing the saved list");
        WORDS.put("记得备注[昵称：想说的话]噢","Please add a note: [nickname: your message]");
        WORDS.put("将会尽快更新到感谢名单。","You will be added to the thank-you list as soon as possible.");
        WORDS.put("完全开源免费。欢迎捐赠 2.3 元支持开发。备注「昵称：想说的一句话」，总计不超过 30 个字符，将会尽快更新到感谢名单。","Free and open source. A ¥2.3 donation supports development. Add “nickname: your message” (30 characters total); you will be added to the thank-you list as soon as possible.");
        WORDS.put("自动滚动","Auto-scroll");
        WORDS.put("默认关闭。在设定照度以内增加主、辅助光感的变化确认时间。手动调节、熄屏、HDR、闲置与驾驶模式继续沿用系统。","Off by default. Extends main and assist light-change confirmation within the chosen light range. Manual changes, screen off, HDR, idle and driving modes keep system behavior.");
        WORDS.put("适用照度 5～100 lux；变亮、变暗最短确认各为 1～4 秒。保留系统更长等待；辅助光感采样窗口仅 5 秒，因此确认时间最高 4 秒。","Light range: 5–100 lux. Minimum brightening and dimming confirmation: 1–4 s each. Longer system waits remain. The assist buffer holds 5 s, so the selectable confirmation is capped at 4 s.");
        WORDS.put("暗光适用照度：","Low-light range: ");
        WORDS.put("暗光最短变亮确认：","Low-light brightening minimum: ");
        WORDS.put("暗光最短变暗确认：","Low-light dimming minimum: ");
        WORDS.put("暗光参数超出可调范围","Low-light parameters are out of range");
        WORDS.put("1/8 收集曲线、运行状态与本次系统进程日志…","1/8 Collecting curves, runtime state and Hook logs…");
        WORDS.put("2/8 收集显示、光感、唤醒和温控状态…","2/8 Collecting display, sensors, power and thermal state…");
        WORDS.put("3/8 收集显示接口、资源覆盖与近期系统记录…","3/8 Collecting display interfaces, overlays and recent system logs…");
        WORDS.put("4/8 收集固件标识、亮度资源和背光只读信息…","4/8 Collecting firmware identity, brightness resources and read-only backlight data…");
        WORDS.put("5/8 收集显示配置文件…","5/8 Collecting display configuration files…");
        WORDS.put("6/8 提取系统与小米显示框架，计算校验值…","6/8 Extracting system and Xiaomi display frameworks and checksums…");
        WORDS.put("7/8 收集旧模块诊断并再次采集显示快照…","7/8 Collecting legacy diagnostics and a second display snapshot…");
        WORDS.put("8/8 完成压缩并校验分析包…","8/8 Finishing and verifying the diagnostic archive…");
        WORDS.put("照度跳变：","Light jump: ");
        WORDS.put("系统高亮控制器的当前状态；仍由系统判断何时触发。","Current sunlight high-brightness state. Triggering remains under system control.");
        WORDS.put("阳光增强","Sunlight boost");
        WORDS.put("采样窗口不足时沿用原有等待，避免一直等不到确认。","Keep the original delay if the evidence window is too short, so confirmation cannot be stalled.");
        WORDS.put("系统会根据双侧读数与场景切换参考，不意味着两个独立亮度引擎在抢控制权。","The system switches sensor references according to readings and scenes. This does not imply two competing brightness engines.");
        WORDS.put("当前光感参考","Active sensor reference");
        WORDS.put("其他系统策略","Other system policy");
        WORDS.put("光感参考切换：","Sensor reference changed: ");
        WORDS.put("旧引擎仍在退出，尚未启用新曲线","The old engine is still exiting; the new curve is not enabled yet");
        WORDS.put("已启用","On");
        WORDS.put("实际延长确认：主光感 ","Confirmations extended: main ");
        WORDS.put(" · 辅助光感 "," · assist ");
        WORDS.put(" 秒前 · #"," s ago · #");
        WORDS.put("未启用","Off");
        WORDS.put("曲线路径切换：","Curve path changed: ");
        WORDS.put("输出路径切换：","Output strategy changed: ");
        WORDS.put("默认关闭。已确认或候选照度不超过 50 lux 时，主、辅助光感至少持续变亮 3 秒、变暗 4 秒才确认；更长的原有等待保留。手动调节、熄屏、HDR、闲置与驾驶模式不受此项影响。","Off by default. When confirmed or candidate light is up to 50 lux, both sensor paths require at least 3 s of brightening or 4 s of dimming evidence. Longer existing waits remain. Manual changes, screen off, HDR, idle and driving modes are unaffected.");
        WORDS.put("当前路径未取得可绘制曲线","No drawable curve observed for this path");
        WORDS.put("自动、临时、应用指定与系统回退是不同输出策略；回退不代表用户关闭了自动亮度。","Automatic, temporary, app override and fallback are different output strategies. Fallback does not mean you turned off automatic brightness.");
        WORDS.put("显示最近一次实际执行的映射路径，不把支持某接口当作正在使用它。","Shows the mapping path actually observed in the latest calculation, rather than assuming a supported interface is in use.");
        WORDS.put("比较同一次计算中，场景处理前后的亮度目标。","Compares targets before and after scene processing in the same calculation.");
        WORDS.put("显示系统手动保持策略是否改写目标；手动曲线节点仍可另行影响曲线。","Shows whether the system manual hold altered the target. Remembered curve points can affect the curve separately.");
        WORDS.put("系统记忆模型的状态；模型存在不等于当前曲线一定使用了它。","System memory model status. Its presence does not prove the active curve uses it.");
        WORDS.put("显示策略开关，不代表本次一定改变了亮度。","Shows the policy flag, not a claim that it changed this calculation.");
        WORDS.put("视频等 HDR 内容可改变输出亮度，与照度曲线变化分开记录。","HDR content can change output brightness. These output calls are recorded separately from curve calculations.");
        WORDS.put("仅增加照度变化的确认时间，保留原有传感器数值与系统过渡动画。","Extends light-change confirmation only; keeps original sensor readings and system transitions.");
        WORDS.put("未取得表示该阶段尚未被观察到。曲线计算与后续输出分开记录，导出分析包可查看切换详情。","Unavailable means the stage has not been observed. Calculations and later output calls are separate; export a diagnostic package for transition details.");
        WORDS.put("亮度分支：等待读取 · 点击查看","Brightness paths: waiting · Tap to view");
        WORDS.put("点击查看亮度分支","Tap to view brightness paths");
        WORDS.put("正式版","Official release");
        WORDS.put("暗光稳定接口尚未完整兼容","Low-light stability interfaces are not fully compatible");
        WORDS.put("稳定性测试版","Stability test");
        WORDS.put("亮度分支","Brightness paths");
        WORDS.put("最近曲线计算：","Last curve calculation: ");
        WORDS.put("曲线路径","Curve path");
        WORDS.put("输出路径","Output path");
        WORDS.put("标准映射曲线","Standard mapping curve");
        WORDS.put("Refactor 曲线","Refactor curve");
        WORDS.put("场景修正","Scene adjustment");
        WORDS.put("手动保持修正","Manual hold adjustment");
        WORDS.put("短期记忆模型","Short-term memory model");
        WORDS.put("夜间唤醒策略","Night wake policy");
        WORDS.put("暗光稳定","Low-light stability");
        WORDS.put("已改写目标","Target changed");
        WORDS.put("未改写目标","Target unchanged");
        WORDS.put("系统回退","System fallback");
        WORDS.put("临时亮度","Temporary brightness");
        WORDS.put("应用指定亮度","App brightness override");
        WORDS.put("曲线：","Curve: ");
        WORDS.put("输出：","Output: ");
        WORDS.put("适配 HyperOS 4 的自动亮度工具。\n\n以系统双侧感光与场景判定为基础，提供可编辑曲线、预设与手动偏好记忆。保留系统平滑过渡，也可按需调整温控和变化确认时间。","Automatic brightness for HyperOS 4.\n\nBuilt on system sensor fusion and scene detection, with editable curves, presets and manual brightness memory. Keeps smooth system transitions, with optional thermal and light-change controls.");
        WORDS.put("Root 已授权。请在 LSPosed 启用 HyperLux，勾选系统框架，然后重启手机。\n从旧测试版迁移时，请先关闭旧版的 LSPosed 开关。","Root is granted. Enable HyperLux in LSPosed, select System Framework, then restart.\nDisable the old test module’s LSPosed switch before migrating.");
        WORDS.put("请在 Root 管理器中允许 HyperLux 获得 Root 权限，再点击重新检测。\nRoot 可用后才会继续检查 LSPosed。","Allow Root access for HyperLux in your Root manager, then check again.\nLSPosed can be checked once Root is available.");
        WORDS.put("完全开源免费。欢迎捐赠 2.3 元支持开发。备注「昵称：想说的一句话」，总计不超过 30 个字符，下次更新加入感谢名单。","Free and open source. A ¥2.3 donation supports development. Add “name: a message” (30 characters total) to join the next update’s credits.");
        WORDS.put("适配 HyperOS 4 的自动亮度工具。可编辑与记忆的亮度曲线，配合系统场景感知和平滑调节。","Automatic brightness for HyperOS 4. Editable curves and manual brightness memory, with system scene sensing and smooth transitions.");
        WORDS.put("✓ Root 授权已通过\n○ 系统框架连接未建立\n请核对 LSPosed 作用域和是否重启","✓ Root granted\n○ System Hook not connected\nCheck the LSPosed scope and restart the phone");
        WORDS.put("通过 LSPosed 接入系统曲线，沿用系统光感与亮度输出。Root 用于设置与诊断。","LSPosed connects to the system curve while keeping its sensors and brightness output. Root is used for settings and diagnostics.");
        WORDS.put("变亮 0.5～10 秒，变暗 1～15 秒。小幅变亮、闲置与驾驶模式继续沿用系统策略。","Brighten: 0.5–10 s; dim: 1–15 s. Small increases, idle and driving modes retain system policy.");
        WORDS.put("默认关闭。开启后可减少显示层的温控限亮；严重过热或达到电池温度阈值时恢复系统策略。","Off by default. Reduces display-layer thermal dimming. System protection resumes during severe heat or at the battery threshold.");
        WORDS.put("变亮 0.5～10 秒，变暗 1～15 秒。闲置与驾驶模式继续沿用系统策略。","Brighten: 0.5–10 s; dim: 1–15 s. Idle and driving modes retain system policy.");
        WORDS.put("节点受系统上下限和相邻节点约束，亮度随照度不递减；最高照度端保持系统上限。","Points stay within system limits and cannot fall below their neighbors. The last point stays at the system maximum.");
        WORDS.put("关闭后不再记入新调整，已有记忆保留。记忆可能被系统重置，不保证跨重启保留。","Turning this off keeps existing memory. The system may reset it, and a reboot may clear it.");
        WORDS.put("Root 已获授权，但系统仍在运行旧版 Hook。请重启手机以加载新版本。","Root is granted, but the old Hook is still loaded. Restart the phone to load the new version.");
        WORDS.put("默认沿用系统。光线持续越过变化阈值后再调节，等待越长越不易受短暂遮挡影响。","Uses system delays by default. Longer confirmation reduces reactions to brief obstructions.");
        WORDS.put("手动亮度立即生效，也会影响附近照度的曲线。强度越低，每次记住的调整越少。","Manual changes take effect immediately and shape the curve nearby. Lower strength remembers less each time.");
        WORDS.put("尚未连接 Hook：请在 LSPosed 启用本模块，勾选系统框架并重启","Hook disconnected. Enable the module in LSPosed, select System Framework, and restart.");
        WORDS.put("请在 Root 管理器中卸载这些旧模块并重启，避免多套引擎同时调节亮度。","Uninstall these old modules in your Root manager, then restart to avoid overlapping brightness control.");
        WORDS.put("可设 38～50℃。达到阈值交回系统，冷却到设定幅度后再允许减少降亮。","Range: 38–50℃. System control resumes at the threshold; relaxation returns after cooling by the margin.");
        WORDS.put("可设 38～50℃，冷却 1℃后重新允许。硬件及其他系统限制仍生效。","Range: 38–50°C; resumes after cooling by 1°C. Hardware and other system limits still apply.");
        WORDS.put("导出到手机存储根目录，包含运行记录、设备状态、显示链路与温控信息。","Exports logs, device status, display and thermal information to the storage root.");
        WORDS.put("在相近照度范围内延续同一次记忆；暗处至少保留 5 lux 的容差。","Nearby light levels share one adjustment, with at least 5 lux tolerance in dim light.");
        WORDS.put("0.5～15 秒。仅影响系统判定的微小变亮；关闭后沿用系统时间。","0.5–15 s. Applies only to small increases identified by the system; uses system timing when disabled.");
        WORDS.put("100% 为系统基础值。范围由系统亮度上下限及相邻节点决定。","100% is the system baseline. System brightness limits and neighboring points define this range.");
        WORDS.put("关闭请求已保存，但系统尚未确认恢复；请重启，暂不恢复旧引擎","Disable request saved, but restoration is not confirmed. Restart before resuming the old engine.");
        WORDS.put("关闭请求已保存；请重启后再点停用，确认恢复并解除旧模块暂停","Disable request saved. Restart and select Disable again to confirm restoration and resume the old module.");
        WORDS.put("保留基础曲线和最近滑块位置，仅清除当前曲线的手动锚点。","Keep your base curve and last slider position. Clear only the remembered curve points.");
        WORDS.put("节点必须随照度不递减，请降低前一个节点或提高后一个节点","Brightness cannot decrease as light rises. Lower the previous point or raise the next one.");
        WORDS.put("已清除当前手动曲线锚点；系统保存的最近滑块位置保持原样","Manual points cleared; the saved slider position is unchanged");
        WORDS.put("当前已恢复系统曲线。请核对兼容状态，再重新保存并应用。","System curves have been restored. Check compatibility, then save and apply again.");
        WORDS.put("高照度端暂保持官方上限，请保持第四个参数为 100%","The last point must stay at the system maximum (100%)");
        WORDS.put("当前系统进程 · 最近 160 条 · 最新在下方","Current system session · Last 160 entries · Newest at the bottom");
        WORDS.put("已接入小米曲线。系统手动保持仍可能影响当前输出。","Curve applied. A system manual override may still affect brightness.");
        WORDS.put("曲线高度是逻辑亮度比例；屏幕亮度由系统标定换算。","Curve height is a logical ratio; the system converts it to screen brightness.");
        WORDS.put("当前为手动亮度，曲线将在开启自动亮度后参与调节。","Manual brightness is on. The curve takes effect when auto brightness is enabled.");
        WORDS.put("灰：系统基础 · 蓝：自定义 · 绿：手动记忆","Gray: system · Blue: custom · Green: learned");
        WORDS.put("QQ 交流群 314981836 · 点击复制","QQ group 314981836 · Copy");
        WORDS.put("主光感和辅助光感，经融合与场景判断产生有效照度","Main and assist sensors feed fusion and scene detection to produce effective light");
        WORDS.put("已恢复官方基础曲线，并恢复由本应用暂停的旧模块","System curve restored; the old module paused by this app has been resumed");
        WORDS.put("间隔以内的连续拖动视为一次调整，避免重复累积。","Consecutive moves within this interval count as one adjustment.");
        WORDS.put("自定义曲线已接入，官方光感和过渡动画继续运行","Custom curve connected; system sensors and transitions retained");
        WORDS.put("预设已按本机可调范围调整，保存并应用后生效","Preset adjusted to this device’s limits. Save & apply to activate it.");
        WORDS.put("请先在官方曲线 test01 中恢复原配置","Restore the original configuration in curve test01 first");
        WORDS.put("照度定位曲线，换算亮度后交由系统平滑调节。","Light selects a point on the curve. The system converts it to brightness and smooths the transition.");
        WORDS.put("已清除本次系统曲线的手动锚点，保留基础曲线","Manual points cleared; base curve retained");
        WORDS.put("此固件温控亮度接口尚未兼容，不能启用该选项","Thermal control is unsupported on this firmware; this option cannot be enabled.");
        WORDS.put("纵轴为曲线相对强度，不是屏幕亮度百分比。","Curve height is relative strength, not screen brightness percentage.");
        WORDS.put("进入设置自动读取；修改后点击保存并应用。","Settings refresh when opened. Save & apply your changes.");
        WORDS.put("此固件曲线接口尚未兼容，保留官方行为：","Curve interface unsupported; system behavior retained: ");
        WORDS.put("收集曲线、运行状态与本次系统进程日志…","Collecting curves, status and session logs…");
        WORDS.put("微小变亮确认时间应在 0.5～15 秒","Small-increase delay must be 0.5–15 s");
        WORDS.put("系统尚未确认曲线接入，已撤回本次提交","The system did not confirm the curve. Changes have been rolled back.");
        WORDS.put("设置未完成","Settings could not be applied");
        WORDS.put("系统未在 6 秒内确认本次配置。","The system did not acknowledge these settings within 6 seconds.");
        WORDS.put("未取得当前系统进程的有效确认，请核对 LSPosed 并重启。","No valid acknowledgement from the current system process. Check LSPosed and restart.");
        WORDS.put("最后确认状态：","Last acknowledgement: ");
        WORDS.put("已恢复此前配置；你在界面中的修改仍保留，尚未保存。","Previous settings were restored. Your edits are still available and have not been saved.");
        WORDS.put("未能确认恢复此前配置，请导出分析包；不要连续点击保存。","Restoration could not be confirmed. Export an analysis package before trying again.");
        WORDS.put("拖动节点调整亮度，点击节点输入数值。","Drag a point to adjust brightness. Tap it to enter a value.");
        WORDS.put("1.0.0 · APP 测试版 03","1.0.0 · App test 03");
        WORDS.put("该预设来自其他固件，请先核对曲线节点","This preset is from another firmware. Check the curve points first.");
        WORDS.put("未取得 Root 响应，请确认授权。","No Root response. Check the permission grant.");
        WORDS.put("已应用，官方动画与传感器继续控制主屏","Applied; system sensors and animation control the main display");
        WORDS.put("系统尚未确认锚点清除，请重新读取状态","Point reset is not confirmed yet. Refresh the status.");
        WORDS.put("只影响状态显示，不改变亮度调节频率。","Only changes display refresh; brightness control is unaffected.");
        WORDS.put("LumaCurve 官方曲线测试模块","LumaCurve system-curve test module");
        WORDS.put("314981836，暗号：1691","314981836, passcode: 1691");
        WORDS.put("拖动节点调整曲线，点击节点输入数值","Drag a curve point or tap it to enter a value");
        WORDS.put("手动亮度已调整，本次不写入曲线锚点","Manual brightness changed; not remembered in the curve");
        WORDS.put("当前系统进程 · 最近 160 条","Current system process · Last 160 entries");
        WORDS.put("提交小米基础曲线并等待系统确认…","Submitting the curve and waiting for confirmation…");
        WORDS.put("曲线已选中，点击保存并应用后生效","Curve selected. Save & apply to activate it.");
        WORDS.put("拖动或点击节点 · 高照度端固定","Drag or tap a point · Last point is fixed");
        WORDS.put("包含设备与显示信息，请按需分享。","Contains device and display information. Share only as needed.");
        WORDS.put("节点强度范围是 10%～200%","Point strength must be 10%–200%");
        WORDS.put("系统曲线已连接；主屏接口核对通过","System curve connected; main display verified");
        WORDS.put("已连接小米曲线，当前沿用官方基准","Xiaomi curve connected; using system baseline");
        WORDS.put("锚点记忆强度应在 0%～100%","Memory strength must be 0%–100%");
        WORDS.put("✓ Root 与系统框架已连接\n","✓ Root and system framework connected\n");
        WORDS.put("旧引擎仍在退出，尚未启用新曲线","The old engine is still stopping. The new curve has not been enabled.");
        WORDS.put("温控恢复阈值应在 38～50℃","Battery threshold must be 38–50℃");
        WORDS.put("此固件的温控亮度接口尚未兼容","The thermal brightness interface is unsupported on this firmware");
        WORDS.put("未找到浏览器，可复制网址打开","No browser found. The address has been copied.");
        WORDS.put("曲线已应用，重新建立基础锚点","Curve applied; base points rebuilt");
        WORDS.put("设置已更新，保留当前手动锚点","Settings updated; remembered points kept");
        WORDS.put("温控亮度保持可用（仅显示层）","Reduced thermal dimming available (display layer)");
        WORDS.put("已跳过显示层温控降亮；电池 ","Display thermal dimming skipped; battery ");
        WORDS.put("此系统的确认时间接口暂未兼容","Custom light-change delays are unavailable on this firmware");
        WORDS.put("LumaCurve 旧版模块","Legacy LumaCurve module");
        WORDS.put("○ 接入异常，请查看详细读数","○ Hook error; see detailed readings");
        WORDS.put("此系统的微小变亮接口暂未兼容","Small-increase timing is unavailable on this firmware");
        WORDS.put("等待温度读数，系统温控生效","Waiting for temperature; system thermal control active");
        WORDS.put("最高照度节点固定为系统上限","The last point is fixed at the system maximum");
        WORDS.put("接入异常，已尝试恢复官方：","Hook error; system restoration attempted: ");
        WORDS.put("系统已更新，请重新应用曲线","The system was updated. Reapply the curve.");
        WORDS.put("温控冷却幅度应在 1～3℃","Cooling margin must be 1–3℃");
        WORDS.put("分析包保存到手机存储根目录","Analysis archive saves to the storage root");
        WORDS.put("当前用户与曲线配置不一致","The current user does not match the curve configuration");
        WORDS.put("HyperLux 交流群","HyperLux group");
        WORDS.put("预设名称，最多 24 字","Preset name (up to 24 characters)");
        WORDS.put("正在应用曲线和温控选项…","Applying the curve and options…");
        WORDS.put("LSPosed 尚未接入","LSPosed not connected");
        WORDS.put("○ 温控显示接口暂未兼容","○ Display thermal interface unsupported");
        WORDS.put("已恢复官方曲线与温控策略","System curve and thermal control restored");
        WORDS.put("用户已切换，恢复官方策略","User changed; system control restored");
        WORDS.put("恢复上一轮标准曲线测试…","Restoring the previous curve test…");
        WORDS.put("收集系统温控与固件信息…","Collecting thermal and firmware information…");
        WORDS.put("○ 当前使用系统基础曲线","○ Using the system base curve");
        WORDS.put("尚未连接兼容的系统曲线","No compatible system curve connected");
        WORDS.put("逻辑亮度边界类型已变化","The logical brightness boundary type has changed");
        WORDS.put("载入后点击保存并应用。","After loading, select Save & apply.");
        WORDS.put(" lux · 节点强度"," lux · Point strength");
        WORDS.put("温度较高，系统温控生效","Temperature limit reached; system control active");
        WORDS.put("相邻节点限制了可调范围","Neighboring points limit this range");
        WORDS.put("已交回官方温控亮度策略","System thermal control restored");
        WORDS.put("本应用暂只支持主用户","Only the main user is supported");
        WORDS.put("本应用暂只支持主用户，请切回主用户后重试","Only the main user is supported. Switch back to the main user and retry.");
        WORDS.put("系统亮度的用户身份尚未就绪，请稍后再点保存并应用","The display user identity is not ready. Wait a moment and save again.");
        WORDS.put("需要 Root 权限","Root permission required");
        WORDS.put("连接系统后再保存预设","Connect to the system before saving a preset");
        WORDS.put("需要 Root 授权","Root permission required");
        WORDS.put("✓ 主屏曲线接口兼容","✓ Main-display curve supported");
        WORDS.put("✓ 自定义曲线已应用","✓ Custom curve active");
        WORDS.put("○ 当前使用官方基准","○ System baseline active");
        WORDS.put("✓ 温控显示接口兼容","✓ Display thermal interface supported");
        WORDS.put("已连接 · 官方曲线","Connected · System curve");
        WORDS.put("查看仓库了解更新内容","See the repository for release details");
        WORDS.put("确认时间超出可调范围","Light-change delay is outside the allowed range");
        WORDS.put("记忆分组参数超出范围","Memory grouping settings are outside the allowed range");
        WORDS.put("○ 温控接口暂未兼容","○ Thermal interface unavailable");
        WORDS.put("正在清除手动记忆…","Clearing brightness memory…");
        WORDS.put("融合滤波与场景判定","Fusion, filtering & scene detection");
        WORDS.put("连接后显示节点范围","Connect to see point limits");
        WORDS.put("手动偏好：等待读取","Memory: waiting for data");
        WORDS.put("正在等待系统状态…","Waiting for system status…");
        WORDS.put("入群暗号：1691","Passcode: 1691");
        WORDS.put("预设已保存到本机：","Preset saved: ");
        WORDS.put("请输入范围内的数值","Enter a value within the range");
        WORDS.put("正在恢复官方策略…","Restoring system control…");
        WORDS.put("减少温控降亮已启用","Reduced thermal dimming enabled");
        WORDS.put("✓ 系统框架已连接","✓ System Hook connected");
        WORDS.put("官方手动锚点更新：","Manual point updated: ");
        WORDS.put("暂停旧版亮度引擎…","Pausing the old brightness engine…");
        WORDS.put("收集系统显示链路…","Collecting display information…");
        WORDS.put("另一项操作还在执行","Another operation is still running");
        WORDS.put("自定义变化确认时间","Custom light-change delays");
        WORDS.put("当前没有新应用版本","No new app release available");
        WORDS.put("请卸载旧版亮度模块","Remove old brightness modules");
        WORDS.put("自定义微小变亮确认","Custom small-increase delay");
        WORDS.put("关闭请求保存失败","Could not save the disable request");
        WORDS.put("状态目录创建失败","Could not create the status directory");
        WORDS.put("记住我的手动调整","Remember manual adjustments");
        WORDS.put("等待读取手动锚点","Waiting for remembered points");
        WORDS.put("清除当前手动记忆","Clear current memory");
        WORDS.put("已复制群号与暗号","Group number and passcode copied");
        WORDS.put("还没有自定义预设","No custom presets yet");
        WORDS.put("尚未连接系统曲线","System curve not connected");
        WORDS.put("正在导出分析包…","Exporting analysis…");
        WORDS.put("系统接口尚未兼容","System interface unsupported");
        WORDS.put("系统处于手动亮度","Manual brightness is on");
        WORDS.put("使用系统基础曲线","Using the system curve");
        WORDS.put("该固件接口未兼容","Unsupported on this firmware");
        WORDS.put("当前没有手动锚点","No manual point yet");
        WORDS.put("状态格式不兼容：","Unsupported status format: ");
        WORDS.put(" · 变亮 > "," · Brighten above ");
        WORDS.put("需要四个曲线参数","Four curve parameters required");
        WORDS.put("记忆照度范围：±","Memory light range: ±");
        WORDS.put("自动检查应用更新","Automatic app update checks");
        WORDS.put("暂时无法检查更新","Unable to check for updates");
        WORDS.put("系统确认时间无效","Invalid system light-change delay");
        WORDS.put("手动锚点输入无效","Invalid manual brightness point");
        WORDS.put("✓ 温控接口兼容","✓ Thermal interface compatible");
        WORDS.put("旧预设文件过大","The old preset file is too large");
        WORDS.put("配置格式不兼容","Unsupported configuration format");
        WORDS.put("照度与亮度曲线","Light & brightness curve");
        WORDS.put("清除手动记忆？","Clear brightness memory?");
        WORDS.put("电池温度阈值：","Battery threshold: ");
        WORDS.put("温控：等待读取","Thermal: waiting for data");
        WORDS.put(" · 尚未保存"," · Unsaved");
        WORDS.put(" · 系统速度"," · System speed");
        WORDS.put(" · 缓慢记忆"," · Gentler memory");
        WORDS.put("请填写预设名称","Enter a preset name");
        WORDS.put("请输入有效数字","Enter a valid number");
        WORDS.put("自动亮度已接入","Auto brightness connected");
        WORDS.put("已交回系统控制","System control restored");
        WORDS.put("；系统热状态 ","; Thermal status: ");
        WORDS.put("系统锚点位于 ","Remembered point at ");
        WORDS.put("手动记忆节点：","Remembered points: ");
        WORDS.put("连接后读取曲线","Connect to read the curve");
        WORDS.put("% · 可调 ","% · Range ");
        WORDS.put("曲线坐标不兼容","Unsupported curve coordinates");
        WORDS.put("该节点不可编辑","This point cannot be edited");
        WORDS.put("连续调节间隔：","Gesture grouping interval: ");
        WORDS.put("状态刷新间隔：","Status refresh interval: ");
        WORDS.put("正在检查更新…","Checking for updates…");
        WORDS.put("暗号：1691","Join code: 1691");
        WORDS.put("微小变亮确认：","Small-increase delay: ");
        WORDS.put("命令输出过长","Command output is too long");
        WORDS.put("配置提交失败","Could not submit the configuration");
        WORDS.put("状态写入失败","Could not publish status");
        WORDS.put("配置标识无效","Invalid configuration identifier");
        WORDS.put("等待系统连接","Waiting for the system");
        WORDS.put("当前亮度曲线","Current brightness curve");
        WORDS.put("当前屏幕亮度","Current screen brightness");
        WORDS.put("曲线计算亮度","Calculated brightness");
        WORDS.put("手动偏好记忆","Brightness memory");
        WORDS.put("减少温控降亮","Reduce thermal dimming");
        WORDS.put("最近运行记录","Recent activity");
        WORDS.put("保存曲线预设","Save curve preset");
        WORDS.put("我的曲线预设","My curve presets");
        WORDS.put("编辑曲线节点","Edit curve point");
        WORDS.put("分析包已导出","Analysis exported");
        WORDS.put("系统温控生效","System thermal control");
        WORDS.put("尚无运行记录","No activity yet");
        WORDS.put("等待变化阈值","Waiting for change thresholds");
        WORDS.put("曲线节点无效","Invalid curve point");
        WORDS.put("曲线参数无效","Invalid curve parameters");
        WORDS.put("，记忆强度 ",", memory strength ");
        WORDS.put("完成分析包…","Finishing the analysis archive…");
        WORDS.put("发现新版本 ","New version: ");
        WORDS.put("有新版本可用","Update available");
        WORDS.put("QQ 交流群","QQ community");
        WORDS.put(" · 已停用"," · Disabled");
        WORDS.put(" · 待更新"," · Update pending");
        WORDS.put(" · 已安装"," · Installed");
        WORDS.put("操作失败：","Operation failed: ");
        WORDS.put("操作超时：","Operation timed out: ");
        WORDS.put("保存并应用","Save & apply");
        WORDS.put("停用并恢复","Disable & restore");
        WORDS.put("保存为预设","Save preset");
        WORDS.put("记忆强度 ","Memory strength ");
        WORDS.put("运行与兼容","Connection & compatibility");
        WORDS.put("导出分析包","Export analysis");
        WORDS.put("已删除预设","Preset deleted");
        WORDS.put("可调范围：","Available range: ");
        WORDS.put("输入百分比","Enter a percentage");
        WORDS.put("手动偏好：","Memory: ");
        WORDS.put("变暗 < ","Dim below ");
        WORDS.put("冷却幅度：","Cooling margin: ");
        WORDS.put("变亮确认：","Brightening delay: ");
        WORDS.put("变暗确认：","Dimming delay: ");
        WORDS.put("系统已更新","System updated");
        WORDS.put("变亮 > ","Brighten above ");
        WORDS.put("已复制群号","Group ID copied");
        WORDS.put("接口检查","Interface check");
        WORDS.put("参数过长","Parameters are too long");
        WORDS.put("未知操作","Unknown operation");
        WORDS.put("请求过长","Request is too long");
        WORDS.put("配置过长","Configuration is too long");
        WORDS.put("辅助光感","Assist light sensor");
        WORDS.put("详细读数","Detailed readings");
        WORDS.put("引擎控制","Engine");
        WORDS.put("系统默认","System");
        WORDS.put("我的预设","My presets");
        WORDS.put("（建议）"," (recommended)");
        WORDS.put("尚无记录","No entries yet");
        WORDS.put("开源协议","License");
        WORDS.put("作者博客","Blog");
        WORDS.put("酷安主页","Coolapk");
        WORDS.put("感谢名单","Thanks");
        WORDS.put("重新检测","Check again");
        WORDS.put("已导出：","Exported: ");
        WORDS.put("操作完成","Done");
        WORDS.put("连接中断","Disconnected");
        WORDS.put("等待连接","Waiting for connection");
        WORDS.put("接入异常","Hook error");
        WORDS.put("官方基准","System baseline");
        WORDS.put("等待计算","Waiting for calculation");
        WORDS.put("等待输出","Waiting for output");
        WORDS.put("暂无读数","No reading");
        WORDS.put("未启用：","Not enabled: ");
        WORDS.put("场景响应","Scene response");
        WORDS.put("检查更新","Check updates");
        WORDS.put("下载更新","Download update");
        WORDS.put("变暗 —","Dim —");
        WORDS.put("变亮 —","Brighten —");
        WORDS.put("复制群号","Copy group ID");
        WORDS.put("连接中","Connecting");
        WORDS.put("主光感","Main light sensor");
        WORDS.put("支付宝","Alipay");
        WORDS.put("知道了","Got it");
        WORDS.put("未连接","Not connected");
        WORDS.put("不兼容","Unsupported");
        WORDS.put("运行中","Active");
        WORDS.put("温控：","Thermal: ");
        WORDS.put("电池 ","Battery ");
        WORDS.put("无读数","No reading");
        WORDS.put("系统：","System: ");
        WORDS.put("构建：","Build: ");
        WORDS.put("版本 ","Version ");
        WORDS.put("正式版","Stable release");
        WORDS.put("温控","Thermal");
        WORDS.put("柔和","Soft");
        WORDS.put("稍亮","Brighter");
        WORDS.put("刷新","Refresh");
        WORDS.put("官网","Website");
        WORDS.put("微信","WeChat");
        WORDS.put("打赏","Support");
        WORDS.put("状态","Status");
        WORDS.put("设置","Settings");
        WORDS.put("日志","Logs");
        WORDS.put("关于","About");
        WORDS.put("取消","Cancel");
        WORDS.put("清除","Clear");
        WORDS.put("稍后","Later");
        WORDS.put("保存","Save");
        WORDS.put("删除","Delete");
        WORDS.put("载入","Load");
        WORDS.put("关闭","Close");
        WORDS.put("网址","Web address");
        WORDS.put("确定","Confirm");
        WORDS.put(" 个"," points");
        WORDS.put("正常","Normal");
        WORDS.put("轻微","Light");
        WORDS.put("中等","Moderate");
        WORDS.put("严重","Severe");
        WORDS.put("危急","Critical");
        WORDS.put("紧急","Emergency");
        WORDS.put("关机","Shutdown");
        WORDS.put("未知","Unknown");
        WORDS.put(" 秒"," s");
        WORDS.put("界面","Interface");
        WORDS.put("未取得","Unavailable");
        WORDS.put("自动亮度","Automatic brightness");
        WORDS.put("息屏显示","Always-on display");
        WORDS.put("熄屏","Screen off");
        WORDS.put("HDR 场景进入，输出可能增强","HDR scene entered; output may be boosted");
        WORDS.put("HDR 场景退出，输出恢复常规策略","HDR scene ended; output returned to normal policy");
        WORDS.put("开始改写目标","Target adjustment started");
        WORDS.put("停止改写目标","Target adjustment stopped");
        WORDS.put("亮度与偏好","Brightness and preferences");
        WORDS.put("环境变化与过渡","Environment and transitions");
        WORDS.put("场景与保护","Scenes and protection");
        WORDS.put("运行状态与界面","Runtime and interface");
        WORDS.put("主光感确认","Main sensor confirmation");
        WORDS.put("参数生效状态","Applied parameter status");
        WORDS.put("户外可读性","Outdoor readability");
        WORDS.put("户外高亮增强","Outdoor brightness boost");
        WORDS.put("持续强光下提高亮度","Boost brightness in sustained sunlight");
        WORDS.put("确认持续强光后，在系统曲线目标之上增加亮度，保留系统平滑过渡。离开强光、锁屏、手动调节或温度较高时退出。默认关闭。","Raises the system brightness target after sustained bright light is confirmed, using system transitions. Exits in lower light, on screen off, manual adjustment or elevated temperature. Off by default.");
        WORDS.put("等待读取户外高亮条件","Waiting for outdoor brightness conditions");
        WORDS.put("查看高亮条件","View high brightness conditions");
        WORDS.put("展开高亮参数","Expand boost options");
        WORDS.put("调整自动 HBM 触发与预算","Adjust automatic HBM threshold and budget");
        WORDS.put("仅支持实际启用 HBM 计时的设备。预算最多为系统的 2 倍，且不超过原时间窗口；保留使用历史、省电与温控条件。0 预算不会被当作无限制。","Only for devices using HBM timing. Budget is limited to twice the system value and the original window. Usage history, power saving and thermal conditions remain. A zero budget is never treated as unlimited.");
        WORDS.put("开放系统映射内的高亮范围","Unlock brightness within the system mapping");
        WORDS.put("实验选项：满足户外条件时放宽软件峰值范围，最高仍受本机亮度映射限制。HBM 时间不足时不开放，HDR、画面限亮及驱动保护继续生效；不保证额外提升。","Experimental: expands the software brightness range in confirmed outdoor conditions, within this device’s mapping. HBM time restrictions, HDR, content limits and driver protection remain. Additional brightness is not guaranteed.");
        WORDS.put("进入照度","Entry illuminance");
        WORDS.put("全强度照度","Full-strength illuminance");
        WORDS.put("进入确认","Entry confirmation");
        WORDS.put("退出确认","Exit confirmation");
        WORDS.put("退出照度比例","Exit light ratio");
        WORDS.put("增强强度","Boost strength");
        WORDS.put("单次最长增强","Maximum boost session");
        WORDS.put("增强冷却","Boost cooldown");
        WORDS.put("HBM 触发照度倍率","HBM light threshold multiplier");
        WORDS.put("HBM 时间预算倍率","HBM time budget multiplier");
        WORDS.put("户外：","Outdoor: ");
        WORDS.put("强光增强中","Sunlight boost active");
        WORDS.put("正在确认持续强光","Confirming sustained bright light");
        WORDS.put("正在确认离开强光","Confirming lower light");
        WORDS.put("照度未达到户外条件","Light is below the outdoor threshold");
        WORDS.put("本次增强结束，冷却中","Boost session ended; cooling down");
        WORDS.put("保留你的手动亮度","Keeping your manual brightness");
        WORDS.put("熄屏，沿用系统","Screen off; system policy");
        WORDS.put("手动模式，沿用系统","Manual mode; system policy");
        WORDS.put("HDR 或杜比场景，沿用系统","HDR or Dolby scene; system policy");
        WORDS.put("省电限制生效","Power saving limit active");
        WORDS.put("温度条件不满足，沿用系统保护","Temperature condition not met; system protection");
        WORDS.put("户外增强未开启","Outdoor boost is off");
        WORDS.put("请先保存并应用","Save and apply first");
        WORDS.put("户外接口尚未兼容","Outdoor interface unsupported");
        WORDS.put("等待系统自动亮度就绪","Waiting for system auto brightness");
        WORDS.put("特殊场景，沿用系统","Special scene; system policy");
        WORDS.put("系统 HBM 照度条件未满足","HBM light condition not met");
        WORDS.put("系统 HBM 时间预算不足","HBM time budget unavailable");
        WORDS.put("未取得完整条件，沿用系统","Conditions unavailable; system policy");
        WORDS.put("户外高亮","Outdoor brightness");
        WORDS.put("HBM 亮度分界","HBM transition brightness");
        WORDS.put("系统原范围上限","Original system range maximum");
        WORDS.put("当前范围上限","Effective range maximum");
        WORDS.put("设备映射上限","Device mapping maximum");
        WORDS.put("显示范围上限","Display range maximum");
        WORDS.put("最终限亮器上限","Final clamper maximum");
        WORDS.put("户外请求目标","Outdoor requested target");
        WORDS.put("本机使用 HBM 计时","This device uses HBM timing");
        WORDS.put("本机未启用 HBM 计时，不能据此推断没有其他限亮","HBM timing is disabled; other brightness limits may still apply");
        WORDS.put("HBM 原触发照度","Original HBM light threshold");
        WORDS.put("HBM 当前触发照度","Effective HBM light threshold");
        WORDS.put("HBM 剩余预算估值","Estimated remaining HBM budget");
        WORDS.put("最近观察到的输出限制","Recently observed output limits");
        WORDS.put("最近一分钟未观察到降亮，不代表驱动没有限制","No dimming observed in the past minute; driver limits may still apply");
        WORDS.put("画面灰阶限亮","Content grayscale limit");
        WORDS.put("显示温控","Display thermal limit");
        WORDS.put("电池限亮","Battery brightness limit");
        WORDS.put("省电限亮","Power saving brightness limit");
        WORDS.put("峰值范围","Peak range");
        WORDS.put("画面亮度修正","Content brightness correction");
        WORDS.put("SDR 输出","SDR output");
        WORDS.put("户外目标修正","Outdoor target adjustment");
        WORDS.put("户外增强在系统手动保持之后、最终范围限亮之前加入目标；不会写入基础曲线或手动记忆。","Outdoor boost raises the target after manual-hold processing and before final brightness limits. It does not change the base curve or user memory.");
        WORDS.put("数值是系统亮度坐标的百分比，不是实际 nit。请求目标、可用范围与实际输出分别记录；画面、温控和驱动仍可能限亮。高亮超时由独立事件计时，不依赖光感不断刷新。 ","Values are percentages of the system brightness coordinate, not measured nits. Requested targets, allowed range and actual output are recorded separately. Content, thermal and driver limits may remain. Session timers do not require repeated sensor events.");
        WORDS.put("户外增强开关必须是布尔值","Outdoor switches must be boolean");
        WORDS.put("户外增强参数必须是数值","Outdoor parameters must be numeric");
        WORDS.put("全强度照度须高于进入照度","Full-strength light must exceed entry light");
        WORDS.put("户外照度与时间须为整数","Outdoor light and time must be whole numbers");
        WORDS.put("请先开启户外增强，或关闭附加高亮选项","Enable outdoor boost or disable its additional options");
        WORDS.put("此固件的户外增强接口尚未兼容","Outdoor brightness is unsupported on this firmware");
        WORDS.put("此设备未使用可调整的 HBM 时间控制器","This device does not use an adjustable HBM time controller");
        WORDS.put("此固件的高亮范围接口尚未兼容","High-brightness range is unsupported on this firmware");
        WORDS.put("户外增强：","Outdoor boost: ");
        WORDS.put("户外增强恢复异常：","Outdoor restoration failed: ");
        WORDS.put("剩余 ","Remaining ");
        WORDS.put("临时或应用指定亮度，沿用系统","Temporary or app brightness override; system policy");
        WORDS.put("照度动态范围原上限","Original lux-based range limit");
        WORDS.put("照度动态范围现上限","Current lux-based range limit");
        WORDS.put("亮度曲线与偏好","Curve and preferences");
        WORDS.put("户外高亮","Outdoor brightness");
        WORDS.put("环境变化与确认","Ambient changes and confirmation");
        WORDS.put("亮度过渡","Brightness transitions");
        WORDS.put("场景与温控","Scenes and temperature");
        WORDS.put("返回设置","Back to settings");
        WORDS.put("复制配置","Copy configuration");
        WORDS.put("已复制配置，包含尚未应用的修改","Configuration copied, including unsaved changes");
        WORDS.put("已复制配置","Configuration copied");
        WORDS.put("暗处亮度下限、曲线预设与手动记忆","Darkness floor, curve presets and manual memory");
        WORDS.put("强光目标、可用范围与 HBM 预算","Outdoor target, available range and HBM budget");
        WORDS.put("变化阈值、主辅光感确认与暗光稳定","Change thresholds, sensor confirmation and low-light stability");
        WORDS.put("分别调整变亮和变暗的过渡时长","Separate brightening and dimming transitions");
        WORDS.put("触摸遮挡、手动阳光屏与温控策略","Touch occlusion, manual sunlight mode and temperature policy");
        WORDS.put("参数生效情况与界面刷新","Parameter activity and UI refresh");
        WORDS.put("最左侧节点可上移，设置暗处曲线的亮度下限。上限由下一个节点决定；需要更高时先提高下一个节点。系统手动选择和温控仍优先。","Raise the leftmost point to set a low-light curve floor. Its next point limits the height; raise that point first if needed. Manual choices and thermal limits take priority.");
        WORDS.put("暗处亮度下限","Low-light curve floor");
        WORDS.put("编辑最低照度节点","Edit lowest-lux point");
        WORDS.put("按本机曲线范围输入百分比，不是控制中心滑块的百分比。仅调整基础曲线，手动选择和温控仍优先。","Enter a percentage of this device's curve range, distinct from the system slider. Only the baseline curve changes; manual choices and thermal limits take priority.");
        WORDS.put("暗处亮度下限超出本机曲线范围","Low-light floor exceeds the device curve range");
        WORDS.put("暗处亮度下限必须是数值","Low-light floor must be numeric");
        WORDS.put("暗处亮度下限无效","Invalid low-light floor");
        WORDS.put("导出配置","Export configuration");
        WORDS.put("导入配置","Import configuration");
        WORDS.put("正在导出配置…","Exporting configuration…");
        WORDS.put("配置已导出","Configuration exported");
        WORDS.put("文件位于设备存储根目录。包含当前设置，可在后续版本导入。","Saved in the root of device storage. It contains the current settings and can be imported in later versions.");
        WORDS.put("导入后先检查设置，再点击保存并应用。旧版本缺少的新选项使用默认值。","Review the imported settings, then Save and apply. New options absent in older files use their defaults.");
        WORDS.put("导入会替换当前尚未保存的设置。","Import will replace your current unsaved settings.");
        WORDS.put("配置已导入，检查后点击保存并应用","Configuration imported. Review it, then Save and apply");
        WORDS.put("未找到文件选择器","File picker unavailable");
        WORDS.put("无法读取配置文件","Cannot read configuration file");
        WORDS.put("配置文件过大","Configuration file is too large");
        WORDS.put("配置文件版本暂不支持，请更新应用","Unsupported configuration version; update the app");
        WORDS.put("不是兼容的 HyperLux 配置文件","Not a compatible HyperLux configuration file");
        WORDS.put("配置参数无效：","Invalid configuration parameter: ");
        WORDS.put("配置开关无效：","Invalid configuration switch: ");
        WORDS.put("配置时间必须是整数：","Configuration times must be integers: ");
        WORDS.put("刷新时间必须是整数","Refresh interval must be an integer");
        WORDS.put("曲线基准不同，已保留本机曲线与亮度下限","Curve baseline differs; device curve and floor retained");
        WORDS.put("已调整超出范围的参数：","Out-of-range parameter adjusted: ");
        WORDS.put("已调整全强度照度","Full-strength lux adjusted");
        WORDS.put("本机不支持，已关闭：","Unsupported on this device; disabled: ");
        WORDS.put("已忽略当前版本不认识的设置：","Settings unknown to this version ignored: ");
        WORDS.put("有未保存的设置","Unsaved settings");
        WORDS.put("手动亮度模式","Manual brightness mode");
        WORDS.put("手动亮度","Manual brightness");
        WORDS.put("采样暂停","Sampling paused");
        WORDS.put("等待采样","Waiting for samples");
        WORDS.put("等待有效照度","Waiting for valid illuminance");
        WORDS.put("开启系统自动亮度后读取","Enable system auto brightness to read sensors");
        WORDS.put("运行状态与界面","Runtime and interface");
        WORDS.put("沿用系统双侧感光、场景判定与平滑过渡，提供可编辑曲线、暗处亮度下限与手动偏好记忆。户外高亮、温控和变化确认可按需调整，配置支持导入导出。","Uses system dual sensors, scene detection and smooth transitions, with editable curves, a low-light floor and manual preference memory. Outdoor brightness, thermal limits and confirmation delays are optional; settings can be imported and exported.");
        WORDS.put("曲线与记忆","Curve and memory");
        WORDS.put("手动记忆","Manual memory");
        WORDS.put("基础曲线决定起点，手动记忆修正附近亮度，存档用于下次恢复。手动保持只是暂时保持本次亮度，不等于偏好节点已删除。","The baseline is the starting point. Manual memory adjusts nearby brightness; the archive restores it later. A temporary brightness hold is separate from stored preference points.");
        WORDS.put("连接后显示实际节点与系统能力","Connect to view real points and device capabilities");
        WORDS.put("查看记忆节点与交接记录","View points and handover history");
        WORDS.put("记住手动偏好","Remember brightness preferences");
        WORDS.put("手动亮度立即生效；记忆强度决定附近曲线记住多少。100% 接近系统原有行为，较低值需多次调整才能逐步改变。","Manual brightness takes effect immediately. Memory strength controls how much the nearby curve learns. 100% follows the system behavior; lower values need repeated adjustments.");
        WORDS.put("渐进记忆","Gradual memory");
        WORDS.put("完整记忆","Full memory");
        WORDS.put("不记忆","No memory");
        WORDS.put("合并连续拖动，避免一次滑动被反复累计。","Groups continuous dragging so one gesture is not counted repeatedly.");
        WORDS.put("只控制一次拖动如何分组，不是离开保持或清除记忆的阈值。暗处至少容许 5 lux 的分组变化。","Only groups drag gestures; it does not end a hold or clear memory. Grouping allows at least 5 lux of variation in low light.");
        WORDS.put("保存与恢复","Save and restore");
        WORDS.put("存档保留天数","Archive retention");
        WORDS.put("最多保存手动点","Saved manual point limit");
        WORDS.put("0 为自动。只限制保存与恢复的数量，不增加基础编辑点，也不扩大系统锚点容器。修改基础曲线、用户或固件后旧存档不混用。关闭保存不会立即清除当前偏好。","0 means automatic. This limits saved and restored points, without expanding the editor or native capacity. Old archives are not reused after baseline, user or firmware changes. Turning saving off keeps current preferences.");
        WORDS.put("锁屏后的记忆","Memory after screen off");
        WORDS.put("亮屏后恢复已保存偏好","Restore saved preferences on wake");
        WORDS.put("仅在相近照度恢复","Restore only in similar light");
        WORDS.put("恢复照度容差","Restore light tolerance");
        WORDS.put("暗处最小容差","Minimum low-light tolerance");
        WORDS.put("亮屏采样稳定等待","Wake sample settling time");
        WORDS.put("保留锁屏前的完整偏好","Keep the full pre-lock preference");
        WORDS.put("亮屏先等有效照度，再恢复一次；新手动调整优先。完整偏好开启时，可替换系统锁屏交接后的旧备用节点；关闭时只在系统没有手动节点时恢复。环境明显变化时默认不恢复，也不会不断插回被系统清除的点。","Waits for valid light on wake, then restores once. New manual choices take priority. Full preference restoration can replace older backup points; when off, restoration only fills an empty curve. By default, changed light prevents restoration. Cleared points are not repeatedly reinserted.");
        WORDS.put("系统短期记忆","System short-term memory");
        WORDS.put("连接后读取系统记忆规则","Connect to inspect system memory rules");
        WORDS.put("自定义锁屏后重判规则","Customize wake reassessment rules");
        WORDS.put("照度变化重判起始","Minimum off time for light reassessment");
        WORDS.put("重判照度差","Reassessment light difference");
        WORDS.put("最长免重判熄屏时长","Maximum off time before reassessment");
        WORDS.put("默认沿用系统。熄屏超过起始时长且照度差超过阈值，或超过最长时长时，允许系统重判；Refactor 可能切换备用曲线，传统路径可能收窄偏好亮度。重判不是直接删除存档。","Uses the system rule by default. Reassessment is allowed after the minimum off time plus a light change, or the maximum off time. Refactor may use a backup curve; the traditional path may constrain the preference. Reassessment does not delete the archive.");
        WORDS.put("自定义短期模型失效时间","Customize short-term model timeout");
        WORDS.put("短期模型失效等待","Short-term model timeout");
        WORDS.put("模型失效后，系统会在下次有效照度到来时决定保留或重建曲线，并非到时间立刻清除。新时间只影响之后安排的计时，不修改已经排队的系统消息。","After invalidation, the next valid light sample determines whether to keep or rebuild the curve. Timeout does not instantly clear it. Changes apply to subsequently scheduled timers, not existing queued messages.");
        WORDS.put("基础编辑点：","Baseline editor points: ");
        WORDS.put(" 个 · 当前手动点："," · Live manual points: ");
        WORDS.put("当前曲线节点：","Current curve points: ");
        WORDS.put(" / 7（包含基础与手动点）"," / 7 (baseline and manual combined)");
        WORDS.put("本机保留完整基础曲线，手动模型支持 1 个偏好点","The full device baseline is retained; the manual model supports one preference point");
        WORDS.put("已保存：","Saved: ");
        WORDS.put(" 个 · 系统同区间新调整可能替换旧点"," · New choices in the same interval may replace old points");
        WORDS.put("锁屏重判接口可用","Wake reassessment is available");
        WORDS.put("锁屏重判接口暂未兼容","Wake reassessment is unsupported");
        WORDS.put("短期模型计时接口可用","Short-term timeout is available");
        WORDS.put("短期模型计时接口暂未兼容","Short-term timeout is unsupported");
        WORDS.put("最近交接：","Latest handover: ");
        WORDS.put("记忆状态待确认","Memory status pending");
        WORDS.put("亮屏／熄屏交接","Screen on/off handover");
        WORDS.put("系统重建记忆曲线","System rebuilt the memory curve");
        WORDS.put("短期模型标为失效","Short-term model invalidated");
        WORDS.put("系统检查备用曲线","System checked the backup curve");
        WORDS.put("系统评估锁屏后的记忆","System reassessed memory after screen off");
        WORDS.put("已恢复偏好存档","Preference archive restored");
        WORDS.put("当前节点","Live points");
        WORDS.put("存档节点","Archived points");
        WORDS.put("短期模型：","Short-term model: ");
        WORDS.put("已失效，等待系统判断","Invalid; awaiting system reassessment");
        WORDS.put("最近交接","Recent handovers");
        WORDS.put(" 个手动点"," manual points");
        WORDS.put("手动记忆详情","Manual memory details");
        WORDS.put("无手动节点","No manual points");
        WORDS.put("（曲线坐标）"," (curve coordinate)");
        WORDS.put("4 个基础编辑点；系统手动调整可形成最多 7 个总节点，见手动记忆页。","4 baseline editor points. System manual adjustments can produce up to 7 total points; see Manual memory.");
        WORDS.put("4 个编辑控制点；设备原有完整曲线节点全部保留，手动模型支持 1 个偏好点。","4 editor controls; all original device baseline points are retained. The manual model supports one preference point.");
        WORDS.put("拖动分组照度容差：±","Drag grouping light tolerance: ±");
        WORDS.put("系统场景变化已重建曲线，存档保留","System scene reassessment rebuilt the curve; the archive is retained");
        WORDS.put("记忆已保留，等待亮屏确认","Memory retained; awaiting wake confirmation");
        WORDS.put("等待亮屏后的有效照度","Waiting for valid light after wake");
        WORDS.put("亮屏确认超时，本次不恢复","Wake confirmation timed out; no restoration this time");
        WORDS.put("系统实时记忆优先，存档未覆盖","Live system memory takes priority; archive not applied");
        WORDS.put("等待有效照度后恢复记忆","Waiting for valid light to restore memory");
        WORDS.put("环境已变化，本次不恢复记忆","Light has changed; no restoration this time");
        WORDS.put("尚未观察到记忆交接","No memory handover observed yet");
        WORDS.put("手动记忆参数超出范围","Manual memory settings are outside the allowed range");
        WORDS.put("记忆开关必须是布尔值：","Memory switch must be boolean: ");
        WORDS.put("记忆参数无效：","Invalid memory setting: ");
        WORDS.put("本机暂不支持锁屏记忆重判设置","Wake memory reassessment settings are not supported on this device");
        WORDS.put("本机暂不支持短期记忆有效时间设置","Short-term memory timeout settings are not supported on this device");
        WORDS.put("相近照度同时参考锁屏前读数与存档点，避免换环境后再次锁屏带回不相关偏好。","Similar light is checked against both the pre-lock reading and archived points. Locking again in a new environment will not restore an unrelated preference.");
        WORDS.put("默认关闭。开启后延长暗光变化确认，可同时提高触发阈值。手动调节、熄屏、HDR、闲置与驾驶模式继续沿用系统。","Off by default. Extends low-light confirmation and optionally widens trigger thresholds. Manual adjustment, screen off, HDR, idle and driving keep the system policy.");
        WORDS.put("暗光小变化不调节","Ignore small light changes in dim environments");
        WORDS.put("仅在暗光稳定开启时生效。照度变化需超过比例、最小照度差与系统原有门槛中的较大值，且持续满足确认时间。主、辅助光感与微小变亮一起处理；不修改光感读数，不锁死屏幕亮度。","Requires Low-light stability. A sustained light change must exceed the largest of the relative margin, minimum lux difference and native threshold. Covers main and assist sensors, including small brightening. Sensor readings and screen brightness are not replaced.");
        WORDS.put("暗光少动","Less movement in low light");
        WORDS.put("关闭暗光稳定","Disable low-light stability");
        WORDS.put("少动预设：变亮需至少增加 60% 或 10 lux，变暗需至少减少 40% 或 2 lux。两者取更严格者；零照度仍可触发变暗。环境变亮到超过暗光范围后沿用正常策略。","Preset: brightening needs at least +60% or +10 lux; darkening needs at least −40% or −2 lux. The stricter margin wins; a true zero-lux sample can still trigger darkening. Normal policy resumes after the accepted light leaves the low-light range.");
        WORDS.put("暗光最小变亮比例","Low-light brightening margin");
        WORDS.put("暗光最小变亮照度差","Low-light minimum brightening difference");
        WORDS.put("暗光最小变暗比例","Low-light darkening margin");
        WORDS.put("暗光最小变暗照度差","Low-light minimum darkening difference");
        WORDS.put("延长变化确认，并可提高暗光触发阈值。保留原有传感器数值与系统过渡动画。","Extends confirmation and optionally widens low-light trigger thresholds, keeping native sensor readings and transition animations.");
        WORDS.put("暗光阈值实际调整：","Low-light threshold adjustments: ");
        WORDS.put("此系统的暗光阈值接口暂未兼容","Low-light threshold tuning is not supported on this system");
        WORDS.put("辅助光感参考闸门","Assist sensor confirmation gate");
        WORDS.put("暗处只有主光感变亮、辅助光感近期稳定时，多确认一会儿，抑制疑似屏幕反光。辅助也变化、被遮挡或读数过期时放行；主光感明显变亮或等待到时也放行。不是辅助光感一票否决。","When only the main sensor brightens in dim light and recent assist readings are stable, waits briefly to reduce suspected screen reflections. Releases if the assist changes, is covered or becomes stale, the main rises strongly, or the wait expires. The assist is not an absolute veto.");
        WORDS.put("单侧变亮最长观察：","Maximum main-only observation: ");
        WORDS.put("辅助稳定容差：±","Assist stability tolerance: ±");
        WORDS.put("%（至少 2 lux）","% (at least 2 lux)");
        WORDS.put("等待读取辅助闸门状态","Waiting for assist gate status");
        WORDS.put("辅助闸门：","Assist gate: ");
        WORDS.put(" · 观察 "," · Observations: ");
        WORDS.put("主光感单独变亮，观察中","Observing a main-only rise");
        WORDS.put("辅助无可靠证据，已放行","No reliable assist evidence; released");
        WORDS.put("辅助也有变化，已放行","Assist changed too; released");
        WORDS.put("主光感明显变亮，已放行","Strong main rise; released");
        WORDS.put("观察结束，已放行","Observation ended; released");
        WORDS.put("未触发主光感变亮","No main brightening trigger");
        WORDS.put("未启用或不适用","Disabled or not applicable");
        WORDS.put("辅助光感暗光闸门接口暂未兼容","The assist low-light gate is not supported on this system");
        WORDS.put("基础节点与手动记忆分开显示。","Base nodes and manual memory are shown separately.");
        WORDS.put("基础曲线决定各照度的亮度；手动调整的偏好请到「手动记忆」查看。","The base curve sets brightness at each lux level. See Manual memory for preferences from slider adjustments.");
        WORDS.put("左端可设置暗处亮度下限。若调不上去，先提高相邻节点；手动选择和温控仍优先。","Raise the left node to set a dim-light floor. If limited, raise the next node first. Manual choices and thermal limits still take priority.");
        WORDS.put("持续强光下提高目标亮度。离开强光、锁屏、手动调节或过热时退出。默认关闭。","Raises the target in sustained bright light. Exits when light falls, the screen locks, you adjust brightness, or heat limits apply. Off by default.");
        WORDS.put("仅支持带 HBM 计时的设备。预算最多为系统的 2 倍且不超时间窗口；仍受温控与省电限制。","Requires native HBM timing. Budget is capped at twice the native value and within its time window. Thermal and power limits remain.");
        WORDS.put("实验选项：放宽户外软件上限，仍受本机映射、HBM 预算与保护限制，不保证更亮。","Experimental: relaxes the outdoor software ceiling within device mapping, HBM budget, and protection limits. Extra brightness is not guaranteed.");
        WORDS.put("基础曲线定起点，手动记忆改附近亮度，存档供下次恢复。暂时保持亮度不等于清除记忆。","The base curve sets the starting point; manual memory adjusts nearby brightness; archives restore it later. A temporary hold does not clear memory.");
        WORDS.put("手动调节立即生效。强度越低，曲线记得越慢；100% 沿用系统力度。","Manual adjustments take effect immediately. Lower strength changes the curve more slowly; 100% uses native strength.");
        WORDS.put("只用于合并同一次拖动；不影响亮度保持或清除记忆。暗处容差至少 5 lux。","Only groups a single slider gesture; does not control brightness hold or memory clearing. Dim-light tolerance is at least 5 lux.");
        WORDS.put("0 为本机支持的最多数量，不增加编辑点。换曲线、用户或固件后不混用旧存档；关闭保存保留当前偏好。","0 uses the device capacity, without adding editing nodes. Archives are not reused across curve, user, or firmware changes. Disabling saving keeps current preferences.");
        WORDS.put("恢复时同时核对锁屏前照度与存档点，避免带回其他环境的偏好。","Restoration checks both pre-lock lux and archived anchors to avoid carrying preferences into a different environment.");
        WORDS.put("亮屏后确认照度，再恢复一次；新手动调整优先。开启完整偏好可替换旧备用点，关闭则只补空缺。","Restores once after wake and lux confirmation; new manual adjustments take priority. Complete preference restoration may replace older backup nodes; otherwise it only fills missing memory.");
        WORDS.put("熄屏够久且照度变化够大，或超过最长时长时，允许系统重判偏好；不会删除存档。默认沿用系统。","Allows native preference reassessment after enough screen-off time and lux change, or the maximum duration. Archives remain. Uses native rules by default.");
        WORDS.put("到时后，系统在下一次有效照度下重判。只影响新计时，不立即清除曲线。","After expiry, the next valid lux sample triggers native reassessment. Applies to new timers and does not clear the curve immediately.");
        WORDS.put("减少暗处小波动引起的调节。默认关闭；手动、熄屏、HDR 等特殊场景沿用系统。","Reduces adjustments from small dim-light fluctuations. Off by default; manual, screen-off, HDR, and other special modes use native handling.");
        WORDS.put("确认时间受采样窗口限制，保留系统更长等待。","Confirmation is bounded by the sensor history window; longer native waits remain.");
        WORDS.put("实际生效时间见下方「参数生效状态」。","See Parameter activity below for the effective timing.");
        WORDS.put("比例、最小照度差和系统门槛取更严格者；持续变化才调节，不修改光感读数。","Uses the stricter of the relative margin, minimum lux difference, and native threshold. Requires sustained change without modifying sensor readings.");
        WORDS.put("「暗光少动」提高亮暗门槛，并在本机支持时启用辅助闸门。选择后记得保存并应用。","Less movement raises dim-light thresholds and enables the assist gate when supported. Save and apply after choosing.");
        WORDS.put("仅主光感变亮、辅助近期稳定时多等一会儿。辅助变化、遮挡、过期，或明显变亮、等待到时即放行。","Waits briefly when only the main sensor rises and recent assist readings stay stable. Releases on assist changes, cover, stale data, a strong main rise, or timeout.");
        WORDS.put("倍率越大越不易调节，最小照度差过滤小波动。仅在设定照度内生效，特殊场景沿用系统。","Higher multipliers require larger changes; minimum lux differences filter small fluctuations. Applies within the chosen lux range; special modes use native thresholds.");
        WORDS.put("调整辅助光感的确认时间；暗光稳定开启时取更长等待，最长 4 秒。","Sets assist sensor confirmation. When dim-light stability is enabled, the longer wait applies, up to 4 seconds.");
        WORDS.put("倍率越大过渡越慢，亮暗分别设置。只影响正常自动亮度，不重启正在进行的过渡。","Higher multipliers slow transitions; set brightening and dimming separately. Only affects normal automatic brightness without restarting an active transition.");
        WORDS.put("调整手动模式阳光屏的进入、退出等待；不强制开启，也不改变自动 HBM 冷却。","Sets manual sunlight-mode entry and exit waits; does not force activation or alter automatic HBM cooldown.");
        WORDS.put("只调整手指移开后的等待。0 秒取消额外等待，仍保留遮挡保护。","Only adjusts the wait after a finger leaves. Zero removes the extra wait while keeping touch-cover protection.");
        WORDS.put("适配 HyperOS 4 的自动亮度工具。\n\n沿用系统双侧感光与平滑过渡，支持可编辑曲线、手动记忆保存与暗光稳定。户外高亮、温控和变化确认可按需调整，配置支持导入导出。","An automatic brightness tool for HyperOS 4.\n\nKeeps native dual sensors and smooth transitions, with editable curves, saved manual memory, and dim-light stability. Outdoor brightness, thermal limits, and confirmation are adjustable; configurations can be imported and exported.");
        WORDS.put("收起详细参数","Hide detailed parameters");
        WORDS.put("展开详细参数","Show detailed parameters");
        WORDS.put("预设已选中，保存并应用后生效","Preset selected. Save and apply to activate it.");
        WORDS.put("暗光更稳","Extra stability");
        WORDS.put("温和增强","Gentle boost");
        WORDS.put("均衡增强","Balanced boost");
        WORDS.put("适度放宽","Moderate relaxation");
        WORDS.put("反应灵敏","Responsive");
        WORDS.put("减少波动","Less fluctuation");
        WORDS.put("少些变化","Fewer changes");
        WORDS.put("更灵敏","More responsive");
        WORDS.put("快速确认","Quick confirmation");
        WORDS.put("稳妥确认","Steady confirmation");
        WORDS.put("柔和过渡","Smooth transitions");
        WORDS.put("快速过渡","Quick transitions");
        WORDS.put("快速响应","Quick response");
        WORDS.put("避免误触发","Fewer false triggers");
        WORDS.put("快速恢复","Quick recovery");
        WORDS.put("遮挡少动","Stable when covered");
        WORDS.put("暗光稳定与锁定","Low-light stability & lock");
        WORDS.put("主屏手动亮度","Manual display brightness");
        WORDS.put("暗光定时锁定","Timed low-light lock");
        WORDS.put("不锁定","No lock");
        WORDS.put("睡前保持","Bedtime hold");
        WORDS.put("暗光持续后关闭自动亮度","Switch to manual after sustained darkness");
        WORDS.put("保持进入时的亮度；照度明显升高后恢复自动。锁屏或重新开启自动亮度即退出。你主动关闭的自动亮度不会被重新开启。","Holds the current brightness, resuming auto when the environment brightens. Locking the screen or enabling auto ends the hold. Auto turned off by you will stay off.");
        WORDS.put("需要主辅光感共同确认暗处；任一侧持续变亮可退出。锁定期间低频监听光感，温控和应用指定亮度仍生效。","Both available sensors must confirm darkness; sustained light on either releases the hold. Low-rate monitoring continues during the hold. Thermal and app brightness limits remain.");
        WORDS.put("等待读取暗光锁定状态","Waiting for low-light lock status");
        WORDS.put("允许磁贴手动调节","Enable manual brightness tile");
        WORDS.put("滑动即关闭自动亮度，通过主屏框架接口直接设定亮度。系统重新开启自动亮度后，面板停止写入。","Dragging switches to manual and sets main-display brightness through the framework. Re-enabling auto stops this panel from writing.");
        WORDS.put("允许范围以系统当前报告为准，不绕过驱动上限。面板不会持续写值或锁住主屏节点。","Uses the range currently reported by the system. Does not bypass driver limits, repeatedly force brightness, or lock display nodes.");
        WORDS.put("打开主屏亮度面板","Open brightness panel");
        WORDS.put("添加控制中心磁贴","Add Quick Settings tile");
        WORDS.put("主屏亮度","Display brightness");
        WORDS.put("磁贴已添加","Tile added");
        WORDS.put("可在控制中心编辑磁贴时添加 HyperLux 主屏亮度","Add HyperLux display brightness from the Quick Settings editor");
        WORDS.put("进入照度：","Enter below: ");
        WORDS.put("等待时间：","Wait: ");
        WORDS.put("退出照度：","Resume above: ");
        WORDS.put("退出确认：","Resume confirmation: ");
        WORDS.put("已保持当前亮度","Holding current brightness");
        WORDS.put("暗光计时中","Darkness timer running");
        WORDS.put("等待持续暗光","Waiting for sustained darkness");
        WORDS.put("用户手动模式，不自动恢复","User-selected manual mode; no auto restoration");
        WORDS.put("主屏手动面板控制中","Manual panel active");
        WORDS.put("接口异常，已退出","Interface error; released");
        WORDS.put("未锁定","Not locked");
        WORDS.put("暗光锁定","Low-light hold");
        WORDS.put("滑动后关闭自动亮度。100% 是系统当前允许的上限，温控、HDR 与驱动仍可限亮。重新开启自动亮度后停止写入。","Dragging disables auto. 100% means the currently allowed limit; thermal, HDR and driver constraints still apply. Enabling auto stops writes.");
        WORDS.put("输入亮度值","Enter brightness value");
        WORDS.put("恢复自动亮度","Restore auto brightness");
        WORDS.put("系统亮度值","Framework brightness value");
        WORDS.put("主屏亮度范围尚未就绪","Display range is not ready");
        WORDS.put("已退让；再次滑动才会关闭自动亮度","Released; drag again to enter manual mode");
        WORDS.put("自动亮度中；滑动切换为手动","Auto brightness active; drag to switch to manual");
        WORDS.put("手动亮度；可使用完整允许范围","Manual brightness; full allowed range");
        WORDS.put("亮度超出当前允许范围","Brightness is outside the currently allowed range");
        WORDS.put("先启用引擎并保存主屏手动面板设置；若刚更新应用，请重启以载入新接口。","Enable the engine and save manual panel settings first. After updating the app, reboot to load the new interface.");
        WORDS.put("基础亮度、暗处下限与曲线预设","Baseline brightness, dark floor and presets");
        WORDS.put("偏好强度、持久保存与锁屏交接","Preference strength, persistence and wake handoff");
        WORDS.put("强光目标与系统高亮预算","Outdoor targets and system HBM budget");
        WORDS.put("主辅光感阈值与确认时间","Main/aux sensor thresholds and confirmation");
        WORDS.put("分别设置变亮和变暗时长","Separate brighten and dim transition times");
        WORDS.put("遮挡保护、阳光屏与温控","Cover protection, sunlight and thermal");
        WORDS.put("兼容状态与界面刷新","Compatibility and refresh");
        WORDS.put("减少暗光波动，或定时保持亮度","Reduce low-light changes or hold brightness after a delay");
        WORDS.put("磁贴面板、直接写值与自动退让","Tile panel, direct values and automatic release");
        WORDS.put("亮度控制方式","Brightness ownership");
        WORDS.put("系统调节","System control");
        WORDS.put("暗光锁定期间仅低频监听主辅光感；显著变亮后恢复自动。主屏面板退出后不再写值。温控、HDR 和应用指定亮度仍由系统处理。","Low-light lock monitors sensors at a low rate and restores auto in a brighter environment. Closing the panel ends UI queries; manual node hold continues. The system still handles thermal, HDR and app overrides.");
        WORDS.put("响应与保护","Response & protection");WORDS.put("运行与界面","Runtime & interface");
        WORDS.put("暗光锁定，保持当前亮度","Low-light hold: current brightness retained");WORDS.put("自动亮度暂停；主辅光感继续低频监听，持续变亮后恢复自动。","Auto brightness paused; low-rate sensor monitoring restores auto after sustained light.");
        WORDS.put("主光感监听","Main sensor watch");WORDS.put("辅助光感监听","Aux sensor watch");WORDS.put(" 秒后恢复"," s to resume auto");
        WORDS.put("暗光锁定低频监听主辅光感，环境显著变亮后恢复自动。主屏弹窗直接接管背光节点，关闭弹窗仍保持；恢复自动、息屏或进入息屏显示后释放，重新亮屏不自动接管。","Dark lock monitors both sensors at low rate and restores auto when the environment becomes bright. The main-panel popup holds raw backlight after closing. Auto mode, screen off or AOD releases it; unlocking restores the retained selection.");
        WORDS.put("主屏操作未完成","Main-display operation incomplete");
        WORDS.put("HyperLux · 主屏亮度","HyperLux · Main display");
        WORDS.put("正在读取主屏节点…","Reading main-display node…");
        WORDS.put("当前 ","Current ");
        WORDS.put("目标 ","Target ");
        WORDS.put("节点上限 ","Node maximum ");
        WORDS.put("节点上限 —","Node maximum —");
        WORDS.put("输入节点值","Enter node value");
        WORDS.put("输入主屏节点值","Enter main-display node value");
        WORDS.put("直接调主屏背光节点，可超过系统普通滑条范围。数值不是 nit；实际亮度取决于驱动。高亮会增加发热与耗电。","Direct panel control can exceed the ordinary system slider. Values are not nits; output depends on the driver. High brightness increases heat and power use.");
        WORDS.put("关闭弹窗仍保持选择；开启自动亮度或锁屏即退让。","Closing the popup keeps the choice. Enabling auto or locking the screen releases control.");
        WORDS.put("未找到可用的主屏背光节点","No supported main-display backlight node");
        WORDS.put("节点亮度保持中","Holding panel brightness");
        WORDS.put("等待光感读数","Waiting for sensor readings");
        WORDS.put("手动模式；滑动接管节点","Manual mode; drag to control the panel");
        WORDS.put("先启用引擎；刚更新应用需重启","Enable the engine; reboot after updating");
        WORDS.put("请输入范围内的整数","Enter an integer within the range");
        WORDS.put("主屏节点亮度","Main-display node brightness");
        WORDS.put("点击打开独立弹窗，直接写主屏背光节点；滑动关闭自动亮度，重新开启自动亮度即退让。","Opens a standalone popup with direct main-panel writes. Dragging disables auto; enabling auto releases control.");
        WORDS.put("滑条上限读取主屏 max_brightness，可超过系统普通滑条。小型 C 守护仅在接管期间运行；锁屏或恢复自动后释放节点。","Uses main-panel max_brightness, beyond the ordinary system slider. A small C guard runs only during takeover; screen lock or auto releases the node.");
        WORDS.put("锁屏期间释放节点，解锁后恢复选择；开启自动亮度结束保持。","Releases the node while locked and restores your choice after unlock. Auto brightness ends the hold.");
        WORDS.put("手动保持中","Manual hold active");
        WORDS.put("解锁后恢复","Restores after unlock");
        WORDS.put("滑动接管","Drag to take control");
        WORDS.put("主屏输出接口尚未兼容","Main-display output isolation is not supported yet");
        WORDS.put("滑条上限读取主屏 max_brightness，可超过系统普通滑条。小型 C 守护保持目标；锁屏期间释放节点，解锁后恢复，开启自动亮度结束保持。","Uses the main-panel max_brightness, beyond the ordinary slider. The native guard releases the node while locked, restores after unlock, and yields to auto brightness.");
        WORDS.put("目标节点","Target");WORDS.put("节点读回","Readback");WORDS.put("节点上限","Node limit");
        WORDS.put("输入数值","Enter value");WORDS.put("节点最大值","Node maximum");WORDS.put("恢复自动","Restore auto");
        WORDS.put("驱动反馈：","Driver feedback: ");WORDS.put("（节点单位，非 nit）"," (node units, not nits)");
        WORDS.put("拖动按相对距离调节。锁屏暂停，解锁恢复；开启自动亮度结束保持。","Drag by relative distance. Pauses while locked, restores after unlock. Auto brightness ends the hold.");
        WORDS.put("100% 为驱动公布的节点上限，不是 nit；实际亮度仍受面板限制，高亮会增加发热与耗电。","100% is the driver's node limit, not nits. Panel limits still apply; high brightness increases heat and power use.");
        WORDS.put("强光优先","Outdoor maximum");
        WORDS.put("系统不支持","Unsupported system");WORDS.put("当前仅支持 HyperOS 4","HyperOS 4 is required");WORDS.put("系统版本不支持","Unsupported system version");
        WORDS.put("版本未识别","Version unknown");WORDS.put("未能识别系统版本","System version not identified");
        WORDS.put("检测到系统版本：","Detected system version: ");WORDS.put("未能识别","Not identified");WORDS.put("版本属性不一致","Version properties disagree");
        WORDS.put("HyperLux 当前仅支持 HyperOS 4。HyperOS 3 等版本无法使用，授权 Root、启用 LSPosed 或重启不能解决此兼容问题。","HyperLux currently supports HyperOS 4 only. HyperOS 3 and other versions are unsupported. Root access, enabling LSPosed or rebooting cannot resolve this compatibility issue.");
        WORDS.put("未能识别 HyperOS 版本；请核对系统设置中的版本号。","Unable to identify the HyperOS version. Check the version in system settings.");
        WORDS.put("强光优先：全强度目标达到本机映射上限；支持时提前触发 HBM，保留原时间预算与保护。保存后生效。","Outdoor maximum targets the device mapping limit at full intensity. Where supported, HBM starts earlier with its original time budget and protections. Save to apply.");
        PHRASES=new ArrayList<>(WORDS.entrySet());PHRASES.sort((a,b)->Integer.compare(b.getKey().length(),a.getKey().length()));
    }
    public static String translate(String text,boolean english){
        if(text==null||!english)return text;
        String exact=WORDS.get(text);if(exact!=null)return exact;
        for(Map.Entry<String,String> item:PHRASES)text=text.replace(item.getKey(),item.getValue());
        return text;
    }
}
