/* Typed daemon state. Reserved fields preserve the oracle layout during validation. */
#pragma once
#include <stdint.h>
#include <stddef.h>
#include "learning.h"
typedef struct IosState {
    uint8_t reserved_0000[6328];
    char fini_array_with_sentinels[24];
    int32_t g_max;
    int32_t cfg_thermal_hard_trigger;
    int32_t cfg_thermal_hard_resume;
    float cfg_thermal_hard_floor_pct;
    int32_t cfg_charging_heat_guard;
    int32_t cached_auto;
    int32_t g_power_interactive;
    char g_last_display_state[24];
    char g_brightness_owner[32];
    char g_power_wakefulness[16];
    volatile int32_t g_run;
    char g_lux_source[16];
    float last_stable_lux;
    int32_t prev_auto_mode;
    int32_t g_wake_readonly_last_hw;
    char g_write_gov_reason[32];
    int32_t current_poll_ms;
    char g_config_error[96];
    char g_wake_source[16];
    float lux_prev4;
    float lux_prev3;
    float lux_prev2;
    float lux_prev1;
    int32_t cached_slider;
    float cfg_hl_threshold;
    int32_t cfg_min_step;
    char cfg_hbm_off_value[32];
    float cfg_alpha_fast;
    float cfg_alpha_mid;
    float cfg_alpha_slow;
    float cfg_fast_thresh;
    float cfg_slow_thresh;
    float cfg_spike_up;
    float cfg_spike_down;
    float cfg_hyst_low;
    float cfg_hyst_high;
    float cfg_gamma;
    float cfg_brighten_speed;
    float cfg_darken_speed;
    int32_t cfg_thermal_cap_enable;
    float cfg_hl_extreme_lux;
    float cfg_hl_boost_max;
    float cfg_hl_min_pct;
    int32_t cfg_hl_cooldown_ms;
    int32_t cfg_hl_temp_thresh;
    int32_t cfg_hl_temp_resume;
    int32_t cfg_hl_bat_thresh;
    int32_t cfg_hl_hbm_enable;
    char cfg_hbm_on_value[32];
    float cfg_learn_strength;
    float cfg_learn_max_offset;
    int32_t cfg_learn_sample_delay_ms;
    float cfg_learn_decay_days;
    float cfg_learn_curve_sigma;
    float cfg_learn_time_neighbor;
    int32_t cfg_learn_min_delta;
    char hl_hbm_discovery[32];
    int32_t g_sensor_rate_mode;
    uint64_t last_settings_xml_size;
    char cached_slider_source[16];
    char settings_read_source[16];
    float g_front_lux;
    float g_back_lux;
    char hl_last_block_reason[32];
    int32_t g_last_write_readback;
    float g_low_lux_bright_spike_raw;
    char g_thermal_guard_source[32];
    char g_reason_primary[24];
    int32_t g_cached_battery_cap;
    int32_t prev_slider_val;
    uint8_t reserved_1b70[16];
    int32_t cfg_learn_enabled;
    uint8_t reserved_1b84[4];
    uint64_t cfg_last_mtime;
    uint8_t hl_hbm_discovery_attempted;
    uint8_t reserved_1b91[3];
    uint8_t g_ndk_ok;
    uint8_t reserved_1b95[11];
    float trend_lux[5];
    uint8_t reserved_1bb4[4];
    int32_t g_tr_0;
    uint8_t reserved_1bbc[4];
    int32_t g_tr_1;
    uint8_t reserved_1bc4[4];
    uint64_t g_tr_2;
    int32_t g_tr_3;
    uint8_t reserved_1bd4[4];
    uint64_t g_wake_readonly_until;
    int32_t g_wake_readonly_extends;
    uint8_t g_target_hold_active;
    uint8_t reserved_1be5[3];
    uint8_t g_gov_hold;
    uint8_t reserved_1be9[3];
    int32_t g_gov_last_dir;
    uint64_t g_low_lux_rise_confirmed_until;
    int32_t g_low_lux_rise_confirmed_samples;
    int32_t g_low_lux_rise_ceiling_br;
    uint64_t g_low_lux_rise_fallback_hold_until;
    int32_t g_zero_lux_recent_mask;
    int32_t stable_count;
    uint64_t g_wake_guard_until;
    uint64_t g_last_lux_event_ms;
    volatile int32_t g_reset_learn;
    volatile int32_t g_reload_config;
    volatile int32_t g_reload_learn;
    uint8_t reserved_1c2c[4];
    uint64_t g_learn_reset_settle_until;
    uint8_t g_transition_active;
    uint8_t reserved_1c39[7];
    uint64_t g_last_actuator_ms;
    int32_t g_actuator_frame_ms;
    int32_t g_thermal_emergency_bypass;
    int32_t bright_cnt;
    int32_t dark_cnt;
    int32_t g_actuator_only_count;
    uint8_t g_light_sensors_enabled;
    uint8_t reserved_1c5d[3];
    uint64_t g_last_screen_edge_ms;
    uint64_t learn_pending_since_ms;
    int32_t learn_pending_sample_count;
    uint8_t reserved_1c74[4];
    float learn_pending_lux_sum;
    uint8_t reserved_1c7c[4];
    float learn_pending_lux_sum_mirror;
    uint8_t reserved_1c84[4];
    uint8_t learn_pending_committed;
    uint8_t reserved_1c89[3];
    int32_t g_wake_hw_br;
    uint64_t g_wake_sensor_settle_until;
    uint8_t g_external_write_hold;
    uint8_t reserved_1c99[7];
    uint64_t g_external_write_hold_until;
    int32_t g_external_write_burst_count;
    uint8_t reserved_1cac[4];
    uint64_t g_external_write_burst_start_ms;
    int32_t fast_dark_confirm_cnt;
    int32_t fast_dark_streak;
    uint64_t g_zero_lux_since;
    uint8_t g_low_lux_bright_spike_guard;
    uint8_t reserved_1cc9[3];
    int32_t g_low_lux_bright_spike_count;
    uint64_t g_low_lux_bright_spike_since;
    int32_t g_transition_retarget_count;
    int32_t g_aod_enabled;
    uint8_t g_learn_dirty;
    uint8_t reserved_1ce1[7];
    uint64_t g_last_learn_flush_ms;
    int32_t g_wake_lux_sample_count;
    int32_t trend_idx;
    int32_t trend_filled;
    uint8_t reserved_1cfc[4];
    uint64_t g_last_processed_lux_event_ms;
    float g_actuator_smooth_lux;
    uint8_t g_lux_valid;
    uint8_t reserved_1d0d[3];
    uint64_t g_last_write_ms;
    int32_t g_proximity_near;
    uint8_t reserved_1d1c[4];
    uint64_t g_dark_drop_until;
    int32_t fast_dark;
    uint8_t fast_dark_candidate;
    uint8_t reserved_1d2d[3];
    uint64_t g_sensor_reactive_until;
    uint8_t g_zero_lux_suspect;
    uint8_t reserved_1d39[3];
    int32_t g_dark_drop_confirm_count;
    uint64_t g_dark_settle_until;
    int32_t g_actuator_fast_dark;
    uint8_t g_sensor_stale;
    uint8_t reserved_1d4d[3];
    uint8_t g_sensor_hold_active;
    uint8_t reserved_1d51[3];
    uint8_t hl_active;
    uint8_t reserved_1d55[3];
    uint8_t hl_hbm_active;
    uint8_t reserved_1d59[3];
    int32_t g_wake_target_raw;
    int32_t g_wake_target_clamped;
    uint8_t g_heat_guard_active;
    uint8_t reserved_1d65[3];
    uint8_t g_thermal_entry;
    uint8_t reserved_1d69[3];
    uint8_t cached_auto_adj_valid;
    uint8_t reserved_1d6d[3];
    int32_t g_last_stable_on_hits;
    int32_t g_last_stable_on_br;
    float g_last_stable_on_lux;
    uint8_t reserved_1d7c[4];
    uint64_t g_last_stable_on_ms;
    int32_t g_target_candidate_dir;
    int32_t hl_confirm_cnt;
    int32_t hl_trigger_cnt;
    int32_t learn_commit_cnt;
    char hl_hbm_path[256];
    uint8_t g_config_valid;
    uint8_t reserved_1e99[3];
    int32_t cfg_config_version;
    int32_t cfg_hl_max_active_ms;
    char cfg_hbm_node_path[256];
    uint8_t reserved_1fa4[4];
    LearnCell g_learn[11][4];
    float g_global_offset;
    int32_t hl_hbm_found;
    void *h_lib;
    uint64_t fn_getMgrPkg;
    uint64_t fn_getMgr;
    uint64_t fn_getDefSensor;
    uint64_t fn_createEQ;
    uint64_t fn_destroyEQ;
    uint64_t fn_enable;
    uint64_t fn_disable;
    uint64_t fn_setRate;
    uint64_t fn_getEvents;
    uint64_t fn_minDelay;
    uint64_t fn_looperPrepare;
    uint64_t fn_looperPoll;
    uint64_t fn_getSensorList;
    uint64_t fn_getType;
    uint64_t fn_getName;
    void *g_mgr;
    void *g_eq;
    void *g_front_sensor;
    int32_t g_sensor_rate_us;
    uint8_t reserved_246c[4];
    void *g_back_sensor;
    uint8_t g_back_ok;
    uint8_t reserved_2479[7];
    void *g_prox_sensor;
    uint8_t g_prox_ok;
    uint8_t reserved_2489[3];
    char g_sensor_path[256];
    uint8_t reserved_258c[4];
    uint64_t last_settings_ms;
    uint64_t last_settings_xml_mtime;
    uint64_t last_settings_shell_ms;
    float cached_auto_adj;
    char settings_read_error[64];
    uint8_t reserved_25ec[4];
    uint64_t g_last_aod_check_ms;
    uint8_t g_target_debounce_init;
    uint8_t reserved_25f9[3];
    int32_t g_target_debounce_br;
    int32_t g_target_candidate_br;
    uint8_t reserved_2604[4];
    uint64_t g_target_candidate_since;
    uint64_t g_front_sensor_timestamp_ns;
    uint64_t g_front_lux_event_ms;
    int32_t g_sensor_nan_count;
    uint8_t reserved_2624[4];
    uint64_t g_back_sensor_timestamp_ns;
    uint64_t g_back_lux_event_ms;
    uint64_t g_back_confirm_event_ms;
    int32_t g_back_fallback_confirm_count;
    uint8_t reserved_2644[4];
    uint64_t g_sensor_hold_since_ms;
    uint8_t g_sensor_hold_timeout;
    uint8_t reserved_2651[3];
    char g_sensor_stale_source[24];
    uint8_t hl_exiting;
    uint8_t reserved_266d[3];
    int32_t hl_boost_br;
    char g_wake_lux_samples[20];
    int32_t g_wake_lux_sample_index;
    uint8_t reserved_268c[4];
    uint64_t g_wake_last_lux_event_ms;
    uint64_t cfg_last_check_ms;
    uint64_t g_gov_hold_until;
    int32_t g_write_readback_mismatch_streak;
    int32_t g_last_write_result;
    int32_t g_thermal_temp;
    int32_t g_tz_last_class;
    int32_t g_thermal_trusted_temp_mdeg;
    int32_t g_thermal_suspect_temp_mdeg;
    char g_thermal_deny_source[32];
    uint64_t g_thermal_exit_settle_until;
    int32_t g_thermal_floor_latched_br;
    uint8_t g_thermal_source_filtered;
    uint8_t reserved_26ed[3];
    int32_t g_thermal_guard_confirm_cnt;
    int32_t g_thermal_cap_br;
    uint64_t hl_active_start;
    uint64_t hl_cooldown_until;
    char g_reason_chain[192];
    char g_learn_block_reason[64];
    uint64_t g_last_battery_read_ms;
    int32_t g_cached_charging;
    char g_tz_last_source[32];
    int32_t g_temp_battery_mdeg;
    char g_thermal_trusted_source[32];
    int32_t g_temp_charger_mdeg;
    int32_t g_temp_display_mdeg;
    char g_thermal_suspect_source[32];
    uint64_t g_last_thermal_temp_read_ms;
    uint8_t g_tz_cached;
    uint8_t reserved_2889[3];
    int32_t g_tz_count;
    int32_t g_tz_indices[12];
    char g_tz_names[384];
    int32_t g_tz_classes[12];
    uint8_t hl_thermal_blocked;
    uint8_t reserved_2a71[7];
    uint64_t hl_exit_start;
    int32_t g_sensor_zero_streak;
    int32_t g_sensor_max_streak;
} IosState;
extern IosState ios_state;
extern const IosState ios_default_state;
_Static_assert(sizeof(IosState) == 10888, "State layout compatibility");
_Static_assert(offsetof(IosState,fini_array_with_sentinels) == 6328, "fini_array_with_sentinels layout");
_Static_assert(offsetof(IosState,g_max) == 6352, "g_max layout");
_Static_assert(offsetof(IosState,cfg_thermal_hard_trigger) == 6356, "cfg_thermal_hard_trigger layout");
_Static_assert(offsetof(IosState,cfg_thermal_hard_resume) == 6360, "cfg_thermal_hard_resume layout");
_Static_assert(offsetof(IosState,cfg_thermal_hard_floor_pct) == 6364, "cfg_thermal_hard_floor_pct layout");
_Static_assert(offsetof(IosState,cfg_charging_heat_guard) == 6368, "cfg_charging_heat_guard layout");
_Static_assert(offsetof(IosState,cached_auto) == 6372, "cached_auto layout");
_Static_assert(offsetof(IosState,g_power_interactive) == 6376, "g_power_interactive layout");
_Static_assert(offsetof(IosState,g_last_display_state) == 6380, "g_last_display_state layout");
_Static_assert(offsetof(IosState,g_brightness_owner) == 6404, "g_brightness_owner layout");
_Static_assert(offsetof(IosState,g_power_wakefulness) == 6436, "g_power_wakefulness layout");
_Static_assert(offsetof(IosState,g_run) == 6452, "g_run layout");
_Static_assert(offsetof(IosState,g_lux_source) == 6456, "g_lux_source layout");
_Static_assert(offsetof(IosState,last_stable_lux) == 6472, "last_stable_lux layout");
_Static_assert(offsetof(IosState,prev_auto_mode) == 6476, "prev_auto_mode layout");
_Static_assert(offsetof(IosState,g_wake_readonly_last_hw) == 6480, "g_wake_readonly_last_hw layout");
_Static_assert(offsetof(IosState,g_write_gov_reason) == 6484, "g_write_gov_reason layout");
_Static_assert(offsetof(IosState,current_poll_ms) == 6516, "current_poll_ms layout");
_Static_assert(offsetof(IosState,g_config_error) == 6520, "g_config_error layout");
_Static_assert(offsetof(IosState,g_wake_source) == 6616, "g_wake_source layout");
_Static_assert(offsetof(IosState,lux_prev4) == 6632, "lux_prev4 layout");
_Static_assert(offsetof(IosState,lux_prev3) == 6636, "lux_prev3 layout");
_Static_assert(offsetof(IosState,lux_prev2) == 6640, "lux_prev2 layout");
_Static_assert(offsetof(IosState,lux_prev1) == 6644, "lux_prev1 layout");
_Static_assert(offsetof(IosState,cached_slider) == 6648, "cached_slider layout");
_Static_assert(offsetof(IosState,cfg_hl_threshold) == 6652, "cfg_hl_threshold layout");
_Static_assert(offsetof(IosState,cfg_min_step) == 6656, "cfg_min_step layout");
_Static_assert(offsetof(IosState,cfg_hbm_off_value) == 6660, "cfg_hbm_off_value layout");
_Static_assert(offsetof(IosState,cfg_alpha_fast) == 6692, "cfg_alpha_fast layout");
_Static_assert(offsetof(IosState,cfg_alpha_mid) == 6696, "cfg_alpha_mid layout");
_Static_assert(offsetof(IosState,cfg_alpha_slow) == 6700, "cfg_alpha_slow layout");
_Static_assert(offsetof(IosState,cfg_fast_thresh) == 6704, "cfg_fast_thresh layout");
_Static_assert(offsetof(IosState,cfg_slow_thresh) == 6708, "cfg_slow_thresh layout");
_Static_assert(offsetof(IosState,cfg_spike_up) == 6712, "cfg_spike_up layout");
_Static_assert(offsetof(IosState,cfg_spike_down) == 6716, "cfg_spike_down layout");
_Static_assert(offsetof(IosState,cfg_hyst_low) == 6720, "cfg_hyst_low layout");
_Static_assert(offsetof(IosState,cfg_hyst_high) == 6724, "cfg_hyst_high layout");
_Static_assert(offsetof(IosState,cfg_gamma) == 6728, "cfg_gamma layout");
_Static_assert(offsetof(IosState,cfg_brighten_speed) == 6732, "cfg_brighten_speed layout");
_Static_assert(offsetof(IosState,cfg_darken_speed) == 6736, "cfg_darken_speed layout");
_Static_assert(offsetof(IosState,cfg_thermal_cap_enable) == 6740, "cfg_thermal_cap_enable layout");
_Static_assert(offsetof(IosState,cfg_hl_extreme_lux) == 6744, "cfg_hl_extreme_lux layout");
_Static_assert(offsetof(IosState,cfg_hl_boost_max) == 6748, "cfg_hl_boost_max layout");
_Static_assert(offsetof(IosState,cfg_hl_min_pct) == 6752, "cfg_hl_min_pct layout");
_Static_assert(offsetof(IosState,cfg_hl_cooldown_ms) == 6756, "cfg_hl_cooldown_ms layout");
_Static_assert(offsetof(IosState,cfg_hl_temp_thresh) == 6760, "cfg_hl_temp_thresh layout");
_Static_assert(offsetof(IosState,cfg_hl_temp_resume) == 6764, "cfg_hl_temp_resume layout");
_Static_assert(offsetof(IosState,cfg_hl_bat_thresh) == 6768, "cfg_hl_bat_thresh layout");
_Static_assert(offsetof(IosState,cfg_hl_hbm_enable) == 6772, "cfg_hl_hbm_enable layout");
_Static_assert(offsetof(IosState,cfg_hbm_on_value) == 6776, "cfg_hbm_on_value layout");
_Static_assert(offsetof(IosState,cfg_learn_strength) == 6808, "cfg_learn_strength layout");
_Static_assert(offsetof(IosState,cfg_learn_max_offset) == 6812, "cfg_learn_max_offset layout");
_Static_assert(offsetof(IosState,cfg_learn_sample_delay_ms) == 6816, "cfg_learn_sample_delay_ms layout");
_Static_assert(offsetof(IosState,cfg_learn_decay_days) == 6820, "cfg_learn_decay_days layout");
_Static_assert(offsetof(IosState,cfg_learn_curve_sigma) == 6824, "cfg_learn_curve_sigma layout");
_Static_assert(offsetof(IosState,cfg_learn_time_neighbor) == 6828, "cfg_learn_time_neighbor layout");
_Static_assert(offsetof(IosState,cfg_learn_min_delta) == 6832, "cfg_learn_min_delta layout");
_Static_assert(offsetof(IosState,hl_hbm_discovery) == 6836, "hl_hbm_discovery layout");
_Static_assert(offsetof(IosState,g_sensor_rate_mode) == 6868, "g_sensor_rate_mode layout");
_Static_assert(offsetof(IosState,last_settings_xml_size) == 6872, "last_settings_xml_size layout");
_Static_assert(offsetof(IosState,cached_slider_source) == 6880, "cached_slider_source layout");
_Static_assert(offsetof(IosState,settings_read_source) == 6896, "settings_read_source layout");
_Static_assert(offsetof(IosState,g_front_lux) == 6912, "g_front_lux layout");
_Static_assert(offsetof(IosState,g_back_lux) == 6916, "g_back_lux layout");
_Static_assert(offsetof(IosState,hl_last_block_reason) == 6920, "hl_last_block_reason layout");
_Static_assert(offsetof(IosState,g_last_write_readback) == 6952, "g_last_write_readback layout");
_Static_assert(offsetof(IosState,g_low_lux_bright_spike_raw) == 6956, "g_low_lux_bright_spike_raw layout");
_Static_assert(offsetof(IosState,g_thermal_guard_source) == 6960, "g_thermal_guard_source layout");
_Static_assert(offsetof(IosState,g_reason_primary) == 6992, "g_reason_primary layout");
_Static_assert(offsetof(IosState,g_cached_battery_cap) == 7016, "g_cached_battery_cap layout");
_Static_assert(offsetof(IosState,prev_slider_val) == 7020, "prev_slider_val layout");
_Static_assert(offsetof(IosState,cfg_learn_enabled) == 7040, "cfg_learn_enabled layout");
_Static_assert(offsetof(IosState,cfg_last_mtime) == 7048, "cfg_last_mtime layout");
_Static_assert(offsetof(IosState,hl_hbm_discovery_attempted) == 7056, "hl_hbm_discovery_attempted layout");
_Static_assert(offsetof(IosState,g_ndk_ok) == 7060, "g_ndk_ok layout");
_Static_assert(offsetof(IosState,trend_lux) == 7072, "trend_lux layout");
_Static_assert(offsetof(IosState,g_tr_0) == 7096, "g_tr_0 layout");
_Static_assert(offsetof(IosState,g_tr_1) == 7104, "g_tr_1 layout");
_Static_assert(offsetof(IosState,g_tr_2) == 7112, "g_tr_2 layout");
_Static_assert(offsetof(IosState,g_tr_3) == 7120, "g_tr_3 layout");
_Static_assert(offsetof(IosState,g_wake_readonly_until) == 7128, "g_wake_readonly_until layout");
_Static_assert(offsetof(IosState,g_wake_readonly_extends) == 7136, "g_wake_readonly_extends layout");
_Static_assert(offsetof(IosState,g_target_hold_active) == 7140, "g_target_hold_active layout");
_Static_assert(offsetof(IosState,g_gov_hold) == 7144, "g_gov_hold layout");
_Static_assert(offsetof(IosState,g_gov_last_dir) == 7148, "g_gov_last_dir layout");
_Static_assert(offsetof(IosState,g_low_lux_rise_confirmed_until) == 7152, "g_low_lux_rise_confirmed_until layout");
_Static_assert(offsetof(IosState,g_low_lux_rise_confirmed_samples) == 7160, "g_low_lux_rise_confirmed_samples layout");
_Static_assert(offsetof(IosState,g_low_lux_rise_ceiling_br) == 7164, "g_low_lux_rise_ceiling_br layout");
_Static_assert(offsetof(IosState,g_low_lux_rise_fallback_hold_until) == 7168, "g_low_lux_rise_fallback_hold_until layout");
_Static_assert(offsetof(IosState,g_zero_lux_recent_mask) == 7176, "g_zero_lux_recent_mask layout");
_Static_assert(offsetof(IosState,stable_count) == 7180, "stable_count layout");
_Static_assert(offsetof(IosState,g_wake_guard_until) == 7184, "g_wake_guard_until layout");
_Static_assert(offsetof(IosState,g_last_lux_event_ms) == 7192, "g_last_lux_event_ms layout");
_Static_assert(offsetof(IosState,g_reset_learn) == 7200, "g_reset_learn layout");
_Static_assert(offsetof(IosState,g_reload_config) == 7204, "g_reload_config layout");
_Static_assert(offsetof(IosState,g_reload_learn) == 7208, "g_reload_learn layout");
_Static_assert(offsetof(IosState,g_learn_reset_settle_until) == 7216, "g_learn_reset_settle_until layout");
_Static_assert(offsetof(IosState,g_transition_active) == 7224, "g_transition_active layout");
_Static_assert(offsetof(IosState,g_last_actuator_ms) == 7232, "g_last_actuator_ms layout");
_Static_assert(offsetof(IosState,g_actuator_frame_ms) == 7240, "g_actuator_frame_ms layout");
_Static_assert(offsetof(IosState,g_thermal_emergency_bypass) == 7244, "g_thermal_emergency_bypass layout");
_Static_assert(offsetof(IosState,bright_cnt) == 7248, "bright_cnt layout");
_Static_assert(offsetof(IosState,dark_cnt) == 7252, "dark_cnt layout");
_Static_assert(offsetof(IosState,g_actuator_only_count) == 7256, "g_actuator_only_count layout");
_Static_assert(offsetof(IosState,g_light_sensors_enabled) == 7260, "g_light_sensors_enabled layout");
_Static_assert(offsetof(IosState,g_last_screen_edge_ms) == 7264, "g_last_screen_edge_ms layout");
_Static_assert(offsetof(IosState,learn_pending_since_ms) == 7272, "g_learn_pending_3 layout");
_Static_assert(offsetof(IosState,learn_pending_sample_count) == 7280, "g_learn_pending_4 layout");
_Static_assert(offsetof(IosState,learn_pending_lux_sum) == 7288, "g_learn_pending_5 layout");
_Static_assert(offsetof(IosState,learn_pending_lux_sum_mirror) == 7296, "g_learn_pending_6 layout");
_Static_assert(offsetof(IosState,learn_pending_committed) == 7304, "g_learn_pending_7 layout");
_Static_assert(offsetof(IosState,g_wake_hw_br) == 7308, "g_wake_hw_br layout");
_Static_assert(offsetof(IosState,g_wake_sensor_settle_until) == 7312, "g_wake_sensor_settle_until layout");
_Static_assert(offsetof(IosState,g_external_write_hold) == 7320, "g_external_write_hold layout");
_Static_assert(offsetof(IosState,g_external_write_hold_until) == 7328, "g_external_write_hold_until layout");
_Static_assert(offsetof(IosState,g_external_write_burst_count) == 7336, "g_external_write_burst_count layout");
_Static_assert(offsetof(IosState,g_external_write_burst_start_ms) == 7344, "g_external_write_burst_start_ms layout");
_Static_assert(offsetof(IosState,fast_dark_confirm_cnt) == 7352, "fast_dark_confirm_cnt layout");
_Static_assert(offsetof(IosState,fast_dark_streak) == 7356, "fast_dark_streak layout");
_Static_assert(offsetof(IosState,g_zero_lux_since) == 7360, "g_zero_lux_since layout");
_Static_assert(offsetof(IosState,g_low_lux_bright_spike_guard) == 7368, "g_low_lux_bright_spike_guard layout");
_Static_assert(offsetof(IosState,g_low_lux_bright_spike_count) == 7372, "g_low_lux_bright_spike_count layout");
_Static_assert(offsetof(IosState,g_low_lux_bright_spike_since) == 7376, "g_low_lux_bright_spike_since layout");
_Static_assert(offsetof(IosState,g_transition_retarget_count) == 7384, "g_transition_retarget_count layout");
_Static_assert(offsetof(IosState,g_aod_enabled) == 7388, "g_aod_enabled layout");
_Static_assert(offsetof(IosState,g_learn_dirty) == 7392, "g_learn_dirty layout");
_Static_assert(offsetof(IosState,g_last_learn_flush_ms) == 7400, "g_last_learn_flush_ms layout");
_Static_assert(offsetof(IosState,g_wake_lux_sample_count) == 7408, "g_wake_lux_sample_count layout");
_Static_assert(offsetof(IosState,trend_idx) == 7412, "trend_idx layout");
_Static_assert(offsetof(IosState,trend_filled) == 7416, "trend_filled layout");
_Static_assert(offsetof(IosState,g_last_processed_lux_event_ms) == 7424, "g_last_processed_lux_event_ms layout");
_Static_assert(offsetof(IosState,g_actuator_smooth_lux) == 7432, "g_actuator_smooth_lux layout");
_Static_assert(offsetof(IosState,g_lux_valid) == 7436, "g_lux_valid layout");
_Static_assert(offsetof(IosState,g_last_write_ms) == 7440, "g_last_write_ms layout");
_Static_assert(offsetof(IosState,g_proximity_near) == 7448, "g_proximity_near layout");
_Static_assert(offsetof(IosState,g_dark_drop_until) == 7456, "g_dark_drop_until layout");
_Static_assert(offsetof(IosState,fast_dark) == 7464, "fast_dark layout");
_Static_assert(offsetof(IosState,fast_dark_candidate) == 7468, "fast_dark_candidate layout");
_Static_assert(offsetof(IosState,g_sensor_reactive_until) == 7472, "g_sensor_reactive_until layout");
_Static_assert(offsetof(IosState,g_zero_lux_suspect) == 7480, "g_zero_lux_suspect layout");
_Static_assert(offsetof(IosState,g_dark_drop_confirm_count) == 7484, "g_dark_drop_confirm_count layout");
_Static_assert(offsetof(IosState,g_dark_settle_until) == 7488, "g_dark_settle_until layout");
_Static_assert(offsetof(IosState,g_actuator_fast_dark) == 7496, "g_actuator_fast_dark layout");
_Static_assert(offsetof(IosState,g_sensor_stale) == 7500, "g_sensor_stale layout");
_Static_assert(offsetof(IosState,g_sensor_hold_active) == 7504, "g_sensor_hold_active layout");
_Static_assert(offsetof(IosState,hl_active) == 7508, "hl_active layout");
_Static_assert(offsetof(IosState,hl_hbm_active) == 7512, "hl_hbm_active layout");
_Static_assert(offsetof(IosState,g_wake_target_raw) == 7516, "g_wake_target_raw layout");
_Static_assert(offsetof(IosState,g_wake_target_clamped) == 7520, "g_wake_target_clamped layout");
_Static_assert(offsetof(IosState,g_heat_guard_active) == 7524, "g_heat_guard_active layout");
_Static_assert(offsetof(IosState,g_thermal_entry) == 7528, "g_thermal_entry layout");
_Static_assert(offsetof(IosState,cached_auto_adj_valid) == 7532, "cached_auto_adj_valid layout");
_Static_assert(offsetof(IosState,g_last_stable_on_hits) == 7536, "g_last_stable_on_hits layout");
_Static_assert(offsetof(IosState,g_last_stable_on_br) == 7540, "g_last_stable_on_br layout");
_Static_assert(offsetof(IosState,g_last_stable_on_lux) == 7544, "g_last_stable_on_lux layout");
_Static_assert(offsetof(IosState,g_last_stable_on_ms) == 7552, "g_last_stable_on_ms layout");
_Static_assert(offsetof(IosState,g_target_candidate_dir) == 7560, "g_target_candidate_dir layout");
_Static_assert(offsetof(IosState,hl_confirm_cnt) == 7564, "hl_confirm_cnt layout");
_Static_assert(offsetof(IosState,hl_trigger_cnt) == 7568, "hl_trigger_cnt layout");
_Static_assert(offsetof(IosState,learn_commit_cnt) == 7572, "learn_commit_cnt layout");
_Static_assert(offsetof(IosState,hl_hbm_path) == 7576, "hl_hbm_path layout");
_Static_assert(offsetof(IosState,g_config_valid) == 7832, "g_config_valid layout");
_Static_assert(offsetof(IosState,cfg_config_version) == 7836, "cfg_config_version layout");
_Static_assert(offsetof(IosState,cfg_hl_max_active_ms) == 7840, "cfg_hl_max_active_ms layout");
_Static_assert(offsetof(IosState,cfg_hbm_node_path) == 7844, "cfg_hbm_node_path layout");
_Static_assert(offsetof(IosState,g_learn) == 8104, "g_learn layout");
_Static_assert(offsetof(IosState,g_global_offset) == 9160, "g_global_offset layout");
_Static_assert(offsetof(IosState,hl_hbm_found) == 9164, "hl_hbm_found layout");
_Static_assert(offsetof(IosState,h_lib) == 9168, "h_lib layout");
_Static_assert(offsetof(IosState,fn_getMgrPkg) == 9176, "fn_getMgrPkg layout");
_Static_assert(offsetof(IosState,fn_getMgr) == 9184, "fn_getMgr layout");
_Static_assert(offsetof(IosState,fn_getDefSensor) == 9192, "fn_getDefSensor layout");
_Static_assert(offsetof(IosState,fn_createEQ) == 9200, "fn_createEQ layout");
_Static_assert(offsetof(IosState,fn_destroyEQ) == 9208, "fn_destroyEQ layout");
_Static_assert(offsetof(IosState,fn_enable) == 9216, "fn_enable layout");
_Static_assert(offsetof(IosState,fn_disable) == 9224, "fn_disable layout");
_Static_assert(offsetof(IosState,fn_setRate) == 9232, "fn_setRate layout");
_Static_assert(offsetof(IosState,fn_getEvents) == 9240, "fn_getEvents layout");
_Static_assert(offsetof(IosState,fn_minDelay) == 9248, "fn_minDelay layout");
_Static_assert(offsetof(IosState,fn_looperPrepare) == 9256, "fn_looperPrepare layout");
_Static_assert(offsetof(IosState,fn_looperPoll) == 9264, "fn_looperPoll layout");
_Static_assert(offsetof(IosState,fn_getSensorList) == 9272, "fn_getSensorList layout");
_Static_assert(offsetof(IosState,fn_getType) == 9280, "fn_getType layout");
_Static_assert(offsetof(IosState,fn_getName) == 9288, "fn_getName layout");
_Static_assert(offsetof(IosState,g_mgr) == 9296, "g_mgr layout");
_Static_assert(offsetof(IosState,g_eq) == 9304, "g_eq layout");
_Static_assert(offsetof(IosState,g_front_sensor) == 9312, "g_front_sensor layout");
_Static_assert(offsetof(IosState,g_sensor_rate_us) == 9320, "g_sensor_rate_us layout");
_Static_assert(offsetof(IosState,g_back_sensor) == 9328, "g_back_sensor layout");
_Static_assert(offsetof(IosState,g_back_ok) == 9336, "g_back_ok layout");
_Static_assert(offsetof(IosState,g_prox_sensor) == 9344, "g_prox_sensor layout");
_Static_assert(offsetof(IosState,g_prox_ok) == 9352, "g_prox_ok layout");
_Static_assert(offsetof(IosState,g_sensor_path) == 9356, "g_sensor_path layout");
_Static_assert(offsetof(IosState,last_settings_ms) == 9616, "last_settings_ms layout");
_Static_assert(offsetof(IosState,last_settings_xml_mtime) == 9624, "last_settings_xml_mtime layout");
_Static_assert(offsetof(IosState,last_settings_shell_ms) == 9632, "last_settings_shell_ms layout");
_Static_assert(offsetof(IosState,cached_auto_adj) == 9640, "cached_auto_adj layout");
_Static_assert(offsetof(IosState,settings_read_error) == 9644, "settings_read_error layout");
_Static_assert(offsetof(IosState,g_last_aod_check_ms) == 9712, "g_last_aod_check_ms layout");
_Static_assert(offsetof(IosState,g_target_debounce_init) == 9720, "g_target_debounce_init layout");
_Static_assert(offsetof(IosState,g_target_debounce_br) == 9724, "g_target_debounce_br layout");
_Static_assert(offsetof(IosState,g_target_candidate_br) == 9728, "g_target_candidate_br layout");
_Static_assert(offsetof(IosState,g_target_candidate_since) == 9736, "g_target_candidate_since layout");
_Static_assert(offsetof(IosState,g_front_sensor_timestamp_ns) == 9744, "g_front_sensor_timestamp_ns layout");
_Static_assert(offsetof(IosState,g_front_lux_event_ms) == 9752, "g_front_lux_event_ms layout");
_Static_assert(offsetof(IosState,g_sensor_nan_count) == 9760, "g_sensor_nan_count layout");
_Static_assert(offsetof(IosState,g_back_sensor_timestamp_ns) == 9768, "g_back_sensor_timestamp_ns layout");
_Static_assert(offsetof(IosState,g_back_lux_event_ms) == 9776, "g_back_lux_event_ms layout");
_Static_assert(offsetof(IosState,g_back_confirm_event_ms) == 9784, "g_back_confirm_event_ms layout");
_Static_assert(offsetof(IosState,g_back_fallback_confirm_count) == 9792, "g_back_fallback_confirm_count layout");
_Static_assert(offsetof(IosState,g_sensor_hold_since_ms) == 9800, "g_sensor_hold_since_ms layout");
_Static_assert(offsetof(IosState,g_sensor_hold_timeout) == 9808, "g_sensor_hold_timeout layout");
_Static_assert(offsetof(IosState,g_sensor_stale_source) == 9812, "g_sensor_stale_source layout");
_Static_assert(offsetof(IosState,hl_exiting) == 9836, "hl_exiting layout");
_Static_assert(offsetof(IosState,hl_boost_br) == 9840, "hl_boost_br layout");
_Static_assert(offsetof(IosState,g_wake_lux_samples) == 9844, "g_wake_lux_samples layout");
_Static_assert(offsetof(IosState,g_wake_lux_sample_index) == 9864, "g_wake_lux_sample_index layout");
_Static_assert(offsetof(IosState,g_wake_last_lux_event_ms) == 9872, "g_wake_last_lux_event_ms layout");
_Static_assert(offsetof(IosState,cfg_last_check_ms) == 9880, "cfg_last_check_ms layout");
_Static_assert(offsetof(IosState,g_gov_hold_until) == 9888, "g_gov_hold_until layout");
_Static_assert(offsetof(IosState,g_write_readback_mismatch_streak) == 9896, "g_write_readback_mismatch_streak layout");
_Static_assert(offsetof(IosState,g_last_write_result) == 9900, "g_last_write_result layout");
_Static_assert(offsetof(IosState,g_thermal_temp) == 9904, "g_thermal_temp layout");
_Static_assert(offsetof(IosState,g_tz_last_class) == 9908, "g_tz_last_class layout");
_Static_assert(offsetof(IosState,g_thermal_trusted_temp_mdeg) == 9912, "g_thermal_trusted_temp_mdeg layout");
_Static_assert(offsetof(IosState,g_thermal_suspect_temp_mdeg) == 9916, "g_thermal_suspect_temp_mdeg layout");
_Static_assert(offsetof(IosState,g_thermal_deny_source) == 9920, "g_thermal_deny_source layout");
_Static_assert(offsetof(IosState,g_thermal_exit_settle_until) == 9952, "g_thermal_exit_settle_until layout");
_Static_assert(offsetof(IosState,g_thermal_floor_latched_br) == 9960, "g_thermal_floor_latched_br layout");
_Static_assert(offsetof(IosState,g_thermal_source_filtered) == 9964, "g_thermal_source_filtered layout");
_Static_assert(offsetof(IosState,g_thermal_guard_confirm_cnt) == 9968, "g_thermal_guard_confirm_cnt layout");
_Static_assert(offsetof(IosState,g_thermal_cap_br) == 9972, "g_thermal_cap_br layout");
_Static_assert(offsetof(IosState,hl_active_start) == 9976, "hl_active_start layout");
_Static_assert(offsetof(IosState,hl_cooldown_until) == 9984, "hl_cooldown_until layout");
_Static_assert(offsetof(IosState,g_reason_chain) == 9992, "g_reason_chain layout");
_Static_assert(offsetof(IosState,g_learn_block_reason) == 10184, "g_learn_block_reason layout");
_Static_assert(offsetof(IosState,g_last_battery_read_ms) == 10248, "g_last_battery_read_ms layout");
_Static_assert(offsetof(IosState,g_cached_charging) == 10256, "g_cached_charging layout");
_Static_assert(offsetof(IosState,g_tz_last_source) == 10260, "g_tz_last_source layout");
_Static_assert(offsetof(IosState,g_temp_battery_mdeg) == 10292, "g_temp_battery_mdeg layout");
_Static_assert(offsetof(IosState,g_thermal_trusted_source) == 10296, "g_thermal_trusted_source layout");
_Static_assert(offsetof(IosState,g_temp_charger_mdeg) == 10328, "g_temp_charger_mdeg layout");
_Static_assert(offsetof(IosState,g_temp_display_mdeg) == 10332, "g_temp_display_mdeg layout");
_Static_assert(offsetof(IosState,g_thermal_suspect_source) == 10336, "g_thermal_suspect_source layout");
_Static_assert(offsetof(IosState,g_last_thermal_temp_read_ms) == 10368, "g_last_thermal_temp_read_ms layout");
_Static_assert(offsetof(IosState,g_tz_cached) == 10376, "g_tz_cached layout");
_Static_assert(offsetof(IosState,g_tz_count) == 10380, "g_tz_count layout");
_Static_assert(offsetof(IosState,g_tz_indices) == 10384, "g_tz_indices layout");
_Static_assert(offsetof(IosState,g_tz_names) == 10432, "g_tz_names layout");
_Static_assert(offsetof(IosState,g_tz_classes) == 10816, "g_tz_classes layout");
_Static_assert(offsetof(IosState,hl_thermal_blocked) == 10864, "hl_thermal_blocked layout");
_Static_assert(offsetof(IosState,hl_exit_start) == 10872, "hl_exit_start layout");
_Static_assert(offsetof(IosState,g_sensor_zero_streak) == 10880, "g_sensor_zero_streak layout");
_Static_assert(offsetof(IosState,g_sensor_max_streak) == 10884, "g_sensor_max_streak layout");
